### ISSUE TITLE
In-Memory Realms android

### ISSUE THREAD

**Issue by olesfalcon** [realm/realm-java#1007]
Is there any way to save realm database only in memory?

**Comment by olesfalcon** [comment]
No, i need to save my database only in memory, no files on drive.
I read documentation on iOS. 
In-Memory Realms
Normally Realms are persisted to disk, but you can also create ones which are purely in memory by using the [RLMRealm inMemoryRealmWithIdentifier:] factory method.

I need this feature on Android, it is hard to do? I can help with implementation.

**Comment by sergeyfitis** [comment]
@olesfalcon I am sure that this feature not yet implemented for android. Because this feature is not documented.

**Comment by cmelchior** [comment]
Hi @olesfalcon 

Yes, we do plan to add support for in-memory and readonly Realms just like on iOS, but havn't gotten around to do it yet.

I don't have an a good overview of what exactly we need to support it properly on Android, so while I *think* it is fairly easy, I might be wrong. You can see here in SharedGroup that we already have a Durability setting for MEM-ONLY, so if that part of the code hasn't diverged to much from Cocoa, it might just be a matter of setting that instead of FULL: https://github.com/realm/realm-java/blob/master/realm/src/main/java/io/realm/internal/SharedGroup.java#L37

However that would require yet another constructor (of which we already have too many), which is why we are adding a RealmConfiguration for handling this kind of stuff (#929).

May I ask what is the use case that prohibit you from saving it to disk?

**Comment by olesfalcon** [comment]
I need a database which can be fit in memory, as required by the project design, and requirements . Now it uses a standard SQL Android which is able to do so. But since SQL is not the best and most convenient thing in the world, I would like to use something more elegant and beautiful. Realm looks very attractive but really miss this feature.

**Comment by bmunkholm** [comment]
We can prioritise to get that in. It's just a matter of enabling the setting as @cmelchior mentions and add some testing.

**Comment by cmelchior** [comment]
Apart from minor style comments :+1:

**Comment by beeender** [comment]
#1257 has been merged into master. in-mem Realm will be in the next release.
