### ISSUE TITLE
Illegal State: Row/Object is no longer valid to operate on. Was it deleted?

### ISSUE THREAD

**Issue by tnedich** [realm/realm-java#1047]
I am geting this java.lang.IllegalStateException when I try to delete from my relm.io relm (db). I can access my TeamModel i.

> java.lang.IllegalStateException: Illegal State: Row/Object is no longer valid to operate on. Was it deleted?

```
@Override
        public boolean onActionItemClicked(ActionMode mode, MenuItem item) {

            switch (item.getItemId()) {

                case R.id.action1:

                    Realm realm = Realm.getInstance(ctx);
                    ArrayList<TeamModel> chekedTeams = new ArrayList<>();
                    chekedTeams = adapter.returnCheked();

                    Log.d("ChT","ChT " + chekedTeams.size());

                    for (TeamModel i : chekedTeams) {

                        TeamModel result2 = realm.where(TeamModel.class).equalTo("team_id", i.getTeam_id()).findFirst();
                        realm.beginTransaction();
                        result2.removeFromRealm();
                        realm.cancelTransaction();
                    }

                    adapter.resetListAfterDel();

                break;

            }

            return true;
        }
```

**Comment by bahacan19** [comment]
+1

**Comment by cmelchior** [comment]
Hi @tnedich 
It is a bit unclear what part of your code that is failing. I assume it is this line?
```
 TeamModel result2 = realm.where(TeamModel.class).equalTo("team_id", i.getTeam_id()).findFirst();
```
Are you sure that your TeamModel hasn't already been deleted by another thread? This can be checked by using ```i.isValid()```?

**Comment by tnedich** [comment]
I will close this issue because I strongly belive that is some oversight in my complete code. After debugin I belive It is not Realm.io problem.

**Comment by shahid650** [comment]
Answer: 
I got these errors , and While the solution was simple.
1- java.lang.IllegalStateException: Object is no longer managed by Realm. Has it been deleted?
2-  ThrowingException 8, Object is no longer valid to operate on. Was it deleted by another thread?, .
11-19 00:19:02.146 21759-21932/zeroturnaround.org.jrebel4androidgettingstarted E/REALM_JNI: Exception has been throw: Object is no longer valid to operate on. Was it deleted by another thread?

The Bad Code:
  if (subServiceId != null && !subServiceId.isEmpty()) {
                    mSubServiceModelDelete.setDeleted(true);
                    realm.copyToRealmOrUpdate(mSubServiceModelDelete);
                } else {

                    mSubServiceModelDelete.deleteFromRealm();
                    Log.d("TAG", "Service is Deleted from database.." + mSubServiceModelDelete.getSubservicesSubservicename());
                }

The Good and Error Free Code: 
  if (subServiceId != null && !subServiceId.isEmpty()) {
                    mSubServiceModelDelete.setDeleted(true);
                    realm.copyToRealmOrUpdate(mSubServiceModelDelete);
                } else {
                    Log.d("TAG", "Service is Deleted from database.." + mSubServiceModelDelete.getSubservicesSubservicename());
                    mSubServiceModelDelete.deleteFromRealm();
                }



So that was the Solution For This Error, This Was Error, as i was accessing deleted object after deleting it. LOL
Happy Coding :) :)
