### ISSUE TITLE
Child Activity can't find committed data

### ISSUE THREAD

**Issue by maymard** [realm/realm-java#1079]
I am using version 0.80 of the Android SDK. 
1. Main activity starts async task to get data from REST service, then within a transaction writes the data to the Realm data store.
2. The async task converts the data to views and sends it to the main activity to display.
3. User selects an item and an Intent launches a child activity to display the data
4. Child activity starts async task to get the data from Realm, but Realm doesn't find the data that was committed by the first async task.
Next time the app launches and all subsequent runs, Realm finds the data.

**Comment by emanuelez** [comment]
If the data is not found in step 4 it means that either:

1) The transaction in step 1 has not been committed yet
2) The thread from which step 4 is executed only performs Realm read operations and is not refreshed properly because it's not a Looper/Handler thread. In this case you should call refresh() manually before doing the query.

Does this help?

**Comment by cmelchior** [comment]
I assume the above answered your question. Please reopen if that was not the case.
