### ISSUE TITLE
Deleting foreignkeys and 1-1 relationships on clear()

### ISSUE THREAD

**Issue by somghosh** [realm/realm-java#1081]
I have the following Realm class

	public class Reward extends RealmObject {

	    private long id;
	    private RewardPartner rewardPartner;
	}
	

When I fetch a series of new Reward from server, I do a 

    RealmResults<Reward> results = realm.where(Reward.class).findAll();
    results.clear();
	
	
I also want at the same time the RewardPartner table to be cleared - i.e. the relevant Rewardpartners removed. Is there an easy way to do this in Realm API?

**Comment by emanuelez** [comment]
The issue of cascading deletes is a complicated one because there is no single behavior which would be optimal in all situation. Right now the only options for you is to handle this manually, maybe with a backlink from RewardPartner to Reward and then finding with a query which RewardPartners are not related to any Reward.

**Comment by somghosh** [comment]
Thanks. Is there an ondelete() function in the RealmObject class that I can
override?

**Comment by emanuelez** [comment]
Not really. It's a pretty manual process now but we're planning to make it less painful

**Comment by cmelchior** [comment]
I assume the question was answered. Please reopen if that was not the case.
