### ISSUE TITLE
Auto refresh realm and onChange callback

### ISSUE THREAD

**Issue by eboudrant** [realm/realm-java#1110]
We can perform fine notify on RecyclerView's adapter (ex: ```notifyItemInserted```, ```notifyItemDeleted```,...) is there a way in Realm to know what was the change set that fired the ```onChange``` listener when the realm is auto refresh. Se we could decide how to notify the adaper.

Currently we can only use ```notifyDataSetChanged``` which is not great when we use ```RecyclerView.ItemAnimator```.

If this is not existing yet, any plan in future ?

Thanks ~

**Comment by cmelchior** [comment]
Hi @eboudrant 
Right now there is unfortunately no way for Realm to tell you what changed, so you would have to implement that notification scheme yourself.

Fine-grained notifications are, however, very high on our TODO list and we already have one working on adding the support in the underlying storage engine which is required before we can support for it in Java. You can follow progress on the issue here: https://github.com/realm/realm-java/issues/989

**Comment by cmelchior** [comment]
Closing this as a duplicate.

**Comment by eboudrant** [comment]
Thanks for the quick update!
