### ISSUE TITLE
May be a defect of realm in android 

### ISSUE THREAD

**Issue by lipangit** [realm/realm-java#1152]
Resently I use realm in a child android library, add this aar into parent project .Like this.
![image](https://cloud.githubusercontent.com/assets/2038071/7808214/4c1a7674-03c4-11e5-95c8-589da3946b46.png)
The question is IF I use realm in parent project (** extends RealmObject) ,will occur io.realm.RealmJsonImpl muticlass exception, IF I do not use realm in parent project everything will be ok.
Goal is both in child library and parent project use realm . How to solve or  avoid this problem .

**Comment by cmelchior** [comment]
Hi @lipangit 
Realm currently doesn't work when included in both the library project and the app project due to how the annotation processor works, as you yourself has found out.

However we have been working on solving this issue using a concept called Realm Modules. This feature is already added to our master branch and we just need to merge the last API changes to make it public. 

The Realm module pull request is here:
https://github.com/realm/realm-java/pull/938

And the pull request for adding it to the public API is here (it is going through final reviews currently): 
https://github.com/realm/realm-java/pull/929

We also have an open issue for exactly this: https://github.com/realm/realm-java/issues/511 which will be updated once the above pull request has been merged.

Until then you can only work around it by only having Realm model classes in the library or app project.
