### ISSUE TITLE
DefaultModule should be created while library modules in use.

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#1302]
Problem described in so http://stackoverflow.com/questions/31450084/realm-getdefaultmodule-returns-null?noredirect=1#comment50901688_31450084

When there is no module defined in app project and defined modules in lib project are in use, default module should still be created for app.

**Comment by cmelchior** [comment]
I found the true source of the problem. It happens if you library project contains all the Realm classes/modules in which case the annotation processor for the app project never runs. This means that if the library project is configured as such, the DefaultRealmModule is never created.

In that case it would be pointless to try to use it anyway, since it would be empty. This sounds more like a documentation/javadoc fix or perhaps rename Realm.getDefaultModule() to something better?

**Comment by cmelchior** [comment]
I see a couple of solutions. Not sure which is best:

1) Add some more documentation to the website/javadoc
2) Make Realm.getDefaultModule() throw a better exception instead of returning null.
3) Make Realm.getDefaultModule() return a dummy empty module if no was found.

**Comment by beeender** [comment]
1) People will still ask even we have doc
2) The name is really long and we have to mark `getDefaultModule` deprecated. And the most common case is using the Realm in the application.
I cannot decide between 3) and 4). But it seems using an empty module won't cause anything bad, maybe we should go with 4)? It would be more convenient for refactor.
