### ISSUE TITLE
Realm Browser: ADB Pull Command Not Working Per Instructions

### ISSUE THREAD

**Issue by tzveeJ** [realm/realm-java#1305]
First of all, thanks for such an exciting new product. However, I'm currently unable to use Realm Browser for Android because the "pull" described in the stack overflow question is not working for me. (Yes, I replaced mypackagename with the actual package name.)

    ./adb pull /data/data/mypackagename/files/ .

The command is printing "remote object '/data/data/mypackagename/files/' does not exist".

I was able to shell into the device and cd into the directory (/data/data/mypackagename/files). (Side note, not sure if it matters, but using "ls" from the shell prints "opendir failed, Permission denied".) I also printed the directory path using the command at the stack overflow answer

     Log.d("", "path: " + realm.getPath());

which prints, as expected, "path: /data/data/mypackagename/files/default.realm".

Any help would be greatly appreciated.

**Comment by beeender** [comment]
Hi!
The problem is `/data/data/mypackagename` belongs to the internal storage and it is only accessible for the app or root user.

There are some options to get the realm file in the internal storage:

1 Root your device and start adb daemon with root access by

```
adb kill-server
adb root
```

2 Copy the file by the app to the external storage and pull it from external storage by adb. [`Realm.writeCopyTo()`](https://realm.io/docs/java/latest/api/io/realm/Realm.html#writeCopyTo-java.io.File-) could help in this case.


3 Use external storage to create the RealmConfiguration  in your development buid, and switch back to internal storage in the release build. like:
```
RealmConfiguration config = new RealmConfiguration.Builder(getContext().getExternalCacheDir())
                .build();

realm = Realm.getInstance(config);
```
or set it as the default configuration and use `getDefaultInstance()` to open it everywhere
```
// Only need to set it once
Realm.setDefaultConfiguration(defaultConfig);
realm = Realm.getDefaultInstance();
```

**Comment by tzveeJ** [comment]
Thank you VERY much for this amazing answer. Greatly appreciated.

**Comment by beeender** [comment]
Thanks for your feedback! I am closing this issue now. Feel free to use stackoverflow.com with `realm` tag, that would be easier to be found by other users who might have the same problem. And it is more than welcome to report issues here!

**Comment by tzveeJ** [comment]
Will do! Thanks again.
