### ISSUE TITLE
[Performance] Too many calls to native method

### ISSUE THREAD

**Issue by ypresto** [realm/realm-java#1315]
I have RealmObject with 10 fields and use findAll() to fetch 5000+ rows at once, then copy all realm field into POJO (i know it is naive implementation... :).

I found realm has performance bottleneck on native method call (especially on dalvik) because it calls native method for **each** field.
https://github.com/realm/realm-java/blob/457a8a34445741501f565c8d2304fe29e0fa330c/realm/src/main/java/io/realm/internal/UncheckedRow.java

It might be better if there is way to fetch all fields at once via native method.

**Comment by emanuelez** [comment]
Realm is built on the ground up to be a zero-copy data layer. This allows for a reliable single source of truth. When copying RealmObjects to POJOs all the consistency guarantees are lost, which is why we don't provide such methods ourselves.

What is your use-case? I would be interested to know the motivations behind your choice.

**Comment by cmelchior** [comment]
Also note if you really want to copy all data into pure Java objects, you might as well do it from a background thread, where the performance matters less.

**Comment by ypresto** [comment]
I added Realm to my existing app with POJO entities which are used in many places in app.
So conversion is necessary, for now.

I considered about using RealmObject directly instead of entities.
But it only supports standard types, and  does not supports Parcelable, and it has thread boundary... many difficulties appeared so I decide to convert it.
