### ISSUE TITLE
Read all value

### ISSUE THREAD

**Issue by yaming116** [realm/realm-java#1340]
I have a Realm Object ,how read all value.Now i do it like this;
```java
class ObjectRealm extends RealmObject{
  int id;
  String name;

... get set
}

ObjectRealm realmObj;
ObjectRealm obj = new ObjectRealm ();
obj.setId(realmObj.getId());
```

when i hava a lot feild, :sob:

**Comment by beeender** [comment]
I'd like to know what is the reason of reading all values? To copy them to another Realm?

**Comment by yaming116** [comment]
yes.

**Comment by beeender** [comment]
If you want to create a whole copy of the Realm, [`writeCopyTo()`](https://realm.io/docs/java/latest/api/io/realm/Realm.html#writeCopyTo(java.io.File)) would be the right API to use.

But if you want to create a copy of the object in the same Realm, unfortunately, there is no elegant way to do it right now. Since that requires to create a standalone object and write it back to Realm. You can follow #931 which is the feature you want in this case.

**Comment by cmelchior** [comment]
@yaming116 @beeender Actually `realm.copyToRealm()` will also work if you are copying between two Realms. At least that was the intention, so if it doesn't it is a bug.

```
// This should work
realm2.beginTransaction();
Foo foo1 = realm1.where(Foo.class).findAll().first();
Foo foo2 = realm2.copyToRealm(foo1);
realm2.commitTransaction();
```

**Comment by yaming116** [comment]
Sometimes some of my tables are not related, but I have to query data from several tables, so I put some data directly into the memory (data in multiple databases)
