### ISSUE TITLE
Why was RealmConfiguration.Builder#addModule hidden?

### ISSUE THREAD

**Issue by SleeplessByte** [realm/realm-java#1354]
In https://github.com/realm/realm-java/commit/da2637b1daeade5eab1b16a67e52db085fcd0fd2 `addModule` is made `private`. This function could be used to create a helper method in a library to add modules.

````Java
func( RealmConfiguration.Builder builder ) {
  builder.addModule( SomeLibraryModuleInstance )   
}

**Comment by cmelchior** [comment]
We had two reasons:

1) Specifying the full schema in the same location increases transparency with regard to what classes can be saved in the Realm. 
2) Having the `addModule` public was a bit confusing when there was also a `setModules` method.

What is your use case since you want the library to add its own module?

**Comment by cmelchior** [comment]
Closing due to no response. Please elaborate on your use case if you want us to consider this as right now there isn't a compelling use case that wouldn't complicate the API needlessly.
