### ISSUE TITLE
Encrypted Realm: Improve error message for invalid keys

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1355]
First time you try to open a Realm with an invalid key the message is:

`java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file`

Ideally it should be something like the below

`java.lang.IllegalArgumentException: Illegal Argument: Wrong key used to decrypt the Realm file.`

**Comment by beeender** [comment]
And maybe add a `checkEncryptionKey` method would support #1352 case better.

**Comment by emanuelez** [comment]
Unfortunately core has no way to know if the key is wrong or the realm file is corrupted. If somebody tries to open a JPG image it would still say they are using the wrong key. I think we should state both options. Also this makes it more of IllegalStateException since we don't really know if the problem is the argument (the key) or the Realm file

**Comment by cmelchior** [comment]
As the only way of telling the difference between a corrupted file and an encrypted one is doing statistical analysis on the bytes and looking for a uniform distribution, this seems impractical. 

We already documented in numerous places that a wrong encryption key will result in "Invalid RealmFile". I'll close this issue.
