### ISSUE TITLE
TimeoutException being thrown

### ISSUE THREAD

**Issue by lawloretienne** [realm/realm-java#1457]
Is https://github.com/realm/realm-java/issues/1390 still an issue in v0.82.2?

Also, I noticed the changelog references v0.83
https://github.com/realm/realm-java/blob/master/changelog.txt

Is that available yet?

**Comment by emanuelez** [comment]
It has been fixed and released in 0.82.2: https://github.com/realm/realm-java/blob/c731b69fd28e3f76da97d314990971f488ea6fc8/changelog.txt

The changelog file is correct since it represent what will be included in the next minor release. 0.82.2 was a patch release done on top of 0.82.1 where we cherry-picked only bug fixes in order not to introduce breaking changes.
