### ISSUE TITLE
Realm and transaction count

### ISSUE THREAD

**Issue by carmas123** [realm/realm-java#1506]
Hi, I need to know if Realm is in transaction or not...this method seems not supported by Realm for now (or not?)...however I want to create an helper for Realm class to implement this
```
public class RealmHelper extends Realm {
    private int tranCount = 0;

    @Override
    public void beginTransaction() {
        tranCount++;
        super.beginTransaction();
    }

    @Override
    public void commitTransaction() {
        super.commitTransaction();
        tranCount--;
    }

    @Override
    public void cancelTransaction() {
        super.cancelTransaction();
        tranCount--;
    }

    public int getTranCount() {
        return tranCount;
    }

    public boolean inTransaction() {
        return getTranCount() > 0;
    }
}
```
...but I cannot do this because the Realm class is declare as final and not inheritable...
can anyone help me please?

**Comment by cmelchior** [comment]
Hi @carmas123 
The feature you are looking for is really nested transactions. I have created the issue here for easy reference #1509. That feature unfortunately require changes to our underlying storage engine, so it won't help you right away.

Realm is final because it internally is is quite complex and it easy to create bugs if you start overriding its  methods. However you can use the Decorator pattern instead , see e.g http://stackoverflow.com/questions/4325699/can-intellij-automatically-create-a-decorator-class

**Comment by cmelchior** [comment]
@carmas123 
I assume the above answered your question, otherwise please reopen. Also note that we are about to merge `isInTransaction` which might also solve your use case: #1549
