### ISSUE TITLE
[Support] Official IRC/Slack channel?

### ISSUE THREAD

**Issue by StErMi** [realm/realm-java#1517]
Hi guys, do you offer an official IRC chat or Slack channel? It would be a good thing for us developers to talk with you but also talk with each others and try to solve problems.

**Comment by bmunkholm** [comment]
Hi,
We are experimenting with a Slack channel in Japan at the moment. But unless that's your language, it's likely not to much help :-)
We are considering this, but to be honest our biggest issue is setting false expectations. We try to do close to realtime support already in many channels (StackOverflow, github, and Google groups, twitter) - and that already takes quite a bit of our resources. Those channels are much better to track issues and ensure things get resolved, something IRC and Slack is really not designed for. So I don't think it will be a good channel for communicating with us as it sets realtime expectations which really is hard with a 24 hour worldwide audience - we will never get any sleep :-) But if we could establish the objective to connect users together, I think we could consider that. 
What so you think IRC or Slack would be better at that the established channels are not? Because they are certainly better at keeping conversations to a topic in one place, whereas IRC and Slack are horrible at that mixing all conversations together and therefore scales very poorly IMHO.

**Comment by StErMi** [comment]
At the moment I think that most of the developers are used to Slack, so it
could be a good option.
IRC is known everywhere but I think that slack is much more versatile and
has well done client for desktop/mobile.

On Fri, Oct 2, 2015 at 1:46 PM, Brian Munkholm <notifications@github.com>
wrote:

> Hi,
> We are experimenting with a Slack channel in Japan at the moment. But
> unless that's your language, it's likely not to much help :-)
> We are considering this, but to be honest our biggest issue is setting
> false expectations. We try to do close to realtime support already in many
> channels (StackOverflow, github, and Google groups, twitter) - and that
> already takes quite a bit of our resources. Those channels are much better
> to track issues and ensure things get resolved, something IRC and Slack is
> really not designed for. So I don't think it will be a good channel for
> communicating with us as it sets realtime expectations which really is hard
> with a 24 hour worldwide audience - we will never get any sleep :-) But if
> we could establish the objective to connect users together, I think we
> could consider that.
> What so you think IRC or Slack would be better at that the established
> channels are not? Because they are certainly better at keeping
> conversations to a topic in one place, whereas IRC and Slack are horrible
> at that mixing all conversations together and therefore scales very poorly
> IMHO.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-java/issues/1517#issuecomment-144996820>.
>



-- 

Founder e CEO di SurveyLab <https://surveylab.me/>

Skype: e.ricci.designfuture
Twitter: @StErMi <https://twitter.com/stermi>
Linkedin: https://www.linkedin.com/in/emanuelericci
Google+: https://plus.google.com/u/0/+EmanueleRicci/posts
Hangout: stermi@gmail.com

**Comment by bmunkholm** [comment]
We will evaluate the experiment with our current Slack channel in Japan before we will create one for the english speaking users.

**Comment by StErMi** [comment]
OK! We will wait ;)

On Mon, Oct 5, 2015 at 10:04 AM, Brian Munkholm <notifications@github.com>
wrote:

> We will evaluate the experiment with our current Slack channel in Japan
> before we will create one for the english speaking users.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-java/issues/1517#issuecomment-145457670>.
>



-- 

Founder e CEO di SurveyLab <https://surveylab.me/>

Skype: e.ricci.designfuture
Twitter: @StErMi <https://twitter.com/stermi>
Linkedin: https://www.linkedin.com/in/emanuelericci
Google+: https://plus.google.com/u/0/+EmanueleRicci/posts
Hangout: stermi@gmail.com

**Comment by bmunkholm** [comment]
And do use the other channels until then :-)

**Comment by AndreasBackx** [comment]
@bmunkholm, any update on this? I feel that this could perhaps relieve some pressure from the other means you mentioned. Developers could help each other out without needing the help of a Realm contributor. People could still be forwarded to Github or Stackoverflow if there is something other than a question being asked. Questions could be answered on IRC/Slack while they only saturate the other platforms.

**Comment by Zhuinden** [comment]
Well I didn't know you guys had a [slack](http://slack.realm.io/). :open_mouth:

**Comment by i-schuetz** [comment]
Any updates on this? The last time I checked in the slack channel (a few months ago) there were a 
lot of people speaking Japanese so it seems it's still rather regional.

**Comment by Zhuinden** [comment]
If you have Realm-java specific questions you can generally ask on Stack Overflow and people will answer, the Github issues also tend to have `T:HELP` so you also get answers here, and if you feel like it you can private message me on AndroidChat / Android United slacks
