### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected.

### ISSUE THREAD

**Issue by slidenerd** [realm/realm-java#1518]
Hi guys,

This is the second time I am facing this issue, 1st time was on some other app that uses realm where my base data model was a realmresults object, this time I am trying to recreate the issue and my adapter uses a realmlist to store data. Basically i load different json feeds based on a button called Refresh at the top, its a test application to expose this error, if you want I ll create a different adapter that uses RealmResults as the base data source, it still gives rise to this error.

https://github.com/slidenerd/RealmRecycler here is the project so that you can see for yourself, thanks for your time in advance.

![snap 2015-10-02 at 16 00 52](https://cloud.githubusercontent.com/assets/5139030/10244924/78cdb7d2-6920-11e5-8812-a15c6a96cd34.png)

I will also tell you where the error is, its right on that highlighted line
![snap 2015-10-02 at 16 16 37](https://cloud.githubusercontent.com/assets/5139030/10244980/fd5f686a-6920-11e5-9493-21399ed7d945.png)

a temporary fix would be to use notifyDataSetChanged() and that does not cause any crash but I lose the animations doing that, any suggestions. Some posts on stackoverflow report this issue saying they were scrolling while new data was being loaded etc. i am not even touching the recyclerview, i just hit refresh several times to load different data randomly
I even added a check to see if it is caused if I load more items than before or less items than before, here is an output that triggers it after loading a few feeds, i have the old size on the left and the new size on the right for each new load
![snap 2015-10-02 at 17 24 04](https://cloud.githubusercontent.com/assets/5139030/10245975/909a853e-692a-11e5-80e9-68804017b05c.png)

**Comment by cmelchior** [comment]
Hi @slidenerd. I cloned your project, but couldn't find a way to actually get it to run?

That said, I have a feeling this code is dangerous:

```
    public void setResults(RealmList<T> results) {
        mResults = results;
        notifyItemRangeChanged(0, results.size());
    }
```

You are most likely crashing because `newSize > oldSize`. In order to actually make a RecyclerView animate properly animate changes you will have to keep track of exactly what elements where added, removed or moved. This is currently quite hard using standard RealmResults as they are automatically updated so you don't have anything to compare them with.

We want to add that functionality but it require #989 to be implemented first. So for now you will have to make that diff yourself, most likely by copying your RealmResults into actual Java memory so you have something to diff with.

**Comment by slidenerd** [comment]
Hi @cmelchior  thanks for your advice :) that project on github runs when you press the refresh button at the top, inside the main activity, for now i can manage with notifyDataSetChanged :+1: however eagerly awaiting your next release to see what kind of improvements you guys are planning to add :)

**Comment by cmelchior** [comment]
I don't have any refresh button? At least not when just cloning and running the project. I have

- Navigation drawer with Import/Gallery/Slideshow/Tools etc.
- Settings dropdown
- A FAB with with a letter
