### ISSUE TITLE
RealmResults save data while rotation

### ISSUE THREAD

**Issue by slidenerd** [realm/realm-java#1526]
Hi, I tried searching this issue on your issue base and did not find anything relevant to the latest versions. How can I use Parceler and avoid requery RealmResults everytime after Activity or Fragment rotation :+1:  Thanks in advance for your answer

**Comment by dalinaum** [comment]
You can use [android:configChanges="orientation|keyboardHidden](http://developer.android.com/intl/ko/guide/topics/resources/runtime-changes.html#HandlingTheChange). But it preserve everything that include your activity's layout.

**Comment by zaki50** [comment]
Parceler does not work with RealmObject for now.
Parcelable support has been discussed discussed on #878

Current best solution is that saving primary key or some query parameters as instance state, and requery in new Activity.

I think Realm's query is fast enough in most cases.

**Comment by cmelchior** [comment]
Actually Realm does work with the library Parceler (See how here: https://realm.io/docs/java/latest/#parceler). 

However there are some things to be aware of if you want to use it to live along orientation changes. You can see more in this issue here: https://github.com/realm/realm-java/issues/1482

To summarise: Parceler doesn't actually do any work across orientation changes as the outstate never gets serialised. This means that if you close your Realm completely in onDestroy, any RealmObjects no longer work.

There exists 3 work-arounds for this:

1) Send a primary key, just like @zaki50 mentioned and requery. It will probably be fast enough.

2) Copy your object data into a standalone object. Until #1088 is implemented you will unfortunately have to do this yourself. 

3) Prevent Realm from being closed on orientation changes. Then you can save RealmObjects in outState and still have them available when the activity is recreated. Something like this:

```
    private boolean orientationChange = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (orientationChange == true) {
          realm = Realm.getDefaultInstance();
          orientationChange = false;
      }
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putParcelable("parcel", Parcels.wrap(Foo.class, foo));
        orientationChange = true;
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (!orientationChange) {
          realm.close(); // Remember to close Realm when done.
        }
    }

````

**Comment by zaki50** [comment]
@cmelchior https://realm.io/docs/java/latest/#parceler says that

    2) Once an object has been been parcelled, it becomes detached from Realm and at this point behaves like a standalone object containing a snapshot of the data.

Is your work-around 3) correct?

**Comment by cmelchior** [comment]
@zaki50 Yes, because the Parcel is never actually serialized on orientation changes, so you get the same object out as you put in. The Parceler library only kicks in if the Bundle is serialized, which e.g. happens if you put the Bundle in a Intent to start a new activity.

**Comment by zaki50** [comment]
@cmelchior Thank you! I got it. 

Another way to work with orientation change is to use NonConfigurationInstance.

```
    private Realm realm;
    private boolean realmRetained;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        ResultContainer container = (ResultContainer) getLastCustomNonConfigurationInstance();
        if (container == null) {
            realm = Realm.getDefaultInstance();
            results = ...;
        } else {
            realm = container.realm;
            results = container.results;
        }
    }

    @Override
    public Object onRetainCustomNonConfigurationInstance() {
        realmRetained = true;
        return new ResultContainer(realm, results);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        if (!realmRetained) {
            realm.close();
        }
    }

```

**Comment by slidenerd** [comment]
Thanks for sharing your insight @zaki50  @cmelchior and @dalinaum  , I wont be using android:configChanges so that leaves only copy to standalone object option, let me see what ll work , have a good day :)

**Comment by cmelchior** [comment]
No problem. I'll close this issue now. Feel free to reopen if you encounter further problems with this.
