### ISSUE TITLE
Any way to customize how realm overwrites values

### ISSUE THREAD

**Issue by slidenerd** [realm/realm-java#1540]
![snap 2015-10-07 at 12 48 21](https://cloud.githubusercontent.com/assets/5139030/10331286/bf47b2b0-6cf1-11e5-8e92-7fe4277b4230.png)

I have a table that looks like the one above in Realm browser
The Boolean column is something I manually update inside a RecyclerView with a checkbox, the values for the other columns are loaded from the JSON feed with a custom gson deserializer
![snap 2015-10-07 at 12 50 24](https://cloud.githubusercontent.com/assets/5139030/10331313/00840cf6-6cf2-11e5-8a39-19e7ba10ee6a.png)

my deserializer looks like this and if you notice, it doesnt update the value of the boolean column when it loads from the json feed, when i logout and login the app , the feed is loaded fresh using this deserializer and I lose my column corresponding to the boolean

I am using the copyToRealmOrUpdate with the id being the primary key, my database looks like this after I load fresh data which thanks to the deserializer writes false values in that column
![snap 2015-10-07 at 12 53 07](https://cloud.githubusercontent.com/assets/5139030/10331375/77d46bb6-6cf2-11e5-88e0-5920f8240e41.png)

One solution for me would be to mirror the table 2 times, 1 that stores stuff from json and the other one that mirrors the same data and has the boolean column in it, but is there some OPTIMAL way i can use realm to say that the last column must not be overridden and retain whatever it already has?

Thanks for your answer in advance

**Comment by cmelchior** [comment]
Hi  @slidenerd 

I don't have 1 single solution for this, as it depends on how the rest of the app works, but I have some ideas:

1) All our `createOrUpdateFromJson*` methods actually does exactly what you want as these methods will skip updating any fields that are not present. So if you instead of converting to a standalone object, just modify your JSON to match that would probably be easier.

2) Inside your GsonDeserializer you can open a Realm and query for your object and set the proper `isMonitored` boolean as you have a primary key to query for. 

Neither of these approaches require you to mirror tables, but will allow you to use your existing model.

**Comment by slidenerd** [comment]
Thanks for the time @cmelchior :)
