### ISSUE TITLE
Add `Realm.delete(RealmList)` and `Realm.delete(RealmResults) to remove RealmObjects

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#1560]
Cocoa binding has the similar functions
See https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm6deleteuRq_Ss12SequenceTypedqqq_S1_9GeneratorSs13GeneratorType7ElementCS_6Object_FS0_Fq_T_

Currently, All objects in `RealmResults` can be deleted by `RealmResults.clear()`
But there is no function to delete all objects from `RealmList`

**Comment by cmelchior** [comment]
We probably need to consider our whole API in this area, as right now it isn't as clear as one could hope IMO. I think the original idea was to stick as close to the Java Collection API methods as possible, which makes a lot of sense. However,  how they work differ based on the type, which makes the API harder to understand:

```
realm.clear(clazz); // Deletes all objects of a given type from the Realm

realmResults.clear(); // Deletes all query results from the Realm
realmResults.remove(int location); // Removes item from Realm, returns null
realmResults.removeLast(); Removes last item from Realm
// Why no removeFirst?

realmList.clear(); // Removes items from the List, but not Realm
realmList.remove(int location); // Removes items from the List, but not Realm. Returns item
// Why no removeLast/First?

realmObject.removeFromRealm(); // Removes the object from Realm. isValid() now returns false.
```

Maybe it would make more sense to use the RealmList semantics everywhere? That would be more inline with Java semantics, would allow people to manipulate the results outside a write transaction, and would allow people to up-cast RealmResults to List without problems. 

Given that you need a write-transaction anyway to actually delete the Realm data. Adding special methods for removing would probably be cleaner?

```
realm.removeFromRealm(obj)
realm.removeFromRealm(collection);

realmResults.removeLastFromRealm()
realmResults.removeFromRealm(int location)
realmResults.removeAllFromRealm();

realmList.removeFromRealm(int location)
realmList.removeAllFromRealm();
````

Objective C uses `delete*` instead of `remove*`. Something worth considering if we moved away from the collection API methods anyway.

What do you think?

**Comment by beeender** [comment]
The problem of `allow people to manipulate the results outside a write transaction` is, it has the same problem with the concept `detach` we discussed a lot before.

If we allow user to manipulate the `RealmList` as a normal `List` without changing anything in the Realm, that means, the `RealmList` should be detach from Realm first.

I think Cocoa's approach makes sense. It only has `List.removeAll()` which is the same with `RealmList.clear()`, but no `Results.clear()`.

Maybe we should consider to move this functionality to `Realm`, since the `createObject` function is in `Realm`.

**Comment by cmelchior** [comment]
Could point about consistency. It would be impossible to auto-refresh a collection you manipulated in pure memory.

I think my main concern is that we currently have different words for the same functionality: `remove`, `clear`, `delete`. Choosing one and use it consistently would help a lot. Up until now we have been using `clear()` because it is in the collection API, but on `RealmList`, `clear()` has a different meaning :(

**Comment by beeender** [comment]
we might should just deprecate the `RealmResults.clear()` and force user to use 'Realm.removeFromRealm(RealmResults)` to make the API look better, at least more consistency.

**Comment by cmelchior** [comment]
`clear()` is part of the Collection API, so would be really annoying though :(

**Comment by beeender** [comment]
yes, but we can throw a stub exception to ask user to use another one. But it really sucks that no `RealmResults.clear()` :( At least for me, instinct tells me should use `RealmResults.clear()` to do deletion.

**Comment by cmelchior** [comment]
Same here. I guess the `easiest` solution. Would be to just add:  

```
realm.remove(obj)
realm.remove(collection)
```

to the Realm class. It would mimic ObjC and `remove` fits the wording in RealmObject and the collection API (even though Objective-C uses `delete`).

It would still mean that `clear` behaves differently on RealmList/RealmResults though, but at least we are not introducing overlapping concepts to `RealmList`.

**Comment by dalinaum** [comment]
`realm.remove(obj)` and `realm.remove(collection)` looks good to me.

**Comment by cmelchior** [comment]
Swift also have `deleteAllObjects()`. We should probably adopt that as well

**Comment by meierjan** [comment]
Why is this closed? There is no `deleteAllObjects()`, is it?

**Comment by cmelchior** [comment]
@meierjan In 0.88 there is a new  `Realm.deleteAll()` method

**Comment by meierjan** [comment]
@cmelchior I really love how fast you reply <3. Sorry, my bad.

**Comment by nicks258** [comment]
@cmelchior how to use `Realm.deleteAll() `method.How to define in this mehod.

**Comment by nicks258** [comment]
it says cannot resolve method 'deleteAll()' when i am using `Realm.deleteAll()`
