### ISSUE TITLE
How to return List with Realm

### ISSUE THREAD

**Issue by marcforn** [realm/realm-java#1579]
I have the following static method to retrieve all the users from DDBB:

     public static List<User> getAllUsers(Context context){
        Realm realm = Realm.getDefaultInstance();

        List<User> userList = realm.where(User.class).findAll();

        realm.close();

        return userList;
    }`

but If I close the realm instance I loose the data rerieved from de DDBB. 

How could I return a List of users and closing the realm on same method?

Thanks in advance

**Comment by Zhuinden** [comment]
You would need to copy the realm objects to POJOs that are not Realm Objects, so that your objects would not be associated with a Realm.

Then again, the better way to do it would be to have an open realm that was opened in the Activity `onCreate()`, and use the realm objects from the `RealmResults<T>` directly. And close it only in `onDestroy()`.

**Comment by marcforn** [comment]
Ok, I just want to change the SQLite requests for the Realm ones without having to make big changes on the code.

I will study to migrate all the adapters to RealmAdapters.

Thanks for the information

**Comment by zaki50** [comment]
@marcforn please reopen this issue if you have further questions.

**Comment by marcforn** [comment]
OK, thanks for support.
