### ISSUE TITLE
Be consistent with change listeners and weak referencing

### ISSUE THREAD

**Issue by Wattos** [realm/realm-java#1675]
According to the documentation:

*"Since 0.80.3, the RealmChangeListener is managed as a weak reference internally to avoid potential leaks. So DO NOT use anonymous RealmChangeListener when calling addListener. Instead, always maintain the reference to your listeners until you don’t need them anymore."*

This is not the case for the new API introduced in 0.84 (result.addChangeListener). addChangeListener for realmObject and realmresults are strong references:

*"Remember to unregister any listeners when exiting an Activity or Fragment to avoid memory leaks."*

I would personally prefer not to use weak references as that:
   * Creates warnings in the ide (Field can be local variable)
   * Disables the use of lambda expressions once these are available

In my opinion, it is best to return a Closeable (or destroyable) object which encapsulates all required context information to deallocate the resource. E.g.

```
List<Destroyable> destroyables = new List<>();
destroyables.add(realm.addChangeListener(...))
```
Then I can do

```
for (d in destroyables) {
   d.destroy();
}
```
then I can loop over all of them to destroy them. In either case, it would be nice if both

**Comment by beeender** [comment]
We have a interface consistency problem.

1. `Realm`'s listener will be called whenever the Realm is updated.
2. `RealmResults`'s listener will be called only when the async query finished.
3. User has to hold a strong reference of Realm's listener in case of remove it to avoid memory leaks. (the `RealmBaseAdapter` case.)
4. No strong reference needed for `RealmResults`'s listener since it has the same life cycle of the `RealmResults`.

@realm/java

**Comment by beeender** [comment]
And #1676 would be the same problem as well.

**Comment by nhachicha** [comment]
Hi @Wattos 
All listeners should be strong references, historically we changed `Realm.addChangeListener` to be Weak because `RealmBaseAdapter` had no appropriate callback that helps notify the according Adapter/Activity is no longer used and we need to remove it's listener. Having a Weak listener will not keep the listener (and any enclosing reference) forever.

We're going to refactor this such as:
1. Exposed listeners (public API) should all be strong. Indeed the user is responsible of removing them, the user also knows when it's best to remove the listener (reacting to a callback/event)
2.  We'll introduce Weak listeners for internal use only (like the use case of `RealmBaseAdapter`)

```java
realm.addChangeListener(listener); //keep a strong reference to listener
realm.removeChangeListener(listener); // to remove a non-anonymous listener
realm.removeAllChangeListeners(); // to remove all listeners (including anonymous one)

realm.addWeakChangeListener(listener); // add a WeakReference listener (this is package-private)
```
Hope this will make the API more consistent.
Cheers
