### ISSUE TITLE
realm file incompatible if model has PrimaryKey

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#1703]
from slack.

Realm Swift reports an error when opening the realm file generated on Android.

model definition in Java:

```
public class DataItem extends RealmObject {
    @PrimaryKey
    private int id;

    // seter and getter here
}
```

model definition in Swift:

```
class DataItem: Object {
    dynamic var id = 0

    override static func primaryKey() -> String? {
        return "id"
    }
}
```

reported error:

```
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=0 "Migration is required for object type 'DataItem' due to the following errors:
- Property 'id' has been made a primary key." UserInfo={NSLocalizedDescription=Migration is required for object type 'DataItem' due to the following errors:
- Property 'id' has been made a primary key.}: file /Library/Caches/com.apple.xbs/Sources/swiftlang_PONDEROSA/swiftlang_PONDEROSA-700.1.101.6/src/swift/stdlib/public/core/ErrorType.swift, line 50
```

**Comment by kishikawakatsumi** [comment]
I confirmed that error occurred in the following combination:
- Java 0.82.2/ObjC 0.95.3
- Java 0.84.1/ObjC 0.96.2

**Comment by zaki50** [comment]
`Realm Java` and `Realm Swift` uses different table name in `pk` table.

![pk_table_of_android](https://cloud.githubusercontent.com/assets/406660/10844465/2d20b242-7f43-11e5-9f55-f4fb5753e9da.png)

![pk_table_of_ios](https://cloud.githubusercontent.com/assets/406660/10844467/30fb1fd8-7f43-11e5-8a1e-ae808657fcbf.png)

**Comment by zaki50** [comment]
moved to realm/realm-cocoa#2770

**Comment by cmelchior** [comment]
Confirmed to be a problem with Java.

**Comment by zaki50** [comment]
I pushed a code of android app which I used for investigation.

https://github.com/zaki50/realm_file_viewer_by_stetho

**Comment by kurteous** [comment]
Christian, this fix appears to have broken the migration process from older versions of Java Realm to 0.84.2. My situation is that I have a published app that uses 0.80.1. I have since updated Realm to 0.84.2 in development. I can replicate my problem by installing the Play Store version of my app, starting it up to create some objects in Realm (0.80.1), then installing my development version (0.84.2) over the Play Store version, which triggers a migration. The migration works perfectly from 0.80.1 to 0.84.1, but when I try the exact same migration from 0.80.1 to 0.84.2, using the same process, I get this error upon app startup:

java.lang.RuntimeException: Unable to create application org.myorg.Application: io.realm.exceptions.RealmMigrationNeededException: Primary key not defined for field 'objectID' in existing Realm file. Add @PrimaryKey.

The table in question has always had 'objectID' as its primary key, with the @PrimaryKey annotation, and the migration doesn't attempt to modify that column. It does, however, change some other columns in that table (adding columns, changing some to nullable).

**Comment by cmelchior** [comment]
@kurteous I just tried to test an upgrade from 0.84.1 to 0.84.2 with a Primary Key and it seemed to work fine. Can you post your migration code + model class?

**Comment by skyisle** [comment]
I met same exception with @kurteous. In this situation, my pk table looks like corrupted. 
![image](https://cloud.githubusercontent.com/assets/71561/11318844/2c071562-90a6-11e5-9828-9db4e2a54630.png)

@cmelchior, do you have any idea?

**Comment by skyisle** [comment]
As you can expected, Fclass should be Friend and Acquainclass should be Acquaintance.

**Comment by skyisle** [comment]
#1775 is related to this

**Comment by cmelchior** [comment]
Hi @skyisle 
Thanks, we actually managed to reproduce this issue yesterday, but are still looking for a root cause. So any information about your setup would be helpful. Are you opening the Realm from multiple threads at the same time?

**Comment by skyisle** [comment]
@cmelchior Nothing special configuration with single thread environment.  I did some experimenting with this, so I made a sample project to reproduce this issue easily. https://github.com/skyisle/realm-migration-bug

**Comment by beeender** [comment]
@skyisle #1816 fixed this issue. Thanks for reporting!
