### ISSUE TITLE
Query for POIs in LatLngBounds

### ISSUE THREAD

**Issue by dadino** [realm/realm-java#1765]
I'm trying to query my POIs, using `GoogleMap.getProjection().getVisibleRegion().latLngBounds`, which returns a [LatLngBounds](https://developers.google.com/android/reference/com/google/android/gms/maps/model/LatLngBounds). In my `POI`s I have a child object that contain `lat` and `lng` of the `POI` (poi.position.coordinates.lat/lng).
I tried using `between()`, but [this](https://github.com/realm/realm-java/pull/1284) removed it for link queries.

    query.between("poi.position.coordinates.lat", bounds.northeast.latitude, bounds.southwest.latitude)
		 .between("poi.position.coordinates.lng", bounds.northeast.longitude, bounds.southwest.longitude);

How should I query `Realm` to get those `POI`s?

Bonus question: do you have plans for an official `RealmCoordinate`? (with specific query operators, like `range()` or `distance()`)

**Comment by kneth** [comment]
It is true that we have remove `between()` for querying relationships as our underlaying storage/query engine doesn't support it directly. The best option currently is to add a primary key `poi` and use it as a foreign key in `coordinates` and then query first `coordinates` and then use the keys to query `poi` to get objects. Of course, it gives you a number of queries and loops instead of the simple query as you outline.

**Comment by dadino** [comment]
I'm trying with a `.greaterThanOrEqual().lessThanOrEqual()` approach for both `Latitude` and `Longitute`, but I'm not sure if it is safe to assume that all 4 conditions will be true in all the returned `POI`s. I mean, it should, but reading #1237 I'm a bit confused.

**Comment by kneth** [comment]
I fully understand your confusion, and the documentation could be clearer. Querying linked objects turn out to be existential qualifiers and plain queries are not.

Let me give an example. Consider to model classes `Foo` and `Bar`. `Foo` has a field `bar` which is a `RealmList<Bar>` while `Bar` has a numeric field `x`. The data is:

    Bar[0].x = 5
    Bar[1].x = 3
    Bar[2].x = 6
    Bar[3].x = 2
    Foo[0].bar = {1, 2}
    Foo[1].bar = {3, 4}

The query `where(Bar).between("x", 3, 5)` will return two objects: `Bar[0]` and `Bar[1]` (linked to by `Foo[0]`). You will get the same result with the query `where(Bar).greaterThanOrEqual("x", 3).lessThanOrEqual("x", 5)`. 

Now consider the query `where(Foo).greaterThanOrEqual("bar.x", 3)`. The result is two objects: `Foo[0]` and `Foo[1]` since both objects are linked to at least one `Bar` object that fulfil the condition (`Bar[0]` and `Bar[1]` for `Foo[0]` + `Bar[2]` for `Foo[1]`).

Let us now expand the query to `where(Foo).greaterThanOrEqual("bar.x", 3).lessThanOrEqual("bar.x", 5)`. It will also return the two `Foo` objects. The first condition is same as before, while the second condition is fulfil for `Foo[0]` (`Bar[0]`, `Bar[1]`) and `Foo[1]` (`Bar[3]`). Combined, the two objects `Foo[0]` and `Foo[1]` is returned.

As you can see, querying `Bar` is better, and until #607 is implemented, using a unique id (primary key) is the best way to get the `Foo` objects.

**Comment by dadino** [comment]
Thank you.
I guess the answer to the bonus question is no, right?

**Comment by kneth** [comment]
No, we don't have a time frame for supporting coordinates. It does come up on a regular basic, and you're welcome to create an issue for it (I'll label it "enhancement").

**Comment by cmelchior** [comment]
Closing this as #1772 now contains the actual feature request.
