### ISSUE TITLE
Small issue in Readme: Wrong url for SNAPSHOT releases

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1881]
Ahoy! The URL for SNAPSHOT releases in the readme file is stale. It points to:

    classpath "io.realm:gradle-plugin:<version>-SNAPSHOT"

But the actual URL is:

    classpath "io.realm:realm-android:<version>-SNAPSHOT"

**Comment by mshusek** [comment]
+1 for save me a hour of unpleasant surprise

**Comment by cmelchior** [comment]
Actually we are slowly moving to a new way of deploying Realm which is through a Gradle plugin. The reason for this is that we need to introduce bytecode manipulation to support completely custom methods  and fields, so the documentation is accurate albeit missing in detail.

You can see how it is used in our example projects here: https://github.com/realm/realm-java/blob/master/examples/build.gradle and here https://github.com/realm/realm-java/blob/master/examples/introExample/build.gradle

That said, there is actually an error in the description as it should be `realm-gradle-plugin` instead of `gradle-plugin`. I'll update the documentation

**Comment by kneth** [comment]
@cmelchior Please see #1889

**Comment by Saketme** [comment]
@cmelchior Oh boy yes! Been waiting for that feature since ages!

**Comment by Saketme** [comment]
Noob question, is there a difference between these two Realms:

    io.realm:realm-gradle-plugin:<version>-SNAPSHOT

    io.realm:realm-android:<version>-SNAPSHOT

**Comment by cmelchior** [comment]
Yes, the first is our Gradle plugin which requires the setup I mentioned.
The later is our "FatJar" that doesn't depend on the Gradle plugin, but cannot do bytecode manipulation when we introduce it. This is what people are currently using.

For now they are functional equivalent (but require slightly different setup in the `build.gradle` files)

**Comment by Saketme** [comment]
Got it!
