### ISSUE TITLE
Checking type with DynamicRealm's RealmSchema

### ISSUE THREAD

**Issue by NikoYuwono** [realm/realm-java#1883]
Hello, 

Previously I'm using Table to check the type of the column now I'm trying to migrate to DynamicRealm because [direct access to Table will be deprecated soon.](https://github.com/realm/realm-java/issues/1876)

I think I can get the name of the field with using 

```
RealmObjectSchema realmObjectSchema = dynamicRealm.getSchema().get(selectedTableName);
Set<String> fieldNames = realmObjectSchema.getFieldNames();
```

But how to get the field types?

Thank you!

**Comment by beeender** [comment]
Uh... I think that API is missing and we should add it ...
@cmelchior

**Comment by NikoYuwono** [comment]
Thank you! will wait for the implementation before migrating to DynamicRealm then!

**Comment by cmelchior** [comment]
Hi @NikoYuwono 
Can you elaborate on your use case when using `RealmObjectSchema`? Because ideally you shouldn't need to query the schema for the type. It is information you should already know. 

I believe we left it out intentionally in `RealmObjectSchema` because we are only able to expose the underlying Realm data type and not the type used in your Java RealmObject class, e.g `short`, `int` and `long` would all be of the type `RealmFieldType.INTEGER`, and there was concern that might be confusing.

Note that the information is available in `DynamicRealmObject` where you can do `obj.getFieldType("fieldName").`

I am not totally against adding it to `RealmObjectSchema`, but knowing your use case will help a lot.

**Comment by beeender** [comment]
One use case is for a phone-side Realm browser. Showing data without knowing the schema during the compiling time.

**Comment by cmelchior** [comment]
But the schema is only meta-data? To show any information in a browser you would use `DynamicRealmObject`?

**Comment by beeender** [comment]
You need to know meta data before deciding to call `DynamicObject.getInt()` or `DynamicObject.getString()`. Right?

**Comment by NikoYuwono** [comment]
Hi @cmelchior  currently I'm trying to create a phone-side Realm browser like @beeender said. I want to use Reflection as little as possible that's why I'm trying to access the Field type so I can get the data from DynamicRealmObject.

From what I understand I can only get the data with 
```
String name = person.getString("name");
```

but if I don't know what's the type of the field how can I determine which function should I call?
Before I'm using switch-case on ColumnType but looks like it become deprecated in 0.86.0

**Comment by cmelchior** [comment]
You can also do `person.get("name")`, which would probably be enough for all simple types, but I agree that if you want to make a browser that shows RealmLists and RealmObject references in another way it can be a bit problematic.

I'll add it.

**Comment by NikoYuwono** [comment]
Yes that's what I thought with doing the type checking by myself. Will try that one too though while waiting for the new release. 
Thanks @cmelchior and @beeender will wait for the next release!

**Comment by Saketme** [comment]
@NikoYuwono Really need a phone-side Realm browser :)

**Comment by NikoYuwono** [comment]
@Saketme will try to release initial version next Tuesday!
