### ISSUE TITLE
Mechanism of copyToRealmOrUpdate

### ISSUE THREAD

**Issue by csnu17** [realm/realm-java#1935]
Should I need to check value of the input model with Realm model before execute the method? I don't want to update the model in Realm if all value in each fields are also same previous. I think it's waste of the process. Thank you.

**Comment by cmelchior** [comment]
I guess it depends on how often you think the values change, because if you check first and then insert, you are doing double the work (it also require substantial more code from you). Since this method is mostly used after executing a network request, the overhead in calling `copyToRealmOrUpdate` is tiny, so I would probably not bother optimizing it.

**Comment by csnu17** [comment]
OK, maybe in the next version of realm-java also include the checking mechanism before insert or update. Thank you for your help.
