### ISSUE TITLE
Multi level jsonarray as RealmList inside model

### ISSUE THREAD

**Issue by mich4s** [realm/realm-java#1951]
I have problem with JsonArray with objects like that : {"id":"4","name":"Test","nameN":"Test","priority":"6","image":"imagehttp","categories":[{"id":"1","name":"Restauracje "},{"id":"2","name":"Kawiarnie "},{"id":"4","name":"Moda"},{"id":"5","name":"Rozrywka"}]}

My model looks like that:
@PrimaryKey
    private int id;
    private String name;
    private String image;
    private String priority;
    private RealmList<Category> categories;

And i put this that way:

JSONArray citiesJson = response.getJSONArray("cities");
//begintransaction...
realm.clear(City.class);
realm.createAllFromJson(City.class, citiesJson);

All code is ok, because whole app is working. I just can't find any way, to put 2'nd dimension array as List into model.

Can you help me? There is quite hard to find anything about realm in web ;/

**Comment by cmelchior** [comment]
Your RealmList has to have some type e.g. `RealmList<Category>`  and `Category` has to match the fields inside `{"id":"1","name":"Restauracje "}`

but otherwise doing 

```
realm.beginTransaction();
realm.createAllFromJson(Model.class, json);
realm.commitTransaction();
```
Should work. As it will automatically detect the Json list inside. You don't have to do that manually.

This code here:
```
JSONArray citiesJson = response.getJSONArray("cities");
//begintransaction...
realm.clear(City.class);
realm.createAllFromJson(City.class, citiesJson);
```

Will only work if your JSON is an array, which judging from the code you pasted it is not. It looks like an object with a field that is an array.

**Comment by mich4s** [comment]
So there is no way to make this with object? Json is received from web api, and i can't change the way, it works ;/

**Comment by beeender** [comment]
@mich4s I guess the above comment fixed your issue? I am closing this now. Feel free to reopen this issue if necessary. Thanks a lot for you feedback!
