### ISSUE TITLE
Orphaned child objects

### ISSUE THREAD

**Issue by ihajat** [realm/realm-java#1995]
Hi,

Goals: If I use an object that has a primary key, so that, we can update it. This object has a child object that doesn't have a primary key. I want to update the child object if the parent object is updated.
Expected results: If the parent is updated, the child object is also updated.
Actual results: If the parent is updated, the child object is orphaned ( it will insert a new child object each time the parent object is updated, so , if I update the parent 10 times, I will have 10 child objects, but only the last will be linked to the parent object).
Steps to reproduce: I would think, any code will be able to reproduce it. I will email you whole project.
Version of Realm (0.87.0) / Android Studio (1.5) / OS ( Mac 10.10.5)

kind regards

**Comment by beeender** [comment]
Hi,

This is the expected behaviour. If there is no primary key, there is no way for Realm to know two objects are intended to be the same Object or not. And it would be the same for the parent object or the Child object.

So the suggestion will be adding a primary key to the child object as well.

You can imagine when Realm wants to update the child, how could it know if the object should be updated or created.

**Comment by ihajat** [comment]
Hi,
OK, here's the challenge. I will present to you a very simple piece of json data. Can Realm model it? If it can how? So, we have, for example, dads. Each dad object has a name, and a list of children. 
{
    “dads": [
{“name”:"fred”,"children":[{"id":"1”,"name”:"john”,"sex”:"male"},{"id":"2”,"name”:"Jane”,"sex”:"female"}]},
{“name”:”gary”,"children":[{"id":"1”,"name”:”jack”,"sex”:"male"},{"id":"2”,"name”:”kerry”,"sex”:"female"}]}
]
}

kind regards

**Comment by beeender** [comment]
Child also has a primay key `id` in your example. No?

**Comment by ihajat** [comment]
Hi,

Unfortunately, I can't change the json. So, whilst, dad has a unique Id, children Ids aren't unique. Maybe, autoincrement, but Realm doesn't support it, I don't think. Also, I'm using , realm.createOrUpdateAllFromJson(WorkOrder.class, obj.getJSONArray("dads"));, 
so, what can I do? Any suggestions please.

**Comment by beeender** [comment]
In this uncommon cause i think you can:
Parse the JSON to find the Dad's id, query Realm find the Dad object, clear the children field or just delete the Dad object. Then import it to Realm as before

**Comment by ihajat** [comment]
Sorry, I'm not sure what you mean? Is there some json library? maybe gson? or do you mean, good old fashion string manipulation? Change the json string, so that I change the child Ids to unique Ids?  But, then how would updates to children work? Maybe provide some code please.

**Comment by beeender** [comment]
If you have to update the Child (you might have some local changes make it different from the remote), then i think it is better to parse and update it manually in your case which is not common:

Realm is using GSON to deal with JSON now. And you might want to use the same

Here is the GSON document https://github.com/google/gson/blob/master/UserGuide.md

Parse the Child in the JSON and update the Dad's child field by setters like:
```
Dad dad = realm.where(Dad.class).equalTo("id", 1000); // 1000 is parsed from JSON
Child child1 = dad.getChildList().get(index);
child1.setName(name) // Name parsed from JSON
```

As i said before, the challenge here is to figure out which child is the one you want to updated because you don't have a primary key for it. And to my point of view, that is wrong. it is something you need to make changes in the server side.

**Comment by ihajat** [comment]
Hi,

On reflection:
1. In my humble opinion, since Realm isn't built on top of sqlite, It doesn't need foreign keys to work. So, on the same principle, it would know whether to update or insert;irrespective of a primary key. Maybe have it as an option as an annotation?
2. I got it to work using a hack, without too much intrusiveness. I added a foreign key which is populated using Realm's ability to get its child objects. It then deletes using the old fashion foreign key select, instead of Realm's functionality. 

kind regards

**Comment by beeender** [comment]
Hi,

This is not about the foreign key at all, let me put an example here:

A dad has a son named "John" and we stored in the Realm.
Then server sent some new data that the same Dad now still has one child and same name "John" but it is a daughter.

Then it could be:
1. The "son" had a transsexual operation, and in this case, we should change the original object instead of creating a new one.
2. The son has been died, so it has been removed from the Dad's children list. Later the Dad has a new daughter and The Dad decide to give her the same name "John" for remembering her old brother. And in this case, the old Child object should be created.

I hope i explained my point well.
