### ISSUE TITLE
Too much object allocation on Main Thread when updating DB from background thread

### ISSUE THREAD

**Issue by creativepsyco** [realm/realm-java#2039]
Don't know if this is the intended use case or a problem with my code. But I noticed that every time I do a background update of the DB, it seems to print a lot of Garbage Collection calls. On closer examination, 1/3 of the objects were allocated by Realm. I suppose this is caused by cross-thread notification of change. Is this fine? Or should I investigate further?

![image](https://cloud.githubusercontent.com/assets/547235/12166721/d9f4cf9e-b562-11e5-8043-02bf4b816046.png)

**Comment by cmelchior** [comment]
Yes, we use an iterator method in that class, which iterate over all live RealmObjects.
I could imagine this could result in quite a lot of objects being allocated in some cases. So it is intentional, although not desirable and it looks like something we would want to optimize further.

For easy reference, the offending method is this one: https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/HandlerController.java#L251-Lundefined

**Comment by beeender** [comment]
@cmelchior  I think what @creativepsyco  noticed is related with #2029

**Comment by creativepsyco** [comment]
@beeender Yes indeed it looks quite similar. Shall we close this, I suppose you probably have a raodmap for the performance issues.

**Comment by beeender** [comment]
Yes! then i just close this one. Thanks a lot!
