### ISSUE TITLE
0.88-snapshot-2016-01-13: "does support null values" for a primitive "int" field?

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#2104]
dStatus is an "indexed" "integer" field. We are migration from 0.84.2 realm lib to realm-android-0.88.0-20160113.060756-31 snapshot and got the following crash from one of our users. 

```java
Non-fatal Exception: io.realm.exceptions.RealmMigrationNeededException: Field 'dStatus' does support null values in the existing Realm file. Use corresponding boxed type for field 'dStatus' or migrate using io.realm.internal.Table.convertColumnToNotNullable().
       at io.realm.MyRealmProxy.validateTable(MyRealmProxy.java:1146)
       at io.realm.MyRealmMediator.validateTable(MyRealmMediator.java:47)
       at io.realm.Realm.initializeRealm(Realm.java:297)
       at io.realm.Realm.createAndValidate(Realm.java:265)
       at io.realm.Realm.createInstance(Realm.java:244)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
       at io.realm.Realm.getInstance(Realm.java:200)
```

**Comment by diegomontoya** [comment]
We have another captured crash with exact same type of message but for a different realm db/table. There was no migration involved in the second table crash. The previous "dStatus" table went through a migration. So now we have two tables, 1 with migration 1 without migration,  with similar crashes both on a "int" field that complains about it is a nullable fields and requires migration. 

Both "int" fields happens to the the last column in each table if that is relevant.

**Comment by diegomontoya** [comment]
We have another captured crash with exact same type of message but for a different realm db/table. Both tables in this and previous comment went through migration adding an int field.

Both "int" fields happens to the the last column in each table if that is relevant.

**Comment by cmelchior** [comment]
Can you post your migration code + the RealmClass in question?

**Comment by laaptu** [comment]
Hey guys, any solution to this. This issue persists on `indexed` annotated field.

**Comment by cmelchior** [comment]
Hi @laaptu Can you create a new issue, with your model class and migration code? It will be easier to take the discussion there.

**Comment by laaptu** [comment]
@cmelchior  : I found why this issue comes. It was my own mistake. The issue comes in following manner. Say we add a new `RealmObject` as
```java
  public class BankLocation extends RealmObject {
    @Index
    private int locationId;
    private String locationName;
    //getters and setters
}
```
 And in our `RealmMigration`, we add the following
```java
private static RealmMigration dbMigration = new RealmMigration() {
        @Override
        public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
            RealmSchema realmSchema = realm.getSchema();
            if (oldVersion == 1) {
                realmSchema.create("BankLocation")
                        //.addField("locationId", Integer.class)
                        //instead of above we need to add 
                        .addField("locationId", Integer.class, FieldAttribute.INDEXED)
                        .addField("locationName", String.class);
            }
        }
    };
```
So, in `RealmMigration`, if `@Index` attribute is not mentioned while adding field, the error comes. So, it is all in my implementation the mistake arises. Thanks again for awesome library.

**Comment by laaptu** [comment]
@cmelchior  This isn't the issue in the library, it is the issue on my own implementation. This issue comes when the migration definition of added field doesn't match with what is defined on the `RealmObject` extended class property definition. I will illustrate with following  example, so that it will be easier for any others facing this type of error.

##### Example 1
```java
public class UserBank extends RealmObject {
    private int bankId;
    //getters n setters
 }
```
Now let us add a new  field to this `RealmObject`
```java
public class UserBank extends RealmObject {
    private int bankId;
    private int locationId;
    //getters n setters
 }
```
Now we need to update the `RealmMigration` in following manner
```java
private static RealmMigration dbMigration = new RealmMigration() {
        @Override
        public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
            RealmSchema realmSchema = realm.getSchema();
            if (oldVersion == 1) {
                RealmObjectSchema userBankSchema = realmSchema.get("UserBank");
                //if we add field in following manner i.e. specifying Integer.class instead of int.class
                //the above error comes
                //userBankSchema.addField("locationId", Integer.class);
                //instead we need to add in following manner
                userBankSchema.addField("locationId", int.class);
            }
        }
    };
```

##### Example 2
Though it is not related to this, but while doing migration need to reflect annotation of newly added property
```java
public class UserBank extends RealmObject {
    private int bankId;
    private int locationId;
    @Index
    private int userId;
    //getters n setters
 }
```
And in migration
```java
 private static RealmMigration dbMigration = new RealmMigration() {
        @Override
        public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
            RealmSchema realmSchema = realm.getSchema();
            if (oldVersion == 2) {
                RealmObjectSchema userBankSchema = realmSchema.get("UserBank");
                userBankSchema.addField("userId", int.class, FieldAttribute.INDEXED);
            }
        }
    };
```
BTW need to check the `migrationExample` bundled in the github repo which clearly explains all the proper way of migration.
Thanks :+1:  a million for this awesome library.
