### ISSUE TITLE
Exceptions during async transactions are failing silently

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#2130]
So I've ran into a very frustrating error. Exceptions during asynchronous transactions aren't getting reported. No signs of stacktrace. 

This made me spend a couple of hours trying to figure out why my logic isn't working only to realize that Realm has stopped printing Error stacktraces.

##### Steps to reproduce
Simply throw an `Error` inside a transaction.

##### Example code

````java
private void testRealm() {

    final Realm.Transaction.Callback callback = new Realm.Transaction.Callback() {

        @Override
        public void onSuccess() {
            super.onSuccess();
        }

        @Override
        public void onError(Exception e) {
            super.onError(e);
            e.printStackTrace();
        }

    };

    getRealm().executeTransaction(realm -> {
        throw new IllegalAccessError("Poop");
    }, callback);

}
````
The stacktrace never gets printed.

**Realm version**: 0.87.2

Any ideas how do i fix this?

**Comment by cmelchior** [comment]
Hi @Saketme 

`IllegalAccessError` is an `Error` which we don't handler pr. the specification as they are not recoverable: https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html

However it looks like the Error that are thrown are being caught by our ThreadPoolExecutor instead of crashing as intended. We will look into fixing it. In the meantime, you can work around it by converting any Error to a RuntimeException, although you should not just ignore that exception, but crash instead as pr. the Error specs.

Related is also #1657

**Comment by Saketme** [comment]
Ah. I regularly use such `Errors` across my code as more of a debugging tool. It helps me find mistakes in my code flow.

I will replace them all with `RuntimeExceptions`.

Also, please document this behavior both in the `Callback#onError()` and the [docs](https://realm.io/docs/java/latest/#asynchronous-transactions).
