### ISSUE TITLE
Update `asObservable` JavaDoc to mention that they keep emitting and never call onComplete

### ISSUE THREAD

**Issue by rfrost77** [realm/realm-java#2135]
I request only once to my method that uses realm query with asObservable.
(I saw Log for sure that I requested really once, and it's true.)

But subscribe event from the query which is observable came multiple, twice sometimes triple.

Besides, one of the subscribe events gives me wrong results as 0, even if table has some datas.

How can I get subscribe event only once when I request once query with observable?

**Comment by cmelchior** [comment]
@rfrost77, that is by design. A RealmResults observable will emit each time the data changed. If you are creating a async query, it will immediately emit a empty list as well, this is also by design as sometimes you want some placeholder result right away.

If you are only interested in the first "real" result you can do the following:

```
realm.where(Foo.class).findAllAsync().asObservable()
  .filter(results::isLoaded)
  .first()
  .subscribe( ... ) // You only get the results once
```

This is not entirely clear from the Javadoc though, and we should update it to mention how the Observable behaves, so it doesn't come as a surprise.

**Comment by rfrost77** [comment]
I solved the problem with your answer. Thanks!
