### ISSUE TITLE
Help! Realm do not release disk space

### ISSUE THREAD

**Issue by LiuDeng** [realm/realm-java#2140]
Realm realm  = RealmUtils.getDiskDefaultRealm();
                realm.executeTransaction(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        realm.allObjects(Joke.class).clear();
                        realm.allObjects(Comment.class).clear();
                        realm.allObjects(DateJokeHeader.class).clear();
                        realm.allObjects(JokeWeb.class).clear();
                        realm.allObjects(JokeCount.class).clear();
                    }
                });
                for (int i=0;i < 100; i++)
                    realm.close();
no matter how i try  i can not clear disk space store the objects, the data space cost in setting application info do not decrease.
At same time  i can not query the objects from the realm, so the objects are leaked

**Comment by LiuDeng** [comment]
i can not upload image to github and have explains in this link . There is a demo application project and apk that show the problem.
http://note.youdao.com/share/?id=80fd22a02a20740f9a79ec0bbfd7dce4&type=note

**Comment by LiuDeng** [comment]
the demo code is very simple 

public class MainActivity extends AppCompatActivity {

    Realm realm;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Realm.setDefaultConfiguration(new RealmConfiguration.Builder(this).deleteRealmIfMigrationNeeded().build());
        realm = Realm.getDefaultInstance();
        List<Auth> auths = new ArrayList<>();
        for (int i= 0; i< 100000; i++)
        {
            Auth auth = new Auth();
            auth.setPlatform(i);
            auth.setAvatar("test string test string test string test string test string test string test string test string");
            auth.setToken("test stringtest stringtest stringtest stringtest stringtest stringtest stringtest stringtest string");
            auth.setUuid("test stringtest stringtest stringtest stringtest stringtest stringtest stringtest stringtest stringtest string");
            auths.add(auth);
        }
        realm.beginTransaction();
        realm.copyToRealmOrUpdate(auths);
        realm.commitTransaction();
    }

    @Override
    public void onBackPressed() {
        realm.beginTransaction();
        realm.allObjects(Auth.class).clear();
        realm.commitTransaction();
        super.onBackPressed();
        moveTaskToBack(true);
        finish();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        Log.e("MainActivity", "onDestroy");
        realm.close();
    }
}

**Comment by LiuDeng** [comment]
@cmelchior Please help! we are going to release and find this big problem which finally leak to 600MB than the app will block to reponse。

**Comment by LiuDeng** [comment]
@dalinaum @beeender @stk1m1 @emanuelez @kneth  Help me~ 
Best Wishes！~ Waiting online....

**Comment by LiuDeng** [comment]
version is 0.87.2

**Comment by cmelchior** [comment]
Hi @LiuDeng 
Realm is a MVCC database, which means that we are keeping multiple versions of your data if needed. This is usually happening if you open a Realm on multiple threads and forget to close it again as Realm then has to keep track of the changes between all versions. You can read more about it here: https://realm.io/docs/java/latest/#large-realm-file-size

As mentioned in the FAQ, right now we are not automatically compacting the file size, but it is not leaking. That space will just be used by future data.

I haven't tried your demo code yet, but from a quick glance it should leak any file size since it only operate on a single thread. I will double check tomorrow, but if it causes the file size to increase it is definitely a bug.

In any case, you can use `Realm.compactRealm()` to reduce the size of a Realm file to it's minimum.

**Comment by LiuDeng** [comment]
Than you so much! @cmelchior  and sorry for not read FAQ for this problem.I have test to use Realm.compactRealm() an it did release disk file ! and you do not need to test the demo agin! Thank you agin! 
Best wishes from deep heart! :100:

**Comment by LiuDeng** [comment]
@cmelchior  Realm.compactRealm return false in my project and have no info for why false.

**Comment by beeender** [comment]
You have to close all other Realm instance before calling `Realm.compact()`, and it is described in the java doc. 

https://realm.io/docs/java/latest/api/io/realm/Realm.html#compactRealm-io.realm.RealmConfiguration-

> The file must be closed before this method is called, otherwise false will be returned.

**Comment by beeender** [comment]
@LiuDeng See the above answer and translation below:

返回 false 是因为你有 Realm 实例没有关闭。具体卡可以看 `Realm.compactRealm` 的文档。建议在合适的时机进行compact，例如，应用程序刚启动，没有打开 Realm 实例之前。 另外，Realm 文件的空间不会被浪费，这些空间会在以后的操作中被重复使用。

**Comment by LiuDeng** [comment]
@beeender Thank you very much~
这个库真的很棒，谢谢~

**Comment by LiuDeng** [comment]
#beeender

**Comment by LiuDeng** [comment]
@beeender 悲剧了 我上线以后再小米手机上用compactRealm 以后提示invalid realm format  太坑了啊。。。

**Comment by beeender** [comment]
@LiuDeng 能复现么？从来没见过这个问题……

**Comment by beeender** [comment]
When compacting, the Realm file will be written to another file and then rename it to the original Realm file. Before renaming, the `fsync` was not done. But it should not be considered as a problem since even the process gets killed, the caches should be written back by the kernel's flusher daemon. 

We are not sure if Xiaomi device has any improper kernel settings/modifications cause the flusher doesn't behave correctly in this situation. To avoid this problem on those devices, now we are doing a `fsync` before renaming which has been merged by #2314 . The db file should never be corrupt even when the kernel doesn't flush the dirty pages back.

The fix will be released in 0.87.5.

**Comment by LiuDeng** [comment]
@beeender 非常感谢 Thank you so much~
