### ISSUE TITLE
Explain core architectural principles of Realm

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2185]
Near the top of the docs, maybe before “getting started”, above or below the code sample.

1) Live objects (zero-copy/always up to date)
2) Live queries (see above)
3) Everything reactive/observable (only true for objects right now, but will be soon)
4) Transactional concurrency (thread confinement / MVCC / Writes blocking / Reads free)

Some of this might already have been covered by other PR's.

**Comment by donnfelker** [comment]
This might be covered by: https://github.com/realm/realm.io/pull/1700

**Comment by cmelchior** [comment]
Yes, I think with #1700 all the bullets in this are actually covered by the docs. When that it is merged it might make sense to bundle them under a separate section at the top of the docs? Thoughts @nosrak113 @donnfelker ?

**Comment by donnfelker** [comment]
I feel all of this is very important, but I do wonder if putting it so close to the top might detract users away from immediately hopping in and getting to the immediate "wow". Maybe below the getting started/etc. I'm on the fence here because there are so many interesting things about Realm. I remember when I first saw Realm, what attracked me was that I didn't have to write SQL any more and I could work with POJO's out of the gate. I still think that is a huge value add, everything else is even more icing on the cake. Maybe thats the best way to put it - Objects are First Class and by the way ... you get all this other magical goodness for free as well. :)

**Comment by cmelchior** [comment]
Since all the above topics are already covered by the docs, any restructuring should probably only take place as part of larger restructuring of the docs in general alongside Cocoa/Swift and other bindings. In that context, it doesn't really make much sense to keep tracking this as a separate topic. So closing this until further notice.

/cc @timanglade
