### ISSUE TITLE
Need feature: custom table name

### ISSUE THREAD

**Issue by itrufeng** [realm/realm-java#2202]
I have a class
```kotlin
open class RealmLink: RealmObject(), Link {
    open override var url: String? = null
    open override var title: String? = null
    open override var createDate: Date? = null
}
```
The `Link` is a interface.
I want to save table `Link` not `RealmLink`. the `RealmLinkRealmProxy` can't do it.

**Comment by cmelchior** [comment]
Hi @itrufeng 
Right now there is no way around your model class being saved with its classname, so you could rename your Link interface in order to rename the RealmLink class.

We have an existing issue for tracking custom names here: https://github.com/realm/realm-java/issues/451 so you can follow that for updates on this feature.

**Comment by itrufeng** [comment]
Thanks.
