### ISSUE TITLE
Library shouldn't include android:allowBackup="true"

### ISSUE THREAD

**Issue by intrications** [realm/realm-java#2227]
I don't think this should be set in the library. Is there a reason it is there?

Including android:allowBackup="true" means it is a hassle to override this to false in my app.

https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/AndroidManifest.xml#L4

**Comment by cmelchior** [comment]
Hi @intrications 
I believe the idea is that as Realm create database files these should be backed up by default. As far as I know `allowBackup` default is `true` (http://developer.android.com/guide/topics/manifest/application-element.html) but Android studio some time ago enabled Lint warnings that complained if it wasn't explicitly set as it is a potentially security issue. 

I was under the impression that this setting could be overridden in the apps manifest, but there seem to be some outstanding issues: https://code.google.com/p/android/issues/detail?id=70073 which I agree is highly unfortunate.

We will have to look into any potential negative interaction with Lint, but otherwise I am not opposed to removing it.

**Comment by mikescamell** [comment]
This is causing me some problems also as having data backup makes no sense for the application i am developing. The data i store becomes irrelevant quickly. 

Without this i cannot update to 0.87.4 and see if some issues i'm having have been fixed regarding the clearing of data.

**Comment by cmelchior** [comment]
@intrications @mikescamell Just to be sure. Adding the below to your manifest doesn't work?

```
<application android:allowBackup="false" tools:replace="allowBackup" />
```

**Comment by mikescamell** [comment]
Cheers @cmelchior , i just remembered i could do that so edited my comment!

**Comment by cmelchior** [comment]
Closed by https://github.com/realm/realm-java/pull/2307
