### ISSUE TITLE
When will realm support LIMIT query??

### ISSUE THREAD

**Issue by wyvern610** [realm/realm-java#2278]
I have history table and need to shrink it periodically.
Now I delete first 50000 objects one by one like the following.

    RealmResults<Entry> results = realm.where(Entry.class).findAllSorted("created");
    List<Entry> entriesToDelete = new ArrayList<Entry>();
    for (int i = 0; i < results.size() && entriesToDelete.size() < 50000 ; i++) {
        entriesToDelete.add(results.get(i));
    }
    for (Entry entry: entriesToDelete)
        entry.removeFromRealm();

This is too slow. are there any alternative to do same things??
Or when will realm support limit clause??

https://github.com/realm/realm-java/issues/544
this was created last year but still no limit clause??? 
your development speed is too slow.

**Comment by cmelchior** [comment]
Hi @wyvern610 

With limited resources we always have to prioritize which tasks to work on, and LIMIT normally has clear work-arounds.

In your case you could make the following two step algorithm instead:

```
RealmResults<Entry> results = realm.where(Entry.class).findAllSorted("created");
Long max = results.get(Math.min(results.size() - 1, 50000)).getCreated();

realm.beginTransaction();
realm.where(Entry.class).lessThanOrEqual("created", max).findAllSorted("created").clear();
realm.commitTransaction();
```

I'll close this as an duplicate. You can follow progress on limit in #544

**Comment by patgoley** [comment]
I'd just like to say that the above solution is not a workaround for having a LIMIT on queries. You're doing two queries that scan the entire table instead of a single query. LIMIT is an optimization that allows this to occur with only a single query. Hence, this is not a workaround but a very inefficient way to get the same result. Doing more queries is not a workaround for something that is supposed to reduce the amount of necessary work.

**Comment by Zhuinden** [comment]
The initial code would have been much faster if he had just used `deleteFromRealm();` on the object instead of adding them to an ArrayList first which needs to reinitialize its internal array many many times.
