### ISSUE TITLE
Improvement: Check for closed Realm on Observable<RealmResults> before removing changeListener

### ISSUE THREAD

**Issue by mitchwongho** [realm/realm-java#2300]
Realm version: 0.87.4

In the case where the `Realm` associated with a `RealmResult` has been closed, the call to `removeChangeListener` in `RealmObservableFactory::getRealmResultsObservable()` may throw an `IllegalStateException`:

```
subscriber.add(Subscriptions.create(new Action0() {
                    @Override
                    public void call() {
                        results.removeChangeListener(listener);
                    }
                }));
```

An improvement may be to check if the Realm is closed before calling the `removeChangeListener`

**Comment by cmelchior** [comment]
Actually it throws that IllegalState on purpose because there is something wrong in how you control the lifecycle of your Realm.

There is a couple of methods you can use to check for it:

```
if (!realm.isClosed() {
  results.removeChangeListener(listener);
} 

// or 

if (results.isValid()) {
  results.removeChangeListener(listener);
}

```

will both work.

**Comment by mitchwongho** [comment]
In my implementation, I've create an Observable that:
1. gets a Realm(Context)
2. invokes `Realm.where(SomeClass.class).findAll()` and invokes `subscriber.onNext()` with the `RealResult`
3. add a subscription to `Subscriber` that closes the Realm when the subscriber unsubscribes

At the business end, when I subscribe to the Observable (described above), I `flatMap` to get the `RealmResult` on which I then transform in to an Observable using `RealmResult.asObservable`.

The `Subscription` produced by subscribing to the Observable is added to a `CompositeSubscription` which is clears and unsubscribed from on the Activity's `onPause()`. It's at this point that the Realm associated with the RealmResult is invalid for `removeChangeListener()` to be called.

**Comment by cmelchior** [comment]
It sounds strange in your above gist if the Realm is closed since you also get an instance in your Observable. Are you closing your Realm to many time? The Realm cache is instance counted, so it shouldn't close the Realm file resource until the counter reaches 0. Also, using the MainThreadSubscription is also a bit suspicious as far as I know that will use the handler to communicate, which might create some life cycle issues.

**Comment by mitchwongho** [comment]
The gist provided above is my current solution to avoid the `IllegalStateException` (by combining a Realm query _and_ RealmResult change events into one Observable).

I appreciate your comments.

In my previous implementation (which sparked this improvement issue), I had this (pseudocode):

```
...
    Observable<RealmResult> sub = doRealmQueryAsObservable(Model.class).
                flatMap( {realmResult -> realmResult.asObservable()} ).
                subscribe( { realmResult -> //do something on updates } );
    compoundSubscription.add(sub);
}
...
public void onPause() {
    compoundSubscription.unsubscribe();
}
```
Since I'm managing the Realm lifecycle in `doRealmQueryAsObservable()`, what I believe is happening is that when `compoundSubscription.unsubscribe()` is invoked, then the `Subscription` from `doRealmQueryAsObservable()` is completed (thus closing the Realm) and *then* then observable from `realmResult.asObservable()` is unsubscribed which attempts to invoke `results.removeChangeListener(listener)` but the Realm on which `results` is bound to is closed.

`MainThreadSubscription` is used to ensure that unsubscribing happens on the main thread.

If this issue is found to be a non-issue, and rather a user error, I'd be satisfied to have the issue closed.

**Comment by cmelchior** [comment]
Given the information above I would say it is a user error. We could relax the requirements for the `removeChangeListener` so it didn't fail if the Realm was closed, but I actually would prefer it to be there since it indicate that the lifecycle isn't completely under control, e.g. even if we fixed this, you would most likely have errors elsewhere.

We hope we can improve the lifecycle management as well in the future, so it isn't quite as hard to get right.
