### ISSUE TITLE
Realm Relation one to many 

### ISSUE THREAD

**Issue by MahmoudAlnouno** [realm/realm-java#2398]
I have module name Beneficiary and Reasons
```
class Beneficiary extends RealmObject {
private RealmResults<Reasons>
}
class  Reasons extends RealmObject{
private Long id;
private String description;
}
```
I can save data no problem with this 
but problem  is Duplication in Reasons after save in data base
 ```
Beneficiary beneficiary = new Beneficiary();
beneficiary.setId(dbPresenter.getNextId(Beneficiary.class));
beneficiary.setName(txtBeneficiaryName.getText().toString());
beneficiary.setReasonsRealmList(reasonsRealmList);
```
Duplication in Reasons (same Id and same name)

**Comment by cmelchior** [comment]
Hi @MahmoudAlnouno 

It isn't clear where you are getting `reasonsRealmList` from, but if objects in that list aren't managed by Realm they will be copied again, and since your Reason model class doesn't have a primary key they will be duplicated.

`setReasonsRealmList` is using `copyToRealmOrUpdate` automatically, so if you want to avoid duplicates you should either give your Reason objects primary keys or manually handle the update.

**Comment by MahmoudAlnouno** [comment]
@cmelchior  done I resolved this issue thank you
