### ISSUE TITLE
Huge Realm Data File 

### ISSUE THREAD

**Issue by jatinagrawal** [realm/realm-java#2461]
We are using Realm as part of our Android project. On 2 separate occasions, we have found our app to have used more than 300 MB data per App Info -> Storage. Yesterday, this was 1.5 GB on my phone. Our datasize is small and we expect few MBs to be used at max. 

We don't have the 1.5 GB file available, but we were able to reproduce a 320MB file again. On opening in Realm Browser, we see less than 1000 records across all the 11 Realm Entities. On exporting, we get "open() failed: Permission denied" error. We were able to export another Realm file which is 14 MB in size. This reduced from 14 MB to 128 KB. 

My question is:
1. What is making Realm use this much (1.5GB, 320 MB, 14 MB) data on devices
2. Is this a known Realm bug for which fix is available?
3. What can we do to avoid hitting this?

1) Larger File(320MB) :- https://drive.google.com/open?id=0B7JpkyAaMXPcRE14MjNtcHJqN0k
2) Smaller File(14 MB) :- https://drive.google.com/file/d/0B7JpkyAaMXPcOHMwbVBjQ2F2MVU/view

Realm version(s): 0.87.4

Android Studio version: 1.5.1

Which Android version and device:  Android 5.1 Moto G, Android 4.4 Galaxy Grand 2, Android 6 Nexus 5X

**Comment by beeender** [comment]
Here is the explanation of you problem https://realm.io/docs/java/latest/#large-realm-file-size

Please do close the Realm instance in the background thread after using them especially those thread without a looper.

**Comment by MGaetan89** [comment]
The link to `compactRealmFile` is not up to date. It should be https://realm.io/docs/java/latest/api/io/realm/Realm.html#compactRealm-io.realm.RealmConfiguration- (and labelled `compactRealm` I think).

By the way, what to you think about calling that method (`compactRealm()`) every time the application is closed (after calling the last `Realm.close()`) or every time the application is started (before the first `Realm.getInstance()`)?

**Comment by beeender** [comment]
@MGaetan89 I will update the doc right now, thanks a lot!

In normal case, Realm will try to reuse those spaces when data size grows, so if your max/min data size doesn't really have a huge diff, I don't think it is necessary to do compact.

More details about compact, when `compactRealm()` called:
Step 1, Realm will write the data into another file
Step 2, if the writing succeed, rename the other file to the current Realm file

In theory, it won't destroy the data even the process gets terminated. But it would take some time if the db file is really big. Also compacting requires you to close all the Realm instances first.
I would like to do it when app starts since it might not be easy to find a right time when Android app quits.

**Comment by beeender** [comment]
@jatinagrawal Is the issue solved? Can we close this issue now?

**Comment by jatinagrawal** [comment]
@beeender Yes it is. I am sorry I didn't close the issue. Thanks for your help.

**Comment by erudonja1** [comment]
Check this:
http://stackoverflow.com/questions/34217476/android-realm-large-file-size/42959238#42959238

**Comment by Zhuinden** [comment]
@erudonja1 technically `compactRealm()` doesn't actually compact (and returns false) if you have random open Realm instance somewhere that is unclosed, you can use `Realm.getGlobalInstanceCount()` to verify this

**Comment by erudonja1** [comment]
@Zhuinden yes, that's correct, but this solution doesn't depend on those situations. Try it :)
