### ISSUE TITLE
Only one RealmModule per file

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#2566]
http://stackoverflow.com/questions/36317366/realm-release-build-with-proguard-fails-could-not-find-io-realm-realmhelperma indicates that it is not possible to have multiple `RealmModule`s in one file.

Of course, it can be a bug but at least we should document it.

**Comment by mikemee** [comment]
As a second engineer on my team has just independently discovered this problem, I'm adding this note in support of something in the docs for this. I'm not sure if this is triggered by using Proguard, or it's a variation that only happens when running a release build.  

If just Proguard, then it would be great to add a note after the snippet in this section: https://realm.io/docs/java/latest/#proguard. E.g. something like:

> If you use @RealmModule, make sure you only have one declaration per java file, to avoid startup errors like: ` io.realm.exceptions.RealmException: Could not find io.realm.RealmHelper`.

Why here?  Because the nature of the FATAL EXCEPTION trace suggests a proguard related problem and it was the first place I looked in the Realm docs for a solution. (The trace had things like: `at io.realm.ab.a(Unknown Source)`).

**Comment by kneth** [comment]
@mikemee Thanks for your comment. We haven't had time to dig too deep into the issue yet but we'll update the documentation when we have a clear picture of the cause and the workaround.
