### ISSUE TITLE
TimeoutException io.realm.internal.Table.finalize() timed out after 10 seconds  raw

### ISSUE THREAD

**Issue by mihirjoshi21** [realm/realm-java#2614]
This is rather a unique crash and only happened in one of production build as of now. 

`Fatal Exception: java.util.concurrent.TimeoutException
io.realm.internal.Table.finalize() timed out after 10 seconds
 raw
io.realm.internal.Table.finalize (Table.java:120)
java.lang.Daemons$FinalizerDaemon.doFinalize (Daemons.java:206)
java.lang.Thread.run (Thread.java:818)`

#### Version of Realm and tooling
Realm version(s): 0.87.4

Android Studio version:  2.1

Which Android version and device: Samsung SM-G360T1 5.1.1 and Arm-v7a

**Comment by cmelchior** [comment]
Hi @mihirjoshi21 
We recently made improvements to make this is better in 0.88.3. A complete fix is being tracked in #2496 
The root cause is that Android cannot keep up cleaning up all the native objects that are potentially created if iterating a large collection of RealmResults. I'll close this as an duplicate, but please upgrade to 0.88.3 to see if that fixes your problem, otherwise you can follow progress in #2496.
