### ISSUE TITLE
Get Realm Schema version of installed application before migration

### ISSUE THREAD

**Issue by bsmn99** [realm/realm-java#2645]
We have a four version of realm database schema, but didn't updated the schema version of the realm configuration, for all four time. i.e for all the version the schema is **1**. We handled the RealmMigrateException and recreated the database as we don't keep the records whenever the app gets an update.

Now the problem is, the Migration is going to take place in the upcoming version, and if we do the Migration starting now, the Users who is skipping the update(Lazy to install the update) will hit the exception as the migration will not work for that scenario.

I Just want the schema version of the already installed application before the Migration Exception occurs when the app is updated. With schema version i can delete the database lower to the Migrated Version and update the app with Migration which is equal or higher.

How to handle this? Helps needed. @timanglade

**Comment by stk1m1** [comment]
Hi @bsmn99,

Judging from what is described from your issue, you should be able to provide a migration scheme for each version of older database. Nevertheless, it would be helpful for us to provide more assist if you could provide a small section of your code demonstrating how you performed migration tasks previously, especially the following.

> We handled the RealmMigrateException and recreated the database as we don't keep the records whenever the app gets an update.

You are also encouraged to make a reference from [a migration example](https://github.com/realm/realm-java/tree/master/examples/migrationExample) we carefully constructed for various scenarios.

**Comment by bsmn99** [comment]
Hi @stk1m1 

Just like this,

The below configuration is same for all of our app versions, handled the exception and delete the database and recreated when get instance.

```
RealmConfiguration realmConfiguration= new RealmConfiguration.Builder(this)
                .name("DBNAME") 
                .schemaVersion(1) 
                .build(); 
```
    try {
        return Realm.getInstance(realmConfiguration);
    } catch (RealmMigrationNeededException e){
        try {
            Realm.deleteRealm(realmConfiguration);
            //Realm file has been deleted.
            return Realm.getInstance(realmConfiguration);
        } catch (Exception ex){
            throw ex;
            //No Realm file to remove.
        }
    }`

**Comment by beeender** [comment]
@bsmn99 I suggest a simpler way to achieve your use case.
When you want to abandon the whole old db schema, you could just use a new different `name()` for the `RealmConfiguration()` and the `schemaVersion()` could start with 1 since it is a totally new db.
And if you want to delete the old db, you can just use the old name to create the `RealmConfiguration` and call `Realm.deleteRealm()`.

**Comment by bsmn99** [comment]
That is the issue for us now, we cannot able to detect the installed schema version, i.e the old schema version before migration, 

The exact scenario is,

1. App version 1 - Schema V1
2. App version 2 - Schema V1
3. App version 3 - Schema V1
4. App version 4 - Schema V1

Now the app is going to be updated with schema V2 with Migration, 

So the user whoever update the app from App version 4 have no worries, But the users who is going to update their app from below V4 surely hav troble with Migration exception, right?

Our Plan A is, how to handle the exception for those who skip the sequential update.

Our Plan B is, If we can able to detect the schema 1 version before update, just delete the database and recreate for them, If schema version is above 2 then the migration will continue work as normal.

**Comment by beeender** [comment]
@bsmn99 Let's say you are using below `RealmConfiguration` to create the Realm for App version 1-4

```java
RealmConfiguration realmConfiguration= new RealmConfiguration.Builder(this)
                .name("DBNAME") 
                .schemaVersion(1) 
                .build(); 
```

So you will have the Realm db file named `DBNAME.realm` in the app's internal files directory.

When you update the app to version 5, you are going to delete the old db and create a new one instead, you could just use a new `RealmConfiguration` instead like:

```java
RealmConfiguration realmConfiguration= new RealmConfiguration.Builder(this)
                .name("DBNAMEV5Plus") 
                .schemaVersion(1) 
                .build(); 
```

This will create a new realm db file named `DBNAMEV5Plus` in the app's internal files directory with the schema defined in the v5 app. It won't throw `MigratiaonNeededExcpetion` since it is not migrated from the old `DBNAME.realm`. And the `schemaVersion` can be started with 1 since it is a whole new db file.

If you want to delete the old db file as well, you can do:
```java
RealmConfiguration oldRealmConfiguration= new RealmConfiguration.Builder(this)
                .name("DBNAME") 
                .schemaVersion(1) 
                .build(); 
Realm.deleteRealm(oldRealmConfiguration);
```

The above is quite like your plan B, but it makes it simpler since you don't have to detect the schema version. Then you scenario becomes:

1. App version 1 - DBNAME Realm Schema V1
2. App version 2 - DBNAME Realm Schema V1
3. App version 3 - DBNAME Realm Schema V1
4. App version 4 - DBNAME Realm Schema V1
5. App version 5 - DBNAMEV5Plus Realm Schema V1

**Comment by bsmn99** [comment]
OK @beeender , please correct me if i am wrong as what i understood from your answer.

The 4 versions of app have same schema version 1. If 5th version is change with Different name the Migration Exception wont occur.

But What happens if the User is now At Version 4, who is going to update V6 of App(Schema V2 with Migration)

**Scenario - App version 4 - DBNAME Realm Schema V1 to App version 6 - DBNAMEV5Plus Realm Schema V2**

**Comment by beeender** [comment]
@bsmn99 If user update from app version 4 to app version 6 which means he/she is going to use `DBNAMEV5Plus Realm Schema V2`, `MigratioNeedednException` won't be thrown in this case since he/she haven't have the `DBNAMEV5Plus Realm Schema V1` before. A `DBNAMEV5Plus.realm` will be created automatically with the schema defined for `DBNAMEV5Plus Realm Schema V2`.

So
* The `MigrationNeededExcpetion` will be thrown only when there is a Realm file exists with an old schema version
* It won't be thrown if the Realm file doesn't exist. Instead a Realm file will be created with the `schemaVersion()` in the `RealmConfiguration`
* You still need to handle the migration from `DBNAMEV5Plus Realm Schema V1` to `DBNAMEV5Plus Realm Schema V2` in case of use update from App Version 5 to App Version 6.

**Comment by bsmn99** [comment]
Finally, there is some Solution, let me try it out. 
Thanks @beeender

**Comment by zaki50** [comment]
@bsmn99 I close this issue. If you'll have further questions, feel free to reopen this.

**Comment by engr-erum** [comment]
> Finally, there is some Solution, let me try it out.
> Thanks @beeender

@bsmn99  issue resolved ? pls share solution

**Comment by Zhuinden** [comment]
@engr-erum I'm not sure what the discussion was about, but you can open Realm and retrieve its schema version without initiating a schema check by opening it via `DynamicRealm.getInstance(realmConfig)`.

**Comment by mayurik18** [comment]
This solution worked for us:

Realm.init(context);
RealmConfiguration realmConfig = new RealmConfiguration.Builder().build();
DynamicRealm realm = DynamicRealm.getInstance(realmConfig);
long version = dynRealm.getVersion();//this will return the existing schema version
dynRealm.close();
