### ISSUE TITLE
RealmResults manual sync and change notification

### ISSUE THREAD

**Issue by roughboy** [realm/realm-java#2650]
I have following scenario:
1. Get some RealmReseults
2. Add change listener to RealmResults
3. Disable auto refresh
4. Modify data underneath the RealmResults (from point 1)
5. Enable RealmResults
6. I am done and want to synchronize RealmResults and trigger change listener associated with them

The reason i am doing it is that I need data to be synchronized after I am done (not earlier). 
How can I achieve it? I've seen that RealmResults contains methods syncIfNeeded/notifyChangeListeners, however they are package protected. Is it possible to make it public?

**Comment by cmelchior** [comment]
Hi @roughboy 
In 0.89 change listeners are already delayed until next looper event. Disabling auto-refresh will prevent the change event from being sent all together. So just using it as normal should be fine?

```
RealmResults<Foo> results = getResults();
results.addChangeListener(listener)
modifyResults(results);
... listeners will automatically be triggered now on the next Looper event?
```

**Comment by roughboy** [comment]
I'm afraid, next looper event is too late in my case.

**Comment by cmelchior** [comment]
What is your use case since you cannot wait to the next looper event?

**Comment by roughboy** [comment]
It is quite complex, however I will try to explain the best I can.

I have recyclerview with items. Each item has a slider that allows to rearange item position on the list. I am using ItemTouchHelper to detect movement of items. Each time ItemTouchHelper.onMoved is called i am updating item position in realm. On the time of position update transaction in realm I am forced to disable realm autoRefresh because that would cause calling notifyDatasetChanged on my adapter and as the result the ongoing movement action will be cancelled (I should be able to move item by more than 1 position at a time). Now straight to the point: consecutive position update transactions require to operate on up-to-date data.

Example:

	<-> means switching items:

	Item A (position 1)
	Item B (position 2)
	Item C (position 3)
	A<->B  // positions are updated, and data needs to be synced
	Item B (position 1)
	Item A (position 2)
	Item C (position 3)
	A<->C // positions are updated, and data needs to be synced
	Item B (position 1)
	Item C (position 2)
	Item A (position 3)

**Comment by bkromhout** [comment]
@roughboy, you should try to use the more granular notify*Changed() methods where possible. Both Thorben Primke's [realm-recyclerview](https://github.com/thorbenprimke/realm-recyclerview) and my [realm-recyclerview-lite](https://github.com/bkromhout/realm-recyclerview-lite) (which has drag-and-drop support built-in) make use of the more granular methods. I can't speak for the former since I'm not its dev, but I've ensured that the latter is up to date and works correctly with Realm 0.89.1 since I use it for a project being actively developed.

**Comment by cmelchior** [comment]
@roughboy it sounds like you are hitting a use case that our ChangeListeners are not really suited for. I think it will probably be easier to implement your own listener scheme for this, especially since you know exactly which items are being changed.

That said, you are not the first to experience problems integrating Realm with RecyclerView animations, so it probably something we should look into providing a sample for.

**Comment by roughboy** [comment]
@cmelchior you are right, it seems like i was misusing realm listeners concept. Anyway, i've already solved my problem, however any example integrating Realm with RecyclerView animations would be very welcome.
