### ISSUE TITLE
Is there any reason for pagination in a RealmBaseAdapter that is fed by RealmResults?

### ISSUE THREAD

**Issue by luzianscherrer** [realm/realm-java#2713]
I've read the discussions about a LIMIT feature for queries and the lazy loading of Realm results. Just to make sure: there is no reason to implement some kind of pagination even when I have a huge ListView with a RealmBaseAdapter that is fed by RealmResults, is there?

But let's say I wanted a pagination feature just for the purpose of the user experience. I wanted to show 50 entries in the ListView and then have a "load another 50 entries" button at the very top of the list. How would I formulate the Realm queries to get chunks of 50 entries from my data?

**Comment by cmelchior** [comment]
Hi @luzianscherrer 
No, you shouldn't need pagination with RealmResults since everything is lazy-loaded.

If you want to implement pagination, it is not something you can describe in a query. Some solutions could be to either use the standard `RealmResults.subList()` or keep track of indexes + pages yourself.

**Comment by luzianscherrer** [comment]
Got it, thanks!

**Comment by Zhuinden** [comment]
> Just to make sure: there is no reason to implement some kind of pagination even when I have a huge ListView with a RealmBaseAdapter that is fed by RealmResults, is there?

`RealmResults.get()` obtains a weak reference only when `get()` is called, but the list itself doesn't contain the objects, which means pagination is not needed as the required query is executed only when you call `results.get(i)` and otherwise are not in memory.

So while you can have pages from `[0...49]`, [50...99]` and the like manually if you want, your `RealmResults` itself gives you indirect access to the realm object, but doesn't contain them in memory, so pagination for the sake of "not loading too much data" isn't required at all, as you're not actually loading the data until you directly index them.
