### ISSUE TITLE
Performance improvement - Suggestion 

### ISSUE THREAD

**Issue by Ozrenko** [realm/realm-java#2806]
I saw that you started using enums. Maybe you should reconsider that decision since google doesn't recommend using enums in Android. They talk more about enums in this video: https://www.youtube.com/watch?v=Hzs6OBcvNQE

They suggest using annotations instead of enums.

**Comment by cmelchior** [comment]
Thank you for the suggestion. We already knew about that video when making the decision though.
There main difference between enums and ints are not speed, but memory usage/file size. Since we only use 2 enums I doubt you can measure any difference either, so we preferred the better type safety and more idiomatic Java code.
