### ISSUE TITLE
Generated RealmProxy class try to access wrong RealmProxy class for internal fields when using an interface hierarchy

### ISSUE THREAD

**Issue by dmarcato** [realm/realm-java#2808]
#### Goal

I'm trying to take advantage of the new interface `RealmModel` and add some abstraction to my models. My goal is to define an interface for my Realm classes to hide details of the implementation.

#### Steps & Code to Reproduce

Given the following structure (in Kotlin, but should be the same in Java):

```kotlin
interface Address : RealmModel
open class RealmAddress() : Address {
    [...]
}

interface User : RealmModel {
    val addresses: MutableList<Address>
}
open class RealmUser() : User {
    override var addresses: RealmList<Address> = RealmList()
}
```

The generated `RealmUserRealmProxy` try to access `RealmAddressRealmProxy` and its table name by relying on a convention on the type of the field `addresses`, but in this case it fails since it tries to look up `AddressRealmProxy` and `class_Address` instead of `RealmAddressRealmProxy` and `class_RealmAddress` since the type of `addresses` is `RealmList<Address>` instead of `RealmList<RealmAddress>`.

I think the code I'm writing should be correct, if not then probably I misunderstand the purpose of using the `RealmModel` interface instead of extending `RealmObject`...

#### Version of Realm and tooling
Realm version(s): 0.90.1

Android Studio version: N/A

Which Android version and device: N/A

**Comment by cmelchior** [comment]
You are correct. This is a bug that should get fixed.

While investing this I also found another bug:
- The annotation processor doesn't correctly complain if you forget to add `@RealmClass` to the model class that extends a custom interface.

**Comment by cmelchior** [comment]
Ups, I totally misunderstood this issue when reading it the first time. Sorry about that.
The issue here is that polymorphism isn't supported yet, e.g. "Address" could be any number of given implementations. This isn't supported by Realm yet, but is tracked here: #761 

Until then, all Realm Model classes must point to concrete instances. 

I'll close this as an duplicate instead. Sorry for the confusion.

**Comment by cmelchior** [comment]
Instead we should detect this scenario in the annotation processor and throw an error there instead of generating a Realm proxy class that clearly doesn't work.

**Comment by NitroG42** [comment]
> Until then, all Realm Model classes must point to concrete instances.

But isn't what the @RealmClass should do (point to a concrete instances), instead of the reammodel interface ?   that would allow us to have common code and attributes.
It might not be the good place to ask this but I didn't quite get the point of having a RealmModel interface because as you can't extend anything directly, the behaviour is the same than RealmObject, isn't it ?

**Comment by cmelchior** [comment]
Yes, currently it is, #761 will change that going forward, but right now it is mostly if you want to keep the model classes "cleaner".

**Comment by NitroG42** [comment]
Oh yeah I thought that might be for a future implementation. Thanks for the answer !
