### ISSUE TITLE
RealmBaseAdapter not notified properly about DataSet changes.

### ISSUE THREAD

**Issue by changxiangzhong** [realm/realm-java#2847]
I'm using the realm 0.88.3 version. We got a bunch of crash reports.

http://crashes.to/s/487c610ad24
http://crashes.to/s/0571baab0c0
http://crashes.to/s/3e9fe666f7f
http://crashes.to/s/b1519bf75f3
http://crashes.to/s/9aae9098e45

They all depicts the Adapter of a listView was not properly notified. So I spend some time on digging into the source code.

IMHO, there's one thing might introduce this issue. `HandlerController::addChangeListenerAsWeakReference` - the RealmBaseAdapter is notified by the weak reference. In case of memory shortage, the weak reference could be GC'ed. And The Adapter will not be notified. And then the app crashes. 

What do you think?

**Comment by beeender** [comment]
`RealmBaseAdapter` is holding a "strong" reference to the change listener, so it should not be GCed unless the adapter itself gets GCed.

We got similar issue reported #2408 but no luck to find out the root cause ... 

Do you have a chance to reproduce it with any devices?

**Comment by beeender** [comment]
An other question, do you delete any object which is related with the problematic adapter in the UI thread?

**Comment by changxiangzhong** [comment]
Thanks for your quick reply. We don't have any chance to reproduce it in the house. We only get crash report from production environment.

Concerning to 2nd question, yes, we do. We just wipe out all the data in one table before inserting.

We had used 0.87.4 and 0.82.1 for a long time, and it seems to be more stable.

**Comment by beeender** [comment]
Is it possible to share some source code with us? the adapter, the place to call the adapter, the place delete object. to help@realm.io if you want to share it privately. If you can share the whole project, that would be great.

**Comment by changxiangzhong** [comment]
@beeender I'll do some preparation work and send you part of the source code.

**Comment by changxiangzhong** [comment]
@beeender An email was sent last Friday

**Comment by beeender** [comment]
@changxiangzhong Sorry for the late response, we were busy with 1.0.0 release for last a few days.
I am checking your project right now.

**Comment by beeender** [comment]
@changxiangzhong The `checkLeak()` is called in the `logout()`, as what i can see, it will just close all Realm instances (and it actually won't, it will just close the only instance on that thread since Realm only has one instance on one thread for the same file based on reference counter, but this is another topic). Is it possible that for some reason `checkLeak()` called caused the Realm instance closed, then the listener won't be triggered?

**Comment by changxiangzhong** [comment]
@beeender Thank you so much for looking into the code. 

The checkLeak is a safety-keeping method - to avoid `Realm` instances leak. A `Realm` instance is wrapped by a `DAO` object, which is created/destroyed in the `onCreate()` and `onDestroy()` in `Fragment` (We are aware of `onDestroy()` is not guaranteed to invoked)

**Comment by beeender** [comment]
Yes, i saw the usage of `checkLeak` in your project.

I am wondering, if there is a chance that `logout` called (it will call `checkLeak`) before your listview get destroyed, then the problem with that stack trace could happen. The sequence is something like:

logout
close all the Realm instances
...
some UI event for the fragment's listview
crash happens, since the realm is closed, and the listeners won't be triggered anymore


BTW, I don't think the `checkLeak` for safety-keeping is a good idea. The life cycle of Realm instance should be controlled precisely by the Activity/Fragment/Application/etc.. IMO, if there is a need for safety-keeping, something has been going wrong already.

**Comment by changxiangzhong** [comment]
@beeender I'll take your advice to remove the `checkLeak` method. 

Concerning to the edge case you were talking about, yes it's possible. But it should not be that often.

**Comment by beeender** [comment]
http://stackoverflow.com/a/26672544/1396606 This answer is quite helpful to understand the 
> The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131624145, class android.widget.ListView) with Adapter(class no.hyper.campaign.ui.fragment.CampaignListFragment$CampaignListAdapter)]

Since we have a clue that might be related with `logout` and `checkLeak`, it would be safe that you can try to emulate the crash then verify the fix :)

**Comment by changxiangzhong** [comment]
Yeah, I'll try to emulate the crash. And push the fix to the production environment and see if we are going to get more crash reports. My gut feeling is the 0.9.x releases were more stable than 0.88.3 builde. Thanks for the support! And congratulations to the 1.0 release!

**Comment by stk1m1** [comment]
hi @changxiangzhong 

Any progress so far? Has @beeender's advice helped you?

**Comment by changxiangzhong** [comment]
@stk1m1 We haven't used the latest 1.0 version. We have been using 0.90 version in production. And it's pretty stable, much better than 0.88.3
