### ISSUE TITLE
.asObservable isn't available when implementing RealmModel

### ISSUE THREAD

**Issue by Glurt** [realm/realm-java#2848]
I was originally going to use the interface to define Realm models but it appears that you can't call .asObservable on an object defined this way. Extending RealmObject is the only way to get this to work.

**Comment by cmelchior** [comment]
Yes, that is intentional. Otherwise you would be forced to have a a no-op implementation in your own class since.

If you want to get an observable when using `RealmModel` you have to use `RealmObject.asObservable(myObj)`. This is also described here: https://realm.io/docs/java/latest/#realmmodel-interface

**Comment by cmelchior** [comment]
I assume the above answered your question, if not feel free to re-open.

**Comment by Glurt** [comment]
Apologies for the delayed reply. Extending RealmObject is perfectly fine for my project so this issue isn't really affecting me.

I do think it would be worth bumping the interface documentation up to just under RealmModel though since they seem like different ways of achieving the same thing.
