### ISSUE TITLE
Probably misleading Realm lifecycle documentation

### ISSUE THREAD

**Issue by mkoslacz** [realm/realm-java#2855]
In your docs, in *Controlling the lifecycle of Realm instances* paragraph (https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances) you wrote that the easiest and safest approach is to close a Realm instance in `onDestroy()` method of `Activity`, and to use `onStart()/onStop()` for `Fragments` as theirs `onDestroy()` might not be called. Actually, there is also no guarantee of  `Activity's onDestroy()` being called (https://developer.android.com/reference/android/app/Activity.html#onDestroy()), and it's recommended to free all resources using `onStop()` (https://developer.android.com/training/basics/activity-lifecycle/stopping.html#Stop):

>  In extreme cases, the system might simply kill your app process without calling the activity's final onDestroy() callback, so it's important you use onStop() to release resources that might leak memory.

Moreover,  `onCreate()/onStop()` methods also overlap when switching between `Activities` (https://developer.android.com/guide/components/activities.html#CoordinatingActivities), so wouldn't it be a better practice to open and close a Realm instance on `onStart()/onStop()` methods for `Activities` also?

**Comment by diegomontoya** [comment]
+1 We also ignore this doc line and do the proper realm closing in onStop(). The problem with onStop() is  there could a lot of wasteful realm open/close since onStop() to onStart() can happen very frequently if the user is jumping back and forth between activities/fragments. Our solution is to call a "UI Thread" delayed realm close in onStop().  This reduces the frequency of realm opens/closes by a wide margin if activities/fragments shared the same realms.

**Comment by mkoslacz** [comment]
If I correctly understand following Realm documentation line:

> To avoid the overhead of opening and closing the Realm data connection, Realm has a reference counted cache internally. This implies that calling Realm.getDefaultInstance() multiple times on the same thread is free, and the underlying resources will automatically be released when all instances are closed.

Doing so doesn't take much resources.

**Comment by cmelchior** [comment]
@mkoslacz If the process is killed it doesn't matter that the Realm isn't closed. Also `onCreate` is always used in Activities which means that `onDestroy` is a nice complement to that. It also reduces the amount of life cycle methods you have to implement.

That is the reason we suggest onCreate/onDestroy, but you are right, you can just as well use onStart/onStop.

**Comment by mkoslacz** [comment]
Ok, but well, maybe I haven't understood something, but you say that:

> If the process is killed it doesn't matter that the Realm isn't closed.

In case of using `onDestroy()` method you have your Realm instance opened while your `Activity` is stopped, and you close this Realm instance just before destroing `Activity`. Moreover, according to your words, if your app process is killed, it doesn't matter that the Realm isn't closed. So if I use Realm in every `Activity` in my app, does it make sense to close Realm just before process is killed (using `onDestroy()`)? 

I can imagine a scenario that makes sense using this approach; it's when you use Realm instance only in some *non-root* `Activities` of your app, as using back button on the root `Activity` just switches to the launcher app, and it doesn't close your app. It makes you keep Realm instances closed while displaying non-db `Activities`. Am I right?

**Comment by cmelchior** [comment]
OnDestroy might be called in other circumstances than on process death, e.g Activities in the background can get killed if the system is low on resources. In general the reason we recommend closing Realms explicitly is because Realm is an MVCC database which means it can hold multiple versions of your data on different threads. If an old version of your data is left open, you will see an increased disk usage. This is not a problem on the UI thread though as that is automatically kept up to date through the Looper.

So in that respect you are right, closing the Realm in Activities is just best practice in order to preserve resources as much as possible, the downsides are very small if you don't. 

So yes you your examples are correct.

**Comment by Zhuinden** [comment]
@cmelchior if the Realm on the main thread is automagically updated by the Looper whenever there's a committed transaction in the Realm, but the resources need to be freed up (and as such the Realm has to be closed) primarily on background threads because they aren't auto-updated, but doesn't that mean that you don't actually **need** to close instances of Realms on looper threads?

**Comment by mkoslacz** [comment]
In short words I would describe it like this: closing the Realm in Activities is just best practice in order to preserve resources as much as possible, but the downsides are very small if you don't do it. The essential thing is to explicitly close all Realm instances on every `non-Looper` thread, ie. `IntentService` or `AsyncTask`.

**Comment by Zhuinden** [comment]
@mkoslacz Wait, isn't the IntentService a looper thread?

**Comment by cmelchior** [comment]
It is, but you only call onHandle for each Intent, so for the purpose of the Realm lifecycle you should think of it as a normal background thread.

**Comment by Zhuinden** [comment]
Oh, I see. Thank you for the info.

**Comment by kneth** [comment]
We have updated the documentation: https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances
