### ISSUE TITLE
Website says 1.0.0, but Changelog says 0.91.1

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#2878]
#### Goal

> What do you want to achieve?

Know what the latest version is

#### Expected Results

Changelog should say 1.0.0

#### Actual Results

Changelog says 0.91.1

#### Steps & Code to Reproduce

Look at the [committed version](https://github.com/realm/realm-java/blob/master/CHANGELOG.md) :tongue: 

Congratulations on the 1.0.0-ifying though, I guess the P1 is done and it's time for backlinks and fine-grained notifications! :joy:

**Comment by cmelchior** [comment]
We are making releases on the `releases` branch, that then gets merged back to master. That is not done yet (mostly because an automated script runs every few hours). But the changelog is here: https://github.com/realm/realm-java/blob/releases/CHANGELOG.md

And yes, now we move on to the next big features: Backlinks and fine-grained notifications are definitely high on that list 😄

**Comment by cmelchior** [comment]
The changelog should be on master now: https://github.com/realm/realm-java/blob/master/CHANGELOG.md

**Comment by Zhuinden** [comment]
Woo! It's official now :D
