### ISSUE TITLE
creating a standalone objet gives me this extra field called valid?

### ISSUE THREAD

**Issue by JohnnyTwoShoes** [realm/realm-java#2956]
Hi,

I copy an object, using copyFromRealm. But the data is now riddled with this extra field, "valid":false

How do I remove it?

Realm version(s): 0.87.0

Android Studio version: 1.5

Which Android version and device: 4.4.4 api19 genymotion

**Comment by cmelchior** [comment]
`isValid` is part of the state from RealmObject and indicate that the object is no longer managed by Realm. If you want to avoid having that as part of your model you can use our RealmModel interface instead of extending RealmObject. You can read more here: https://realm.io/docs/java/latest/#realmmodel-interface

**Comment by JohnnyTwoShoes** [comment]
ok, thanks.
