### ISSUE TITLE
Realm file not being deleted when app is uninstalled

### ISSUE THREAD

**Issue by guichico** [realm/realm-java#2992]
The realm file is no longer being deleted when I uninstall the app in the 1.0.0 version of realm.

**Comment by cmelchior** [comment]
Hi @guichico 
Please see https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues when filing issues. That way we can easier help us. Especially how we can reproduce this.

**Comment by guichico** [comment]
Is quite simple, I uninstall my app and the previous versions of 1.0.0 the realm file is deleted, but is no longer happening in 1.0.0 version. Its difficult to understand?
There is no code to explain that.

**Comment by cmelchior** [comment]
Since this is the first time we have ever heard about this. Then yes, it is difficult to understand. Especially since this isn't happening with our example projects.

As a minimum you should provide info about which devices / version of Android this is happening on. Even better would be something demonstrating it:  sample project / video / whatever. The reason we have a template is because some errors only happen on some devices and versions of Android. Without that information it is impossible to debug.

**Comment by Zhuinden** [comment]
When you uninstall the application, your `/data/data/com.example.acme` folder should be erased. If you're specifically opening the Realm on the external storage (and not inside of your internal storage dedicated data folder as per `context.getFilesDir()`), then the Realm file will not be removed.

The `Realm.getDefaultInstance()` and `Realm.getInstance(Context)` calls open the Realm in `getFilesDir()`, which means it should be deleted along with the application.

Maybe you're being a victim of the new Android's auto-backup feature?

**Comment by guichico** [comment]
Yes, Android's auto-backup feature is the problem.
Thank you for the answer.

**Comment by abroresonaliyev** [comment]
> Since this is the first time we have ever heard about this. Then yes, it is difficult to understand. Especially since this isn't happening with our example projects.
> 
> As a minimum you should provide info about which devices / version of Android this is happening on. Even better would be something demonstrating it: sample project / video / whatever. The reason we have a template is because some errors only happen on some devices and versions of Android. Without that information it is impossible to debug.

in some xiaomi phones
