### ISSUE TITLE
realm-java 2.0.0 don't support stetho-realm 0.9.0 reading realm databases ??

### ISSUE THREAD

**Issue by yanxinmiao** [realm/realm-java#3510]
i use realm-java 1.2.0 ,stetho-realm 0.9.0 can read realm databases . but i change real-java 2.0.0 ,stetho-realm 0.9.0 don't work . when i use chrome reading databases , my app throw exception :java.lang.NoClassDefFoundError: Failed resolution of: Lio/realm/internal/SharedGroup;

**Comment by snowpong** [comment]
Since the file format has changed I'm guessing stetho-realm 0.9.0 can't read it anymore. This is from the 2.0 changelog: "Files written by Realm 2.0 cannot be read by 1.x or earlier versions. Old files can still be opened." https://github.com/realm/realm-java/blob/master/CHANGELOG.md#breaking-changes

**Comment by cmelchior** [comment]
Hi @yanxinmiao Realm-stetho is not maintained by Realm as an official extension, but by @zaki50 (that accidentally also works for Realm). You should create an issue here instead: https://github.com/uPhyca/stetho-realm/issues.

**Comment by zaki50** [comment]
FYI: I've released `Stetho-Realm 2.0.0` which supports `Realm Java 2.0.0`.
