### ISSUE TITLE
Memory Leak with long lived Realm Objects

### ISSUE THREAD

**Issue by AOrobator** [realm/realm-java#3583]
I'm currently keeping my realm objects around as instance variables and seeing a lot of Activity memory leaks.

Attached is a screenshot from LeakCanary
![screenshot_20161006-220633](https://cloud.githubusercontent.com/assets/4106884/19176815/c811073a-8c11-11e6-94b5-62ac43d34804.png)

I have multiple variants of this leak, but they all share Realm.handlerController in the middle of their stacktrace with a static reference to the default EventBus instance. With regards to EventBus, I have ensured that I am registering and unregistering event listeners. Is it recommended that I just stay away from long lived Realm instances?
#### Version of Realm and tooling

Realm version(s): 2.0.0

Android Studio version: 2.2

Which Android version and device: Nexus 6P, Android 7.0

**Comment by Zhuinden** [comment]
Do you open/close the Realm in `onCreate()/onDestroy()`, or considering it's a fragment, in `onCreateView()/onDestroyView()`?

**Comment by kneth** [comment]
Closing Realms is important. Please take a look at https://realm.io/docs/java/latest/#closing-realm-instances

**Comment by AOrobator** [comment]
By long lived realms I mean for the entire lifecycle of an activity or fragment. I am making sure to close my realm objects in onDestroy() of my fragments. Is there a difference in closing it in onDestroyView()?

**Comment by AOrobator** [comment]
Upon closer look, I'm opening and closing in onStart() and onStop()

**Comment by Zhuinden** [comment]
I'm surprised you're not getting crashes when you put the application in background, bring it back foreground, then manipulate any item in your list.

**Comment by AOrobator** [comment]
Before any of the adapter methods are run their code, I first call `checkRealm()` which looks like

```java
void checkRealm() {
    if (realm == null || realm.isClosed()) {
        realm = Realm.getDefaultInstance();
        requeryForData();
    }
}
```

**Comment by Zhuinden** [comment]
And can you guarantee that that realm you open in your adapter is always closed when you expect it to be closed? :P

**Comment by AOrobator** [comment]
I have a `closeRealm()` method on my adapter that's called in `onStop()`

**Comment by AOrobator** [comment]
Here is the same leak without references to EventBus.
![screenshot_20161008-014346](https://cloud.githubusercontent.com/assets/4106884/19210715/1085fcd6-8cf9-11e6-85b0-e08024e0b9b8.png)

`Realm.handlerController` is still present.

**Comment by Zhuinden** [comment]
... Isn't that a list of weak references? I think that was a list of weak references.

**Comment by AOrobator** [comment]
I'm not using RxJava with my adapter. Is there somewhere I can share my code privately?

**Comment by cmelchior** [comment]
Hi @AOrobator. You can send any code to help@realm.io

**Comment by AOrobator** [comment]
I've sent an email to help@realm.io with attached code.

**Comment by beeender** [comment]
I checked your code, there is some suggestions:
1. Do not control the Realm instance lifecycle in the adapter, instead, passing a Realm instance to the adapter.
2. Control the the Realm instance lifecycle in the activity and fragment, and don't check with `realm.isClosed()`  because of:
   - Realm manage the instance by ref counter per thread, which means, if you call `getInstance()` multiple times in the same thread, the same Realm object will be returned. 

I can see in your `XXXOrXXXFragment.java` you are calling `Realm.getDefaultInstance` in both `onCreate()` and `onStart()`, but `Realm.close()` only in the `onStop` which probably leads to some instances not closed which is got from `onCreate`. I suggest you only use `onStart`/`onStop` to manage the lifecycle. See https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances

Also, I don't think checking `isClosed` before get instance is necessary.

**Comment by Zhuinden** [comment]
@beeender I'd rather recommend `onCreateView()`/`onDestroyView()`

**Comment by AOrobator** [comment]
@zhuinden what's the difference with using those lifecycle methods?

**Comment by Zhuinden** [comment]
@AOrobator well, try putting the app in background and bringing it back in foreground without recreating the view and trying to use the adapter, I think you're in for crashes :tongue:

**Comment by beeender** [comment]
@AOrobator Hope your problem got solved. Feel free to reopen it if needed.
