### ISSUE TITLE
Each element of 'value' must be a valid managed object.

### ISSUE THREAD

**Issue by gushoubang** [realm/realm-java#3595]
> We LOVE to help with any issues or bug you have!

> **Questions**:  Caused by: java.lang.IllegalArgumentException: Each element of 'value' must be a valid managed object.
When Iuse it like this 
![image](https://cloud.githubusercontent.com/assets/8435230/19217562/ee7cdccc-8e10-11e6-8ee6-b6da39932931.png)
![image](https://cloud.githubusercontent.com/assets/8435230/19217563/f9559a6c-8e10-11e6-92ee-252b65fc141b.png)

#### Version of Realm and tooling
Realm version(s): 2.0.2

**Comment by zaki50** [comment]
At first, `showMarker` seems to be an managed object.
You don't need to invoke `copyToRealm()` against managed object since it is a method for unmanaged object.

If `RealmList` from `getImgs()` contains unmanaged object, replace it with managed object before setting the list.

So the code should be somethin like:
```
realm.beginTransaction();
try {
RealmList<Image> list = imageShow.getImgs();
if (!list.isManaged()) { // if the 'list' is managed, all items in it is also managed
    RealmList<Image> managedImageList = new RealmList<>();
    for (Image item : list) {
        if (item.isManaged()) {
            managedImageList.add(item);
        } else {
            managedImageList.add(realm.copyToRealm(item));
        }
    }
    list = managedImageList;
}
showMarker.setImgs(list);
realm.commitTransaction();
```

And it's better to use `executeTransaction()` instead of `beginTransaction()`/`commitTransaction()`.

**Comment by gushoubang** [comment]
OK thanks
