### ISSUE TITLE
Fatal Exception: io.realm.exceptions.RealmFileException

### ISSUE THREAD

**Issue by xlrei** [realm/realm-java#3634]
I update realm to 2.0.2, then this exception comes a lot which never happened before. This Exception is happened in a IntentService and share RealmConfiguration Object with main process.

```java

Fatal Exception: io.realm.exceptions.RealmFileException: Realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture. in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 81
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:178)
       at io.realm.BaseRealm.(BaseRealm.java)
       at io.realm.Realm.(Realm.java)
       at io.realm.Realm.createAndValidate(Realm.java:284)
       at io.realm.Realm.createInstance(Realm.java:265)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:143)
       at io.realm.Realm.getInstance(Realm.java:228)

```

Realm version(s): 2.0.2

**Comment by beeender** [comment]
Is the IntentService running in other process?

The exception message changed, but it should be the same problem with https://github.com/realm/realm-java/issues/2459 

You can see more details there. According to the feedback, it only happens when user update the apk (from play store, right?) which may have a Realm file format update, and it is invisible to users (since we haven't heard of user complain it). Are you able to reproduce it or get any feedback from user who met this crash?

**Comment by xlrei** [comment]
@beeender I tried both (with other process or not), both has this exception. I did not meet this exception for a long time (half year with other process one) until I update Realm 2.0.2.  I can't produce it. And temporarily do not get user's feedback.

Our new version do not update to play store yet, so maybe it is new problem.

**Comment by beeender** [comment]
Does it only affect users who update the apk from play store? Does any other users update the apk from other stores have the same problem?

**Comment by xlrei** [comment]
Can't know it from Fabric but incline to the view that users updated apk.

**Comment by beeender** [comment]
Close and dup to #2459
