### ISSUE TITLE
SharedRealm.nativeRefresh is slow for big RealmResults

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3685]
From http://stackoverflow.com/questions/40221038/realm-large-realmresults-block-ui-thread-when-data-is-modified

We need to investigate the performance of `SharedRealm.nativeRefresh` when big RealmResults are present.

**Comment by Zhuinden** [comment]
At 100k+ numbers it was never fast.  It's partly the reason why the Context not being able to immediately release abandoned RealmResults is a pain, but calling explicit GC kinda killed Realm for a while back in the day.

**Comment by kneth** [comment]
Currently, we have too many objects when working with `ResultResults` (`TableView`  and `Query` + C++ friends). Moving to object store's `Results` class could potentially reduce the number of objects. But updating the object accessors might have time too.

**Comment by thadcodes** [comment]
@Zhuinden note that the performance issues start to pop up around 30-50k in some cases.   By 100k it's certain to be noticeable but often starts showing up earlier.

**Comment by nhachicha** [comment]
I did a `traceview` dump & I can confirm that `nativeRefresh` is responsible of slowing down the UI thread. changing the request to `equal` instead of `lessThan` help reducing the time required for `nativeRefresh` to complete, but it's still the dominant call in Traceview
<img width="794" alt="screen shot 2016-10-27 at 03 57 36" src="https://cloud.githubusercontent.com/assets/1793238/19753019/8bf1d070-9bf9-11e6-96e4-da8c8854f08e.png">

Note `nativeRefresh` is invoked because we have an async (read) query that we need to update (using `COMPLETED_UPDATE_ASYNC_QUERIES`) hence the call to `nativeRefresh` to advance the Realm/SharedGroup to the latest version.
 
I've noticed no dropping frames when switching to a sync query: 
`mActualList = mRealm.where(Attendee.class).lessThan("age", 20).findAll();`
but that's expected since we're avoiding calling `nativeRefresh`

**Comment by bdash** [comment]
Do we have a profile showing at the C++ level where time is being spent below `nativeRefresh`?

**Comment by nhachicha** [comment]
@bdash no native profile using Android Monitor, any ideas @beeender  @kneth ?

**Comment by kneth** [comment]
We haven't done native profile but we could try https://google.github.io/fplutil/android_ndk_perf.html

**Comment by beeender** [comment]
I will do a profiling soon

**Comment by Zhuinden** [comment]
I think using Async query with Object Store Results should have fixed most qualms in this regard

**Comment by beeender** [comment]
I did some testing with realm-java `v2.3.2` & `v2.3.0`. I couldn't see the `nativeRefresh()` problem with `v2.3.2`, but I did see the UI lags when scrolling the RecyclerView. 
With `v3.0.0` and realm-android-adapter `v2.0.0`, the scrolling is pretty OK even with 20k entries in the Realm.

There was a fundamental change in `v3.0.0` which should improve performance in this case.

For anyone interested in this issue, see the testing project:

[ProfilingRealmAsyn.zip](https://github.com/realm/realm-java/files/874576/ProfilingRealmAsyn.zip)

**Comment by thadcodes** [comment]
I since gave up on this issue being fixed before I needed it for my project. But just so you know 20-30k was the minimum. By 100k it was certain to happen. If you are saying you can't reproduce make sure you are scrolling while it's loading in all those entries and do it in 10k blocks.

**Comment by Zhuinden** [comment]
Async queries seem to be owrking for me as long as you don't continuously write to the Realm

**Comment by thadcodes** [comment]
@beeender did you happen to try my example from stack overflow which kicked off this bug?  It was a real use case simplified that I was trying to do with realm and failed. Was the main reason I didn't go with realm for this project. (although group by and protections were also a small factor). If it doesn't work then I'd argue this bug is not resolved....

**Comment by beeender** [comment]
@thadcodes Since the example on your SO question  is only a piece of code, i made something similar to it which can be seen in https://github.com/realm/realm-java/issues/3685#issuecomment-289667622 to do the profiling.

But if you have a full project to show the problem, i'd happy to look into this again.
