### ISSUE TITLE
Requirements elicitation

### ISSUE THREAD

**Issue by renatoabreu11** [realm/realm-java#3687]
Good morning,

We have already submited an issue with id #3613 about realm software  processes, and now we would want to know how the team deals with requirements elicitation. So, regarding this:

- How does the team decides on whether to implement a new feature?

- Does someone is responsible to decide which functionality will be implemented?

- What is the process to analyse and accept a pull request or an issue? 

- There are a Software Requirements Specification (SRS) document? 

We would be very pleased and thankfull if you could answer this questions.
Thanks in advance.

**Comment by Zhuinden** [comment]
I'm actually interested in the answers for these questions as well, I never know where the next goals come from

**Comment by kneth** [comment]
In the last two-three decades, the software development process has changed a lot. Back then, the waterfall model was the thing. Open source changed that very much. In general, Realm isn't govern by strict procedures, and we gradually change how we do things depending on who we hire (a new hire might have brilliant idea or know a great tool) and what we did wrong in the last major release.

* How does the team decides on whether to implement a new feature?

We are very much driven by what make sense for our users. Since our users are developers like us, we believe we have a pretty good idea of what makes sense. Of course, we listen - and therefore we enjoy attending meetups and conferences. 

* Does someone is responsible to decide which functionality will be implemented?

Decisions are done as a team. Of course, some team members have stronger opinion on some topics than others. In your area of expertise, your opinion weight more.

* What is the process to analyse and accept a pull request or an issue?

There is no formal process but at least two developers who have not written any code, must approve the PR (yes, for larger PRs, we are often two working together). For very large or complex PRs, we might schedule a meeting to highlight the hot spots. We prefer not do to that as such meetings are not done in public.

* There are a Software Requirements Specification (SRS) document?

We don't have a specification to write specifications.

Mostly, we are using  Github issues to specify requirements but in rare cases, we use our internal wiki (a private Github repo) or share a Google Doc/Sheet.

**Comment by Zhuinden** [comment]
@kneth how much does the Realm Core team and possible other higher-ups influence the next new feature -  for example that this time Sync was released? 

There had to be some kind of external factor to that.

**Comment by kneth** [comment]
Realm Mobile Platform (aka sync) is a long-term goal, and it has an impact on all Realm products/bindings. We strongly believe that Realm Mobile Platform makes sense for developers and all Realm developers particular in its development to some degree.

**Comment by Zhuinden** [comment]
Makes sense

**Comment by renatoabreu11** [comment]
Thank you very much for your help.
