### ISSUE TITLE
Support Realm Models from pure Java module?

### ISSUE THREAD

**Issue by zoltish** [realm/realm-java#3750]
**Context**
I have a core module in a large project, its Java only (no Android). The idea is to re-use most logic between Android and iOS by using J2ObjC, etc.

Im facing a quite huge limitation here though, since Realm cannot be used in a pure Java module -- I am forced to define the **actual** model classes in my Android module (and later on, iOS). 

To streamline the models, and re-use as much logic as possible; I came up with the solution to use interfaces in the core module -- and just use the "pure model" implementations of those on the Android and iOS side of things. 

## CORE (PURE JAVA)
```
interface FruitModel {
String getField() 
void setField(String value);
}

interface FruitRepository {
List<FruitModel> getFruitModels();
}

interface FruitManager{
void addFruit(FruitModel fruitModel);
}
```

## ANDROID
```
public class Fruit extends RealmObject implements FruitModel {
//fields + methods
}

public class FruitRepositoryImpl implements FruitRepository{
//returns a list of Fruit. Works fine.
}

public class FruitManagerImpl implements FruitManager{
//add FruitModel to Realm? Gotta cast it to (Fruit) and I lose all type safety + code is less readable.
}
```

# Ideal structure

## CORE (PURE JAVA)
```
@RealmClass
public class Fruit implements RealmModel{
//fields + methods. once. done.
}
```

## Core + Android + iOS all use the same class. 

I would greatly appreciate support for this, and Im certain Im not alone. I hope you can consider it moving forward, and that its possible without too much hassle.

Much love, thanks for the great library!

**Comment by stk1m1** [comment]
For reusing your predefined models across different platforms, specifically between Android and iOS, I'd urge you to take a look at [RealmBrowser](https://itunes.apple.com/us/app/realm-browser/id1007457278?mt=12). Not only it provide convenient ways to navigate schema, it also offers ways to generate platform specific models on the fly.

In my opinion, each Realm binding is built with considerable amount of effort to make it platform/language idiomatic than simple binding to core. Although one might be able to trace back to the same heritage from Obj-C and Java, it is nigh impractical to make all the bindings to use exactly the same class name/model as their thought foundation has deviated and consolidated quite significantly due to the fact that underlying platform has grown in different directions. 

Should you in dire situation to construct one source base and reuse across different platforms, [Realm-dotnet](https://github.com/realm/realm-dotnet) with Xamarin might give you some aid there.

**Comment by kneth** [comment]
I will strongly suggest that you ask this question at StackOverflow (SO). The SO community is large and other SO user might have experience the same issues as you. As Realm monitors relevant SO tags, we would to ideas from our community that way.

**Comment by zoltish** [comment]
**The Realm Annotations work fine as a standalone module. Would it be possible to extend this to also include the RealmModel interface?** 

From my standpoint, this should work pretty easily and would result in you being able to define models as part of a separate module, and have the annotation processor pick up the classes and make it all work. The only downside being that you cant explicitly use ` extends RealmObject `-- but Id say thats still a win and workable solution. Thoughts?

Disclaimer: I dont have all the superpowers relating to annotation processing. So please fill me in where my knowledge is lacking if the above logic doesnt work. Thanks for your time.

**Comment by beeender** [comment]
@zoltish I don't really get your question. Is it still related with the pure java and J2ObjC? Do you mean we make the RealmModule as a separated module?

**Comment by zoltish** [comment]
@beeender Sorry, it does still relate to my question. Im basically saying, move `RealmModel` to a separate module so that it can be used outside of realm-android. `RealmModel` isnt coupled with any logic, and as long as the annotation processor is able to pick it up (I dont see why it wouldnt) -- it would enable us to acheive what this thread is all about; defining models in a pure java module 👍

**Comment by beeender** [comment]
@zoltish I got it. The suggestion is you could define a dummy `RealmModel` when needed to achieve your goal. The problem of making it a separated module in our project is it makes our project structure more complex and it doesn't seem to be worthy ... (It is already a headache to us for the current complex gradle project, we have annotation processor, java bytecode transformer, etc.. Really sorry we couldn't take your advise, but I think define a dummy Interface in your side is quite a easy thing to do.)

**Comment by zoltish** [comment]
@beeender I hear you, and I know the pains of working with a large project - this whole suggestion is the result of it, after all :) I wasnt aware that its possible to create a dummy RealmModel as such. Would the annotation processor still pick it up?

**Comment by beeender** [comment]
@zoltish I am not familiar with J2ObjC thing, but if it is using to convert only the class declaration to objc class declaration, then you don't need the annotation processor since the annotation processor is only used to inject our Realm access logic to the java source code. But if the J2ObjC is used to convert all the project to objc and make it work like **magic**, i doubt it works -- Realm also relies on java byte code transforming and a native library which are quite difficult to deal with for a automation language level converter.

**Comment by zoltish** [comment]
@beeender I am looking to convert business logic only. The goal being to have changes to model objects (later on) be reflected in the iOS side of things automatically, I think this will save loads of time; but more importantly reduce bugs from writing the same exact variable names and structure of models twice. I think I have enough info to give this a shot now, if it works; Ill let you know! Thanks for the swift replies, and your awesome work on Realm 👍

**Comment by shilgaron** [comment]
@zoltish did you find a solution for your problem?
I'm now facing the exact situation. We have a big project with all the logic shared using J2ObjC, I'm considering using Realm for storing information but I want to use a much shared code as I can.

**Comment by zoltish** [comment]
@shilgaron The above solution didnt work unfortunately. Im going with the next best solution, which to me is declaring the model classes as interfaces in the shared module. All biz logic works with the interfaces and the _only_ thing the Android/iOS are responsible for is to actually create the "raw" models that extend RealmObject etc. It works great, but it wasnt easy coming up with a general enough solution to make it all work without directly accessing any of the models. I might write an article on how to get this setup when I find the time.
