### ISSUE TITLE
Realm where equals to Date return null

### ISSUE THREAD

**Issue by PhanVanLinh** [realm/realm-java#3811]
Here is my Realm database
https://i.stack.imgur.com/iOurG.png
Here is my code for find value with where and equalTo, when I use **int** it working, and if I use **Date** it not working.

You will see in the image, realmNumber return value, and realmDate return null but I provide correct date
https://i.stack.imgur.com/abaW6.png
```

realm.executeTransaction(new Realm.Transaction() {
    @Override
    public void execute(final Realm bgRealm) {

        StepEntry realmNumber = bgRealm.where(StepEntry.class).equalTo("steps", 0).findFirst();

        Date date = stepEntry.getDate();
        StepEntry realmDate = bgRealm.where(StepEntry.class).equalTo("date", date).findFirst();
    }
});
```
How can I make Realm where work with Date?

**Comment by cmelchior** [comment]
Hi @PhanVanLinh Please don't create issues here and on Stack Overflow. We monitor both and discussion is already ongoing in http://stackoverflow.com/questions/40648582/realm-where-with-date-return-null?noredirect=1#comment68531462_40648582

**Comment by Zhuinden** [comment]
@PhanVanLinh if you cannot find your object with `equalTo(field, Date)` then that means the Date you provide in the condition does not match.

Realm has milisecond precision since 0.90.0, so your Date must match in terms of hours, minutes, seconds, miliseconds (technically the long epoch time value must be the exact same)

**Comment by Zhuinden** [comment]
Question resolved in http://stackoverflow.com/a/40650542/2413303
