### ISSUE TITLE
Document order to apply plugins

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#3827]
A comment in #3783 suggests that the order which plugins are applied seems to matter. We should document this.

**Comment by Zhuinden** [comment]
Comment in question: https://github.com/realm/realm-java/issues/3783#issuecomment-260578984

**Comment by ivostoyanov** [comment]
If you use Kotlin and plugins are ordered like this:
apply plugin: 'com.android.application'
apply plugin: 'realm-android'
apply plugin: 'kotlin-android'
-> You get error:  "Object" is not part of the schema for this Realm

If you use Kotlin and plugins are ordered like this:
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'realm-android'
-> You get:  DefaultRealmModuleMediator.java -> error: unreachable statement

Tested with 'io.realm:realm-gradle-plugin:3.3.0' and 'io.realm:realm-gradle-plugin:2.0.0'. Kotlin version is: 1.1.2-4. 

I can't set a configuration that works with Kotiln. Since Android team announced Kotlin as first-class language for Android, probably it is good to make a thorough testing of Realm working with Kotlin.

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
