### ISSUE TITLE
app:compileDebugJavaWithJavac error 

### ISSUE THREAD

**Issue by vishal901** [realm/realm-java#3844]
after add,

 classpath "io.realm:realm-gradle-plugin:2.2.0"

i got error like,

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

please help me...

**Comment by Zhuinden** [comment]
> Compilation failed; see the compiler error output for details.

Can you add `--stacktrace` to the compiler options like specified [HERE](http://stackoverflow.com/a/37266244/2413303), and see the compiler error output?

**Comment by hardartcore** [comment]
Same thing happens to me. The error looks like:
```
error: cannot find symbol import io.realm.UserTagsRealmProxy
```
I know that it's build failure, but tried to clean the gradle cache, build cache, cleared Android Studio cache, nothing seems to work for now.

I use realm with parceler and both code generation fails, can't find why..that's why I am using 2.1.1 for now.

**Comment by Zhuinden** [comment]
Probably the same as https://github.com/realm/realm-java/issues/3827

**Comment by hardartcore** [comment]
@Zhuinden Thanks for the answer! In my case the order was the problem, never thought of that!

**Comment by beeender** [comment]
@hardartcore It seems you solved the problem, I am closing this issue now. Thanks!
