### ISSUE TITLE
which version should I use to upgrade from 0.88.2

### ISSUE THREAD

**Issue by monkeyfdude** [realm/realm-java#3957]
Currently, I use 0.88.2 in my app.

What would be the latest version I can upgrade to without the need of schema/data migrations?

At this point , I don't want to spend cycles on schema migrations and/or data migration to upgrade to recent versions.

Please help.

**Comment by Zhuinden** [comment]
```
0.89.0

Breaking changes

@PrimaryKey field value can now be null for String, Byte, Short, Integer, and Long types. Older Realms should be migrated, using RealmObjectSchema.setNullable(), or by adding the @Required annotation. (#2515).
```

Technically you won't need a migration as long as you put `@Required` on your `@PrimaryKey` fields.

-----------

Although you might run into pain because of how 0.89.0 changed Results iteration behavior inside transactions. If you've been meticulously and consistently using reverse iteration in all cases (`for(int i = results.size()-1; i >= 0; i--) {...`), then you won't have any issues though.

**Comment by monkeyfdude** [comment]
Thank you.
