### ISSUE TITLE
realmResults.sort() not working for api below 24 on Android

### ISSUE THREAD

**Issue by sreejithvs333** [realm/realm-java#3980]
` mRealmResults.sort(new Comparator<Note>() {
                    @Override
                    public int compare(Note o1, Note o2) {
                        return realmList.indexOf(o1.getId()) - realmList.indexOf(o2.getId());
                    }
                });`
I was trying to sort a RealmResults based on a RealmList.But this sort method is only available for api 24 (Android N).Is there any alternate for the same which supports lower api also?

**Comment by kneth** [comment]
@sreejithvs333 The API doesn't expose a method where you can specify your own comparison operator (see `sort` methods in https://realm.io/docs/java/2.2.1/api/io/realm/RealmResults.html). The sorting is done at Realm Core level, and implementing a comparison operator in Java would make sorting slow since we would have to call Java code from C++ at every comparison (worst case: O(N*log(N)) times).
