### ISSUE TITLE
Expose Generated files to realm in another module

### ISSUE THREAD

**Issue by Zeyad-37** [realm/realm-java#4012]
#### Goal
Expose Generated files to realm in another module

#### What do you want to achieve?
I implemented a lib that handles network and database (realm) access. Currently my lib is in another module than my sample app. Every model in the app needs 2 versions, a realm object and a regular POJO. I wrote an annotation processor to generate the equivalent realm class file from my annotated POJO. The problem is that my generated class is not part of the schema.

io.realm.exceptions.RealmException: class com.zeyad.usecases.app.presentation.models.AutoMap_UserModel is not part of the schema for this Realm.
I assume because its in the generated files directory. Is there way to expose the generated files to the schema ? thanks in advance.
#### Expected Results
I expect the LibraryModule to detect my generated files and expose them to my realm configuration
> 

#### Actual Results

>  io.realm.exceptions.RealmException: class com.zeyad.usecases.app.presentation.models.AutoMap_UserModel

#### Code

```java

@RealmModule(library = true, allClasses = true)
class LibraryModule {
}

// called in the application class
private void initializeRealm() {
        Realm.init(this);
        Realm.setDefaultConfiguration(new RealmConfiguration.Builder()
                .name("app.realm")
                .modules(Realm.getDefaultModule(), new LibraryModule())
                .rxFactory(new RealmObservableFactory())
                .deleteRealmIfMigrationNeeded()
                .build());
    }
```

#### Version of Realm and tooling
Realm version(s): 2.2.2

Realm sync feature enabled: no

Android Studio version: 2.2.3

Which Android version and device: moto g3

**Comment by zaki50** [comment]
Realm also uses annotation processor and I don't think there is a way to control the order of the processors.
And, I don't think (not for sure though) that classes generated by some processor is passed to other processors.

Why do you need POJOs in addition to Realm's model classes?
Is it impossible to use `RealmModel` interface instead of extending `RealmObject` class?

**Comment by Zeyad-37** [comment]
This my library: https://github.com/Zeyad-37/UseCases
So basically its a generic implementation of the domain & data layer in the clean architecture design. So, there is a model for the library (extends RealmObject) and another model for the presentation layer. I have not tried generating classes that implement RealmModels yet. But i think the problem will persist. So any ideas ??

**Comment by Zeyad-37** [comment]
So this there anyway to make this work ? i really need help guys

**Comment by Zeyad-37** [comment]
Any work around either ? please someone, answer me

**Comment by cmelchior** [comment]
Hi @Zeyad-37 ... Sorry for the late response. Things have been quite hectic the last week or so.

The problem is as @zaki50 mentioned that you cannot guarantee in which order annotation processors run, which causes the problems you see. In general, annotation processors will run in "steps", so if new files are being generated the AnnotationProcessor will run again with the generated files. Unfortunately Realm requires the full view of all model classes to function currently so it only run once (we abort it the 2nd time) and fixing this is non-trivial if not impossible. It is however something we want to look into as it would also enable more incremental builds, but it hasn't very high priority at the moment.

Right now it would probably require some hacky work-arounds. One idea could be:

1) Encapsulate your `Automap_*` files to a Java module. 
2) Instead of depending on it as a normal dependency from your `app` project, you should instead have a special gradle target that compiles it and copies the Java files to your app folders build directory. 
3) That way, when the app project compiles it will assume those files have been there all along and the Realm modules should be generated correctly.

**Comment by Zeyad-37** [comment]
Hey @cmelchior  thanks for your response. is it possible for all this process to be automated, so that on every build these steps would be executed ? because if not, then the whole thing is not worth it.

**Comment by kneth** [comment]
Currently we don't any automation.

**Comment by Zeyad-37** [comment]
well thanks anyways
