### ISSUE TITLE
I hope it be added to realm-docs

### ISSUE THREAD

**Issue by ZeroBrain** [realm/realm-java#4091]
In my experiences, I have got many thoughts How to use Realm.

so I hope this form be added to realm-docs.

```java
// RealmObject
class UserName extends RealmObject {
  public long id;
  public String name;
}

// Value Object
class User {
  public long id;
  public String name;
}

// use-case
realm.where(UserName.class).equals("id", 1).findAll().asObservable()
  .map(it -> new User(it.id, it.name))
  .subscribeOn(RealmSchedulers.instance())
  .observerOn(Schedulers.io())
  .doOnNext(it -> {/*blah*/})
  .observerOn(Schedulers.computation())
  .doOnNext(it -> {/*blah*/})
  .observerOn(Schedulers.newThread())
  .map(it -> {/*blah*/})
  .observerOn(AndroidSchedulers.mainThread())
  .subscribe(user -> {/*blah blah*/});
```

In my example, I divided `Persistence Object` for Database & `Value Object` for using
Many devs suffer from error of transfer of object among Multithreading.

for good-use-case, I think Devs know about it.

**Comment by Zhuinden** [comment]
well

1.) what is `RealmSchedulers.instance()`?
2.) the subscription is not stored, people might not unsubscribe it which will result in leaks
3.) this example throws out lazy-evaluation of RealmObjects, which is partly the reason why Realm is so fast

> Many devs suffer from error of transfer of object among Multithreading.

That's because they didn't read the documentation on how you shouldn't transfer the object among multi-threading, if you need to access the object on another thread, then query it from a Realm instance that belongs to that thread.

**Comment by cmelchior** [comment]
Hi @ZeroBrain 
Thanks for the input.

Since your example is primarily for working with RxJava, it is unlikely we will add it directly to the docs, since we do not want to add too much noise about 3rd party libs e.g in your case you are making a lot of trade-offs that might not be apparent like not using `copyFromRealm()` but a new class. Also you are using a custom schduler as well.

Not saying that it is an interesting discussion to have, it definitely is, but the docs are not the place for it. Tutorials or blog posts would probably fit better.

We do have an RxJava example in our example repo though, and it would perhaps make sense for you to adapt it to fit there instead? That would also make it much more clear how exactly it works. See e.g https://github.com/realm/realm-java/blob/master/examples/rxJavaExample/src/main/java/io/realm/examples/rxjava/gotchas/GotchasActivity.java

**Comment by cmelchior** [comment]
@ZeroBrain 
I'm closing this issue, but will be happy to discuss it as part of a PR against the RxJava example instead.
