### ISSUE TITLE
Access token should be refreshed before the current one expires

### ISSUE THREAD

**Issue by radu-tutueanu** [realm/realm-java#4094]
I tested the 2.3.0 release with RealmTasks for Android and ROS 1.0.0 with the expiration time set to 60s.

Right now, when the Android binding tries to send an UPLOAD message with and expired token, the server sends an error(`Sending: ERROR(error_code=202, message_size=20, try_again=0, session_ident=1)`) and closes the session.

The client then connects to the auth server and gets a new token.

**This behaviour is incorrect, the client should request an access token before the current access token expires and send a REFRESH message to the server, so that the session does not get disconnected.**

Not sure how much of this behaviour should be in object-store and how much in the binding.

cc @austinzheng @mrackwitz

**Comment by bdash** [comment]
The object store doesn't really have much in the way of event loop support, so setting a timer to refresh the token before it expires is currently up to the binding.

**Comment by nhachicha** [comment]
we should implement a timer that refresh regularly the `access_token` using the `refresh_token` like in [cocoa](https://github.com/realm/realm-cocoa/blob/fef9c95554bb52b9f48c59249bc38a14565fdc16/Realm/RLMSyncSessionRefreshHandle.mm#L63)

The refresh interval should be based on the [accessToken.tokenData.expires](https://github.com/realm/realm-cocoa/blob/fef9c95554bb52b9f48c59249bc38a14565fdc16/Realm/RLMSyncSessionRefreshHandle.mm#L111)

@radu-tutueanu what should happen when we try to refresh an `access_token` with an expired(revoked) `refreh_token` does the server return `203` or `202` ? I ask this because one error is fatal & one is recoverable from the client perspective

**Comment by radu-tutueanu** [comment]
It should be a `202`, but I am not sure. @kvap, what happens in this case?

**Comment by kvap** [comment]
The server does not care about the client's old token when it is a `bind` or `refresh` message. It checks the new token that the client provided in the message and returns `203 (bad_authentication)` if the new token has expired.

**Comment by nhachicha** [comment]
@kvap so `203` should force the user to log in again & try to acquire a new `refresh_token`?

**Comment by kvap** [comment]
Well, it does not necessarily mean that the user has to log in again. The situation when the client provides a **new** token which is already **expired**, is strange and should be avoided. Try increasing `refreshBuffer`, or generating a fresh token without re-login just in case the user is still authentic but the new token has expired.

**Comment by radu-tutueanu** [comment]
This is related https://github.com/realm/realm-cocoa/issues/4615  - the 1.0.1 ROS does not send data from other clients to a client with an expired access token.

**Comment by nhachicha** [comment]
blocked by https://github.com/realm/realm-java/issues/4141

**Comment by nhachicha** [comment]
fixed in https://github.com/realm/realm-java/pull/4214
