### ISSUE TITLE
Verify AsyncTask examples and docs

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4098]
After the slight change in timing regarding notifications being delivered ( https://github.com/realm/realm-java/issues/3427), we need to ensure that our docs and examples reflect best practise:

- [ ] Review docs, especially: https://realm.io/docs/java/latest/#strategies-when-dealing-with-android-framework-threads
- [ ] Threading example, especially: https://github.com/realm/realm-java/blob/master/examples/threadExample/src/main/java/io/realm/examples/threads/AsyncTaskFragment.java
- [ ] Intro example: https://github.com/realm/realm-java/blob/master/examples/introExample/src/main/java/io/realm/examples/intro/IntroExampleActivity.java#L58

**Comment by Zhuinden** [comment]
So apparently with Realm 3.1.1, the UI thread's RealmChangeListeners seem to be called **immediately** when the `realm.commitTransaction()` occurs on the background thread.

```
I/DOG: INSERTING DOG [com.zhuinden.rxrealm.path.dog.Dog@533bea24] [Thread[AsyncTask #1,5,main]]
I/DOG_: REALM CHANGE HAPPENED [Thread[main,5,main]]
I/DOG SUBSCRIPTION: Event happened for DOG table! [Thread[REALM_LOOPER,5,main]]
I/DOG: INSERTED DOG! [Thread[AsyncTask #1,5,main]]
I/DOG: DOG IS FOUND [Dog = [{id:5151},{name:HELLO!}]] [Thread[main,5,main]]
```

Aka: 

- Looper threads are all called "synchronously" (?) the moment you call `realm.commitTransaction()`

- By the time transaction ends, all RealmChangeListeners have been called

- By the time `onPostExecute()` is called, looper threads are already synchronized

This would mean that AsyncTask can no longer be desynchronized. I'm not sure since which version, but I'll go with Realm 3.1.x.

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
