### ISSUE TITLE
Predictive UI animations and local transactions

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#4245]
Without https://github.com/realm/realm-java/issues/4225 , user will still meets the un-synced list views when doing local commit.

Take below sequences for example:
list - 10 items
local commit delete the 1st item
touch event comes, since the list is always live, list.size() return 9 and did a refresh(), everything is up to date
fine grained notification comes, with deletion = [0], 0 should be the index in the old collection, but now, since the list has been updated already, it will delete the 1st in the updated view, which is wrong

The cocoa's solution about this: https://realm.io/docs/objc/latest/#interface-driven-writes

My thoughts, the current cocoa solution (suppress the next chosen listener) is still the best option:
1. It avoids the overhead to trigger all other listeners on the same thread, which is not necessary when other list view is not in the front
2. Not too complex to users, user just need to update the view according to what he changed in the local transaction, also, this gives user more flexibility for more complex animations (I assume there are requirements than what we can handle in the change set)

Another quick solutions can be delivered before #4225:
1. Exposing `Refresh()` to trigger the listeners when commit local transaction and educating user to use it. (So when we ship the listener suppressing, user could know they can use suppressing instead of refresh to make it better.)
2. Do `refresh()` in the `commitTransaction`. This requires less work from user side, but a) it creates overhead for cases which doesn't need to trigger listeners. b) when we deliver the listener suppress, the `refresh` in `commitTransaction` has to be removed which should be considered as a breaking change.

Examples here https://github.com/realm/realm-android-adapters/tree/mc/drag-drop-testing shows the problem, it is for drag & drop. But it could be applied to other cases that the view loose consistency with data.

**Comment by cmelchior** [comment]
I think the problem is a lot more complex to be honest (sorry for the wall of text)

### Problem

As describe here: https://github.com/realm/realm-cocoa/issues/3665, the fundamental issue is that sometimes you want to modify the UI immediately based on some user action.

This is problematic for Realm due to a number of reasons:

* It is not possible to alter data unless inside a write transaction. Write transactions are blocking across threads/processes and are potentially slow as they hit disk.

* This pattern does not conform to the normal reactive paradigm promoted by Realm where you just listen to changes from the One-Source-Of-Truth (The Database).

Some common cases:

* Drag and drop items in a list view.
* Add a new item to a list.
* Delete an item from a list.
* Change a property, e.g. make the item checked.

In all of these cases you would want to optimistically update the UI while the change is persisted in the background.

One fundamental issue with Android and Realms Notifications is based on how the Looper works. The looper is just an event queue that among other things also hold all touch input. This means that when Realm puts a notification on the queue, multiple touch input might be processed first. So unless all UI components are aware of the latest state of Realm data, crashes might happen when the touch input is processed (IndexOutOfBounds when scrolling Lists for example).

The interesting case to solve is this one:

```
[A, B, C, D]
```

1. UI thread swap element A and B (How without starting a block/slow transaction?).
2. How to notify the UI thread this happened?
3. What if a background thread swapped A with C right after A/B swapped place AND deleted D?

### Solutions

#### Solution 1: Suppress Notifications

The current solution chosen by Cocoa. Works by allowing developers to suppress notifications when making a commit. This means that users can suppress the next notification and make the nessassery modifications themselves:

```java
//Example of Drag-n-drop 
public void onDroped() {
    realm.beginTransaction();
    MyObject obj1 = results.get(1);
    MyObject obj10 = results.get(10);
    int oldIndex = obj1.getIndex();
    int newIndex = obj10.getIndex();
    obj1.setIndex(newIndex);
    obj10.setIndex(oldIndex);
    adapter.notifyItemMoved(1, 10);
    realm.commitTransaction(results); // suppress next notification to this query
}
```

* It requires (slow) write transactions on the UI thread.

* Risk causing ANR unless the user can ensure no writes happen in the background (impossible with Sync). Hard for most offline-first architectures.

* Suppressing a notification mean you might risk losing an unrelated update from a background thread. Causing the UI to still reflect the wrong data.

* Supported by the Object Store already.

**Some arguments against this:**

* We have gotten a lot of resistance from the community when suggesting writes on the UI thread. Proposing it again to solve this problem is not helpful.

* RMP will make this problem even worse, as people do not control when RMP begins a write transaction.

* Writes on the UI thread will cause all async queries to be converted to synchronous queries, possible without the user realizing it.

#### Solution 2: Force users to `refresh()`

`refresh()` was removed because it didn't work with our iterators. With 3.0 and the snapshot concept, it would now be possible to re-introduce it if we want to. Instead of suppressing notifications and manually tell the adapter what changed, we can use `refresh()`:

```java
//Example of Drag-n-drop 
public void onDroped() {
    realm.beginTransaction();
    MyObject obj1 = results.get(1);
    MyObject obj10 = results.get(10);
    int oldIndex = obj1.getIndex();
    int newIndex = obj10.getIndex();
    obj1.setIndex(newIndex);
    obj10.setIndex(oldIndex);
    realm.commitTransaction();
    realm.refresh(); // Will trigger notifications immediately and thus make sure the UI is in the
                        proper state before any other looper events are processed.
}
```

* Will still silently convert async queries to synchronous queries
* Still risking ANR's on the UI thread.
* User must remember to call refresh()
* The standard changelistener is responsible for all animations.

#### Solution 3: Trigger notifications on `commitTransaction()`

A variant of Suppress Notifications and manual `refresh`. Instead of suppressing notifications or forcing the user to manually call `refresh()` we trigger it inside Realm on `commitTransaction()`. On non-looper threads this will have no effect. On Looper threads it will trigger notifications immediately.

* This works without the user needing to do anything.
* The standard listeners are used.
* Async queries will still be converted silently.
* The problems with blocking writes are still there.

#### Solution 4: Allow in-memory modifications of RealmResults/RealmList

As an alternative to Async commits. What we really need is an option for manipulating `RealmResults/RealmList` temporarily and in-memory while changes are being saved in the background. How to accomplish this is very uncertain though and it will definitely lead to inconsistencies. Possible through a special UIRealmResults class that can store temporary changes until the next notification.

````java
MyObject obj1 = realmResults.first();
MyObject obj2 = realmResults.first();
obj1.setName("Foo");

// Can no longer compare objects, since the change would be local.
// It would break the general principal of our object graph always being consistent.
// But you could argue that predictive animations are already doing that.
obj1.equals(obj2) == false; 
````

#### Async commits

Core has (or had) support for an async transactions, which defer the final write to disk to a background thread which. This makes transactions a lot faster (effectively the speed of writing to memory), but introduces the risk of losing data if the app crashes after the commit but before the data was written to disk. Once a file is open all commits will either have to be Async or none of them.

Async commits can be combined with all 3 solutions, without the downside of risking ANR (or at least greatly reducing the risk), at the expense of potential data loss. The file will not be corrupt, but might just loose the last data. This might or might not be acceptable to users. 

* Async commits can be combined with all of the above to eliminate the overhead of transactions. It will still force queries to run synchronously. 
* Possible already supported by Core, but needs to be verified.

#### Priority commits

Instead of Async commits we can introduce two levels of transactions. This can also be mixed with all of the above solutions and will fix the problem that the UI thread might ANR because it is waiting for a background thread to complete its commit. Basically it means that if the UI thread starts a commit, it will automatically abort any other running commits.

* Will solve the ANR problem for the UI thread.
* Will not solve the problem that writing to disk is slow.
* All commits must be inside closures that can be restarted. The standard `realm.beginTransaction()/realm.commitTransaction()` will no longer be safe since any transaction might be aborted.
* Will require core changes.

### Conclusion

Short term I would probably prefer Solution 3 and trigger notifications on `commitTransaction()` on looper threads, while we are investigating other potential avenues for improving the situation.

**Comment by Zhuinden** [comment]
I'm not sure why `Solution 3: Trigger notifications on commitTransaction()` is not actually the standard behavior.

I mean, doesn't `realm.commitTransaction()` currently call the Realm and RealmObject change listeners already?

> Local commit triggers Realm global listener and RealmObject listener on current thread immediately instead of in the next event loop.

If `RealmResults` change listener is called *later* wouldn't that mean there is room for inconsistency if you use a Realm listener instead of a RealmResults listener?

**Comment by cmelchior** [comment]
I believe we trigger them on `beginTransaction()` (since the Realm is updated), not on `commitTransaction()`, but with the recent changes I might be mistaken :)

**Comment by Zhuinden** [comment]
@cmelchior yeah, I'm actually a bit out of the loop on it too. :disappointed: 

Technically there is a version bump with `realm.beginTransaction()`, which ought to call RealmChangeListeners, but I do not know if the results are swapped out with snapshots in order to make sure they don't change while the transaction modifies them on the UI thread (if done locally on the UI thread) or not. And I'm also not sure when any change that occurs after `beginTransaction()` and before `commitTransaction()` would result in a notification.

But I'm sure we'll figure it out :smile:

**Comment by beeender** [comment]
There was something wrong with my testing on https://github.com/realm/realm-android-adapters/tree/mc/drag-drop-testing , the `ViewHolder.getAdapterPosition()` could return `NO_POSITION ` when deletion happens.

I made a new drag & drop example: https://github.com/realm/realm-android-adapters/pull/96 . I actually working quite well with async transactions.

So:
`Solution 1: Suppress Notifications` doesn't seem to be necessary at all since even with async transaction, the drag & drop animation performs pretty well.

The solution 2 & 3 would solve the issues with synchronized transaction. I would prefer the `Realm.refresh()` (solution 2) now, since till now, the drag & drop is the only case i can see that need to trigger the collection's listener immediately. triggering the listener always creates too much overhead for other cases. So ideally, user should use async transaction for drag & drop. But there are cases user have to use synchronized transaction, he/she can just call `Realm.refresh()` to trigger. (especially we don't support `ThreadSafeReference` right now, sometimes async transaction could mean a lot of code.)

@realm/java please play with the example and let me know your thoughts. Thanks!

**Comment by cmelchior** [comment]
Thanks, I'll play around with it. I'm curious why you think that triggering the notifications always will create to much overhead? It feels very speculative to me, especially considering that notifications were triggered already on `beginTransaction()`, and you will want to do it anyway for the current RealmResults. So any excessive overhead should only come if you have many unrelated RealmResults floating around?

I do agree that `Realm.refresh()` is probably a method we want to add anyway, so probably a good place to start while we evaluate the situation.

**Comment by beeender** [comment]
> specially considering that notifications were triggered already on beginTransaction()

hmm, this would be a very valid reason for triggering notifications when commit.

**Comment by cmelchior** [comment]
I just played around with the drag-n-drop branch, and I'm not convinced using async transactions will work good enough. If you try dragging an item fast up and down a list of 10-15 items, it is very easy to see lag or missing move events (At least on my emulator and Nexus 7). If you switch to synchronous transactions and do a `beginTransactions()/cancelTransaction()` right after to trigger notifications, you can see a much smoother experience.

That aside, I have a sinking feeling that a Realm backed Adapter is actually a poor fit for this use case right now since recommending synchronous transactions are also really dangerous.  

Right now we cannot have 100% consistency with Realm data and smooth animations at the same time, and I'm not sure we are able to eliminate those problems completely.

**Comment by beeender** [comment]
I think core's async commits could actually fit here. I will do some testing with it.

**Comment by cmelchior** [comment]
Yes, that is my impression as well, but it will need testing. Also from my understanding, once you open a file with async commit enabled _all_ Realm instances need to use it, at least until fully closed again.

**Comment by beeender** [comment]
From the core's code, `do_async_commits` will be performed always if the `durability` is `Async`.
But what we need is just avoid flushing for this only local transaction commit. maybe something from core like `SharedGroup::commit_transaction(bool flush = false)` is good enough for this case?
