### ISSUE TITLE
Get result from database as a arraylist

### ISSUE THREAD

**Issue by Sachin-MTN** [realm/realm-java#4316]
Hi, Sorry if this is a noob question. Could you please explain how to convert result to ArrayList for following code:
RealmResults<label_type> result = realm.where(label_type.class)
        .findAll();
// Is below thing feasible
ArrayList<label_type> arrayList = result;

**Comment by beeender** [comment]
Why do you want to convert it to an `ArrayList`?

**Comment by Sachin-MTN** [comment]
I want to bind that list with my Spinner.

**Comment by beeender** [comment]
Since `RealmResults` implements the `List`, you can directly create a `ArrayAdapter` from it. But be noticed, `RealmResults` is a live collection, which means it could change when any data changes related to it. So you may want to call `ArrayAdapter.notifyDataSetChanged()` in `RealmResults` listener. See https://realm.io/docs/java/latest/#collection-notifications

Also stackoverflow.com is a better place to ask questions like this.

**Comment by Sachin-MTN** [comment]
@beeender Thanks, Let me check and will update you.

**Comment by Zhuinden** [comment]
Can't you use RealmBaseAdapter with spinner?

**Comment by kneth** [comment]
I am closing the issue. If you didn't solve the issue, I suggest that you ask at Stack Overflow since it has a much broader community.

**Comment by Zhuinden** [comment]
Yeah, please use `RealmBaseAdapter` with spinner, do not convert to ArrayList, if you need an unmanaged list of your objects then use `realm.copyFromRealm()` (but you do not need this for this usecase)
