### ISSUE TITLE
Multiple sync realms SyncUser synchronization problems.

### ISSUE THREAD

**Issue by gpulido** [realm/realm-java#4391]
Hello,
I have a problem and I don't know if it is a bug or just that I'm doing something wrong:

I want to manage several realms on the same aplication, and some of them will be Synched and some locally. In order to manage the several realms I created a local "management" realm that have just a class that stores and provides RealmConfigurations properly created.
This class looks like this:

```Java
public class RealmServer extends RealmObject
{
    private String databaseName;    
    private String serverIP;
    private String userJSON;
    private String userId;
    private String password;
    private boolean isLocal;

 public String getRealmUrl()
    {
        return "realm://" + serverIP + ":9080/~/"+ databaseName;
    }

    public String getAuthUrl()
    {
        return "http://" +serverIP + ":9080/auth";

    }
    public SyncCredentials getSyncCredentials()
    {
        return getSyncCredentials(false);
    }

    public SyncCredentials getSyncCredentials(boolean createUser)
    {
        return SyncCredentials.usernamePassword(userId, getPassword(), createUser);
    }

    public RealmConfiguration getConfiguration()
    {
        if (isLocal)
        {
            return new RealmConfiguration.Builder()                 
                    .name(databaseName)                 
                    .schemaVersion(1)
                    .deleteRealmIfMigrationNeeded()                  
                    .build();
        }
        else {

            String serverURL = getRealmUrl();
            SyncUser user = SyncUser.fromJson(getUserJSON());
            SyncConfiguration configuration = new SyncConfiguration.Builder(user, serverURL)                   
                    .schemaVersion(1)
                    .build();
            return configuration;

        }

}
```
The application only have one realm active at any time, it just change where the data is stored. To centralize the change of "Default realms" I created a helper that looks like this:

```Java
public class RealmHelper {

    private volatile static List<WeakReference<Callback>> callbacks = new CopyOnWriteArrayList<>();
    public static void setDefaultInstance(RealmConfiguration config) {
        SyncUser user = SyncUser.currentUser();
        if (user != null)
            user.logout();

        Realm.setDefaultConfiguration(config);
        for (WeakReference<Callback> c : callbacks) {
            Callback callback = c.get();
            if (callback != null)
                c.get().onDefaultInstanceChanged();
            else
                callbacks.remove(c);
        }
    }

    public static void closeDefaultInstance()
    {
        for (WeakReference<Callback> c : callbacks) {
            Callback callback = c.get();
            if (callback != null)
                c.get().onCloseDefaultInstance();
            else
                callbacks.remove(c);
        }

    }

    public static void registerCallback(Callback callback) {
        for (int i = 0; i< callbacks.size(); i++) {
            if (callbacks.get(i).get()!= null && callbacks.get(i).get().equals(callback)) {
                return;
            }
        }
        callbacks.add(new WeakReference<>(callback));
    }

    public static void unRegisterCallback(Callback callback) {
        for (int i = 0; i< callbacks.size(); i++) {
            if (callbacks.get(i).get()!= null && callbacks.get(i).get().equals(callback)) {
                callbacks.remove(i);
                return;
            }
        }
    }
}
```
When the user tries to login for the first time I show a login screen and I use the SyncUser.LoginAsync
and store the connection information, creating the RealmServer object if needed:

```Java
RealmServer realmServer = new RealmServer();
//RealmServer is then filled with the connection info.
 SyncUser.loginAsync(realmServer .getSyncCredentials(), realmServer.getAuthUrl(), new SyncUser.Callback() {
            @Override
            public void onSuccess(SyncUser user) {
              
                realmServer.setUserJSON(user.toJson());

                //Find if we already have one managedserver
                try(Realm realmManagement = ManagementDataModule.getManagementRealm()) {
                    RealmServer managedServer = ManagementDataModule.getManagedAnnotationServer(realmManagement, realmServer);
                    if (managedServer != null) {
                        realmServer.setUUID(managedServer.getUUID());
                    }
                    else
                        realmServer.setUUID(ManagementDataModule.UUIDGenerator.generate().toString());
                    realmManagement.beginTransaction();
                    realmManagement.copyToRealmOrUpdate(realmServer);
                    realmManagement.commitTransaction();
                }            
            }
}

```
I have the activities and fragment "registered" to this class and the normal implementation of the callback Interface is like this:

```Java

@Override
    public void onDefaultInstanceChanged() {
         if (realm!= null) {
            realm.close();
            realm = null;
        }
        realm = Realm.getDefaultInstance();
    }
```
When I want to switch between RealmServers I use the realmmanagement and execute this code:

```Java
  try (Realm realmManagement = ManagementDataModule.getManagementRealm()) {
            RealmServer server = RealmHelper.getByPrimaryKey(realmManagement, RealmServer.class, lastrealmServerUUID);
            RealmHelper.setDefaultInstance(as.getConfiguration());
        }
```
All seems to go fine until the listener executes:

```Java
realm = Realm.getDefaultInstance(),
```
Here the application throws a "Different realmconfiguration exception".
I have tracked out the error and the difference is raised on the equals of the ObjectServerUser, the last line is checking "realms.equals(syncUser.realms)" and they are different (realms has 1 element and syncUser.realms has 0"
Is the only line that returns false, so the objectserveruser is not the same and it is falling back and throwing a different realm configuration exception.

Also, after the crash, If I enter onto the application for the first time, the realm can be accesed without problem, so the error is only raised when I try to "reenter" into the realminstance on the same session.

I don't know if this is a bug or that I'm doing something that is not supported, or in the wrong way.

Would anyone could help me figuring this out?

Thank you!!
UPDATE: I forgot to tell that I'm using Real-java 3.0.0 and realm-object-server 1.3.0-294

**Comment by nhachicha** [comment]
Hi @gpulido 

`from/toJson` methods are used by `UserStore` internally to persist users, you shouldn't worries about doing the persistence manually, like in your case.

You should prefer a call to`UserStore#getCurrent` instead to find out if there's currently a valid user you can use. (If you have multiple users, you can call `get(identity)` where the identity is for example the email you used to login with, the first time). That may explain the discrepancy you see in the equals.

What I suggest to do is to create a `SyncConfiguration` inside `loginAsync` 
```java
SyncUser user = SyncUser.currentUser();
 if (user != null) {
// use it as default/current SyncUser
} else { // otherwise try to login a user 
SyncUser.loginAsync(...) {
           @Override
            public void onSuccess(SyncUser user) {
                SyncConfiguration defaultSyncConfig = new SyncConfiguration.Builder(user, ...).build();
                // now either switch to use it as a default Realm conf
                //        Realm.setDefaultConfiguration(defaultConfig);
                // or save it in a the App Context for example, so you can use it whenever you want 
                //        Realm.getInstance(MyApp.defaultSyncConfig);
            }
 }
}
```

**Comment by gpulido** [comment]
@nhachicha thanks for the help.

You suggest to store the SyncConfiguration instead of the syncUser. I'm confused as I though that If I can recreate the synconfiguration (in my example code I'm doing it using the getConfiguration() from the realmserver object) it would work. Do I have to store the specific instance of synconfiguration?

I guess htat with your aproximation, anytime the user wants to change the configuration has to login again into the new synched configuration. Am I right?

I suppose that the current user is only valid for the current "active" SyncConfiguration, and if I change of configuration I have to login again to obtain a valid syncuser, is it correct?

**Comment by nhachicha** [comment]
> I suppose that the current user is only valid for the current "active" SyncConfiguration

Yes we support one active user at the time. If you change the configuration (say you want to point to another URL) you need to `logout` the current user, then initiate  another login to obtain a new `SyncUser` that will be associated with the new `SyncConfiguration`. 

The reason we emphasis on using `currentUser` is because we keep refreshing the `access_token` of this user in the background, so even if you exit & come back to the application, chances are that the `token` associated with the user is still active, if not we try to refresh it again, without the need to invoke `login*` again. 

So as long as the `SyncUser` is valid you can cache/inject the `SyncConfiguration` associated with this user, to open the synched Realm. You don't need to keep recreating the `SyncConfiguration`. 

We have a complete example app [RealmTasks](https://github.com/realm/RealmTasks/tree/master/RealmTasks%20Android)

Hope this is clear 🙂

**Comment by gpulido** [comment]
Hello,
Thank you very much, I understand now what I was doing wrong.
As you pointed out, I can't store the user, and I have to enforce a new "login" anytime I change from server (url) to obtain a working user that will provide a correct configuration to be used as default configuration.

Just one question remain. If I have to "logout / login" to change from one server to another, the aplication can't be offline to switch between "servers" even when they had been synched by first time, and hence have an already local realm, is that right?

**Comment by nhachicha** [comment]
Before responding to your question, let me correct something, we do support multiple logged-in users, you can discriminate between them using the `identity`/email address as discussed before 
`SyncUser.all().get(userId)` so you don't have to `login`/`logout` 

Since you have an offline copy of the Realm, you can still get the `SyncUser` using `SyncUser.all().get(userId)` create a `SyncConfiguration` (or or use the one associated with the `SyncUser` you want to switch to) for this server (if it doesn't exist anymore) then open the Realm. You'll basically work on it offline, once the connection resume the Sync client will resume syncing your changes.

Note, if you do choose to `logout` a `SyncUser` all Realms associated with it, need to be closed, obviously this requires a new `login*` which gets you a new `SyncUser` that you can create a `SyncConfiguration` from.

**Comment by gpulido** [comment]
I think I get it, thank for your patience.
The "identity" for a user (that I can obtain from a user by user.getIdentity() is the same alongside login and logout of that user? (I have take a look to the identity and seems to be associated with the Token that I thought is sesion valid)
I'm asking, because if it is stable, I can "store" it instead of the "json" in my "realmserver" class to pair users with the associated configuration and search for the logged-in user (if any) for a given "realmserver". I want to be able to use different "realm configurations" at the same time, that is why I need to be able to pair an user with his configuration to set as defaultinstance in the entire app.

From what you said, I'm looking at a way to obtain a RealmConfiguration to be set as defaultinstance from a SyncUser, and the only way that I found is by building it through the RealmConfiguration.builder, is there any other way?

**Comment by nhachicha** [comment]
After you login (using your email address for example) the server will return an identity, that will identify your Realm uniquely, this is what replace the `~` in the server URL. So the identity should remain the same if you login again with the same user. 

`RealmConfiguration.builder` is indeed the only way, `RealmConfiguration` is immutable.

You could imagine a design where you keep a mapping between `emails` & SyncConfigurations

| email   | SyncConfiguraiton |
| ------ | ------------------- |
| bob   | syncConfBob            |
| alice  | syncConfAlice          |

As far as Realm is concerned these will be considered (and cached) as 2 different Realms on disk)
since they translate to 2 different URLs (remember the `~` that gets replaced with the `SyncUser` identity).

Now, if you want to use one as a default configuration, you need to make sure:

1 - You don't have a race condition where you try to change the `setDefaultConfiguration` concurrently 

2- I suggest you close all instance of the previous Realm, before switching to a new conf, to not fall into the trap of thinking you still work with `syncConfBob`, when actually you switched to `syncConfAlice`. Think of it as switching sessions you need to close/finish all work  with `syncConfBob` before setting `syncConfAlice` as a default conf & start using it.

To avoid this headaches, you can simply skip using `setDefaultInstance` & use `Realm.getInstance` instead, at least you're sure you're using the right configuration.

**Comment by gpulido** [comment]
@nhachicha I understand now. 
Thank you very much for all the support that the realm-team are providing to the developers.
Please close the issue. If in a future I have some more  problems, I will reopen it again.
