### ISSUE TITLE
I have such a problem.

### ISSUE THREAD

**Issue by Misayanice** [realm/realm-java#4438]
1.private List<T> list; T extends RealmObject.

2.private void  setNewDatas(List<T> list(){
     this.list=list;
     notifyDataSetChanged();
     Log.e("setNewDatas",this.list.get(0).isManaged());
}

3.private void  setDatas(List<T> list){
     list.addAll(list);
    notifyItemRangeInserted(position + getHeaderLayoutCount(), data.size());
     Log.e("setDatas",this.list.get(0).isManaged());
}

4. setNewDatas------->false;
    setDatas--------->true;
    why ? How can I make two are false?

**Comment by beeender** [comment]
How did you call ` setNewDatas`/`setDatas`?
Something like `myObj.setNewData(myList)`?
is the `myObj` here is a managed `RealmObject`?
is the `myList` here is a managed `RealmList`?

**Comment by Misayanice** [comment]
I know the problem. I would like to convert ResultResult<T> to list, use list.addAll () and then update the adapter. Can you do that?

**Comment by beeender** [comment]
why do you need to convert it to a non-managed list? Why don't you use `RealmResults` directly for adapter? Have you checked https://github.com/realm/realm-android-adapters

**Comment by Misayanice** [comment]
I used this. But there are some places that don't understand. For example, I have cached local data, I need to update to UI via RealmRecyclerviewAdapter

**Comment by Zhuinden** [comment]
> list.addAll(list);

This shouldn't happen at all

>  I would like to convert ResultResult to no-managed list, use list.addAll () and then update the adapter.

Why?

**Comment by Misayanice** [comment]
Online, page download and cache; offline, query paging, update UI. Can you give me some advice?

**Comment by Zhuinden** [comment]
With Realm, you don't need a caching layer because Realm objects are lazy evaluated.

With Realm, as it is a reactive data source, you don't need to manually update the list when you download something. You can just write that into Realm, and receive notifications about change. So what you need is a RealmChangeListener that will update your view in case of change ; this is something that RealmRecyclerViewAdapter does for you automatically. 

With Realm, you don't need to paginate your data because you only load the objects that you are currently showing on the screen, just by using RealmResults instead of unmanaged list. 

If your design demands that you paginate data, then it gets a bit tricky, because Realm has no reason to support limits, considering you can just limit which indices you get from the results.

**Comment by Misayanice** [comment]
thanks
