### ISSUE TITLE
Android Studio gives warning at threads/AsyncTaskFragment.java static field leaks

### ISSUE THREAD

**Issue by jkozh** [realm/realm-java#4580]
Android Studio gives warning at **ImportAsyncTask** - AsyncTask that imports Realm data while providing progress and returns the value of an  aggregate function in the end.
_Static Field Leaks
A static field will leak contexts.  Non-static inner classes have an implicit reference to their outer class. If that outer class is for example a Fragment or Activity, then this reference means that the long-running handler/loader/task will hold a reference to the activity which prevents it from getting garbage collected.  
Similarly, direct field references to activities and fragments from these longer running instances can cause leaks._
Is it a bug?

**Comment by Zhuinden** [comment]
I'm not a Realm person but as [ImportAsyncTask is a private non-static class](https://github.com/realm/realm-java/blob/master/examples/threadExample/src/main/java/io/realm/examples/threads/AsyncTaskFragment.java#L83) it can indeed leak the Activity like that.

**Comment by cmelchior** [comment]
It is correct that non-static classes hold a reference to their parent class, which is considered a leak if the inner class outlives the life of the outer class. If you cancel an AsyncTask correctly this shouldn't happen, but failing to do so will be a leak and could also crash the app since the view hierarchy would be gone. We should fix this example.

**Comment by zaki50** [comment]
threadExample has been fixed.
Thank you for your report.
