### ISSUE TITLE
Is there a way to conditional sort in two fields in Realm

### ISSUE THREAD

**Issue by RajendraSinghBohra** [realm/realm-java#4932]
I have a Rating Realm objects list as Follows:

```
public class RatingRealmObject extends RealmObject {

    @SerializedName("average")
    private float average;
    @SerializedName("raters")
    private int raters;

    public float getAverage() {
        return average;
    }

    public void setAverage(float average) {
        this.average = average;
    }

    public int getRaters() {
        return raters;
    }

    public void setRaters(int raters) {
        this.raters = raters;
    }
}

```
I want to sort the RealmResultList by descending order of average but the number of raters should be greater than or equal to 5. 
e.g. If we have two recipes as A and B. If A has average rating 4 and no. of raters are 8 and B has average rating 5 and no. of raters are 4 then after sort A should come first in the list. 

Any help how to make the condition in realm query.

**Comment by cmelchior** [comment]
Hi @RajendraSinghBohra Since you already asked this on Stack Overflow: https://stackoverflow.com/questions/44963174/is-there-a-way-to-conditional-sort-in-two-fields-in-realm?noredirect=1#comment76912123_44963174 I'll close this here, and let the discussion continue there.

Note, that we actively monitor Stack Overflow, so there is no reason to create an issue in both places.

**Comment by Zhuinden** [comment]
And it is a duplicate of https://github.com/realm/realm-java/issues/4301#issuecomment-303274243
