### ISSUE TITLE
Logout and opend Realm instance

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#4962]
From the `SyncUser.logout()` document:

```
     * @throws IllegalStateException if any Realms owned by this user is still open. They should be closed before
     * logging out.
```

But this is not true. It is checking `ObjectServerUser.sessions` to determine if there is any Realm instance is still opened. But `ObjectServerUser.sessions` is used anymore after we moved session logic to Object Store.

To solve this:
 - Do we really want to restrict user from logging out when Realm instance are still opened? From my opinion. it is very difficult if there are realm instance in the background in user's app. It the relevant Realm instance stops syncing, then it would be good enough for user.
- If we allow this, we need to ensure user won't open a Realm instance with the same name for a different user even in **multi-processes** environment !
- If we disallow this, then needs to also consider the corner case for `getInstanceAsync()`.

**Comment by nhachicha** [comment]
> Do we really want to restrict user from logging out when Realm instance are still opened? From my opinion. it is very difficult if there are realm instance in the background in user's app. It the relevant Realm instance stops syncing, then it would be good enough for user.

Here's the suggested implementation (tweaked a little bit from Cocoa, to take into account our RealmCache impl)

- `logout` will not require instances to be closed, it will be possible to reactivate the `SyncUser` by logging in again (either from the same thread or from a different thread). Re-activating the `SyncUser` will resume syncing.

> If we allow this, we need to ensure user won't open a Realm instance with the same name for a different user even in multi-processes environment !

- This use case will not happen, since a different `SyncUser` will have a different `identity` resulting on a different path on disk

**Comment by cmelchior** [comment]
Fixed by https://github.com/realm/realm-java/pull/5020
