### ISSUE TITLE
Verify Notifications for @LinkingObjects

### ISSUE THREAD

**Issue by bmeike** [realm/realm-java#5091]
The remains of issue #4323
- [ ] How live are `RealmResults` and how should `ChangeListeners` be triggered ?
- [ ] Consider how `CheckedRow` should handle BackLinks.

**Comment by bmeike** [comment]
Assuming ```
open class Person(
        @PrimaryKey var id: Long = -1,
        var name: String = "",
        @LinkingObjects("owner")
        val cats: RealmResults<Cat>? = null
) : RealmObject()
```

- Listeners registered like this: `person.addChangeListener(RealmChangeListener<E> listener)` are not called

**Comment by cmelchior** [comment]
Right now it is by design that listeners on `Person` are not triggered when a `Cat` references it. I'm dubious if these semantics make sense myself, but it would require substantial changes to support it.

It seems weird to me that the general changelistener for `cats` is triggered while the fine-grained isn't.  Someone with more knowledge about the internals would be needed to answer why this is the case.

**Comment by bmeike** [comment]
Great.  Will inquire.  Thanks.

**Comment by cmelchior** [comment]
Talking to .NET, it sounds like a bug that fine-grained collection notifications are not triggered for backlink RealmResults.

**Comment by beeender** [comment]
> Talking to .NET, it sounds like a bug that fine-grained collection notifications are not triggered for backlink RealmResults.

I don't think it is supported by Object Store?
