### ISSUE TITLE
Missing RealmLink for object

### ISSUE THREAD

**Issue by jennymolske** [realm/realm-java#5115]
Hello guys,

I've got a problem with Realm saving my entities to the database. My classes look like the following

```
public class Site extends RealmObject {

    @Required
    @PrimaryKey
    @Expose
    @SerializedName("siteUUID")
    private String SiteUUID;

    /**
     * Use this order to reproduce the error.
     * Declare {@link #Campaigns} before {@link #mCoupons}
     * the error doesn't occur.
     */

    @Expose
    @SerializedName("attributes")
    private RealmList<AttributeObject> mCoupons;

    @Expose
    @SerializedName("campaigns")
    private RealmList<Campaign> Campaigns;

    public Site() {}
}
```

```
public class AttributeObject extends RealmObject {

    @PrimaryKey
    @Required
    @Expose
    @SerializedName("attributesUUID")
    private String AttributeObjectUUID;

    @Expose
    @SerializedName("name")
    private String Name;

    @Expose
    @SerializedName("site")
    private Site site;
    public AttributeObject() {}
}
```

```
public class Campaign extends RealmObject {

    @Required
    @PrimaryKey
    @Expose
    @SerializedName("campaignUUID")
    private String CampaignUUID;

    @Expose
    @SerializedName("name")
    private String Name;

    @Expose
    @SerializedName("site")
    private Site site;

    public Campaign() {}
}
```

The response I receive from our api looks like the following:

```
{
  "siteUUID": "4d310340-1dd1-436b-ab05-723eaea9730f",
  "name": "Site1",
  "attributes": [
    {
      "attributesUUID": "270568ce-f31a-4343-9a53-ba32f3a0ded8",
      "name": "Attribut1",
      "site": {
        "siteUUID": "4d310340-1dd1-436b-ab05-723eaea9730f",
        "name": "Site1",
        "attributes": [],
        "campaigns": []
      }
    }
  ],
  "campaigns": [
    {
      "campaignUUID": "2c2890d0-b15b-497b-946d-affce01c0bfa",
      "name": "Campaign1",
      "site": {
          "siteUUID": "4d310340-1dd1-436b-ab05-723eaea9730f",
          "name": "Site1",
          "attributes": [],
          "campaigns": []
      }
    }
  ]
}
```
In my ActivityMain I load the json from the api and parse it to a Site-Object. Afterwards I would like to add it to my Realm db.

```
Site managedSite = (Site) realm.copyToRealmOrUpdate(object);
```
Now I expect my db to have one site and an Attribute object and a Campaign object which are both linked to the site. 
Current state:
The objects are all in the database but only the campaign is linked to the site. So I get
```
site.getCampaigns().size() = 1 (which is correct)
site.getAttributes().size() = 0 (which is not correct)
```
Maybe it is related to a previously mentioned error from me before (https://github.com/realm/realm-java/issues/4957) but this is another error, so I decided to open a new question.

Anybody got an idea how to solve the problem?

I've created an example project for reproducing the error:
https://drive.google.com/open?id=0B1aHkcAaWIA-c0NHM3RtWG1LYUU

**Comment by beeender** [comment]
This has a similar cause to #4957 , but it is kind of expected behaviour.

See the below image. When calling `coptyToRealmOrUpdate()`, in the object graph, there are actually two `Site` objects with the same PK. But as you can see, one of it has 0 coupon, but the other has 1. Since they both have the same PK, it is undefined which `mCoupons` will be kept as the last results -- they will be both written to the Realm and the one gets written last wins.

![image](https://user-images.githubusercontent.com/449296/29405775-8132cf3a-8371-11e7-90f1-5a874fdc1667.png)

**Comment by jennymolske** [comment]
Hmm okay, but our iOS app also uses Realm and the problem doesn't occur there. Does the both libraries work differently?

**Comment by beeender** [comment]
Not sure how do you parse json to objects graph in iOS, but I think if you parse the `Site` with same uuid to two different `Site` objects with different `mCoupons`, you will meet the similar problem on iOS sooner or later. this is kind of undefined behavior since it is difficult for Realm to figure out what do you want, do you want the `mCoupons` with one element to be saved? or do you want to clear the list?

**Comment by jennymolske** [comment]
Hm yeah okay. I will rethink our api structure then...I want the mCoupons object to be saved :-D
