### ISSUE TITLE
Client Reset triggered manually causes errors when Realm is re-opened

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5143]
If a ClientReset error is triggered, the Session Error handler is correctly triggered with the `ClientResetRequiredError`. However, if the user then decides to manually trigger the cleanup and re-open the Realm, it appears not to work and Object Store crashes with a exception saying the path doesn't exist:

```
io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/io.realm.test/cache/junit1002515331/3054f53f-2ae7-448d-8ff6-52876b6befa9/3054f53f-2ae7-448d-8ff6-52876b6befa9/myrealm.management': make_dir() failed: No such file or directory. (make_dir() failed: No such file or directory) (/data/data/io.realm.test/cache/junit1002515331/3054f53f-2ae7-448d-8ff6-52876b6befa9/3054f53f-2ae7-448d-8ff6-52876b6befa9/myrealm.management) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 256 Kind: ACCESS_ERROR.
at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
at io.realm.internal.SharedRealm.<init>(SharedRealm.java:190)
at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:243)
at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:206)
at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:303)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:289)
at io.realm.Realm.getInstance(Realm.java:320)
at io.realm.SessionTests$5$1.run(SessionTests.java:220)
```

The expected use case is that in an event of Client Reset should be possible to:
1) Close all open Realm instances
2) Manually trigger the `ClientResetRequiredError.executeClientReset()` method
3) Open the Realm again using the same configuration
4) Be able to download all changes using either `waitForInitialRemoteData` or `SyncSession.downloadAllServerChanges()`

**Comment by beeender** [comment]
It seems this requires all the Realm instances (including the one on the client thread) are closed. I think we need https://github.com/realm/realm-core/pull/2835 to make it possible.

**Comment by Zhuinden** [comment]
So I'm kinda wondering, if you have the limitation that all RealmModel classes are generated as `io.realm.____RealmProxy`, then how is it possible to have multiple versions of the same schema in your classpath so that you can save over from one Realm to the other?

Does this mean you need to add name `_v1` to your class name at the moment? :open_mouth:

**Comment by nhachicha** [comment]
@beeender this should be fixed in https://github.com/realm/realm-java/pull/5388. `executeClientReset` is checking the `getGlobalInstanceCount` to make sure you can't trigger manually the client reset if you still have open instances (obviously this logic need to be revisited when we support multi-process).

@Zhuinden the client reset may be triggered from the server side, even if the schema didn't change, if the schema changes you can still use the backup `RealmConfiguration` provided in the `((ClientResetRequiredError) error).getBackupRealmConfiguration()` to open the Realm dynamically to inspect and copy data to the new one.
