### ISSUE TITLE
Illegal Argument: Failure when converting to UTF-8; error_code = 7

### ISSUE THREAD

**Issue by Maxxan** [realm/realm-java#5148]
#### Actual Results

Some users fails to save text that they've written. Realm throws an error.

Stack trace
`java.lang.IllegalArgumentException: Illegal Argument: Failure when converting to UTF-8; error_code = 7;  0x0050 0x0069 0x0063 0x006b 0x0065 0x0064 0x0020 0x0075 0x0070 0x0020 0x0053 0x0061 0x006d 0x0061 0x006e 0x0074 0x0068 0x0061 0x0020 0x0066 0x006f 0x0072 0x0020 0x0074 0x0068 0x0065 0x0020 0x0053 0x0070 0x0065 0x0063 0x0069 0x0061 0x006c 0x0020 0x0054 0x0061 0x006c 0x006b 0x0020 0x0061 0x006e 0x0064 0x0020 0x0074 0x006f 0x006f 0x006b 0x0020 0x0068 0x0065 0x0072 0x0020 0x0068 0x006f 0x006d 0x0065 0x0020 0xd83d 0xde0a 0x0020 0x0028 0x0053 0x0068 0x0065 0x0020 0x0067 0x0061 0x0076 0x0065 0x0020 0x006d 0x0065 0x0020 0x0067 0x0061 0x0073 0x0020 0x006d 0x006f 0x006e 0x0065 0x0079 0x0020 0x0074 0x006f 0x0064 0x0061 0x0079 0x002e 0x0020 0x0053 0x006f 0x0020 0x006e 0x0069 0x0063 0x0065 0x0020 0xd83d 0x0029 0xd83d 0xde0d 0x0029 0x0020 0x0053 0x0068 0x0065 0x0020 0x0061 0x0073 0x006b 0x0065 0x0064 0x0020 0x0074 0x006f 0x0020 0x0063 0x006f 0x006d 0x0065 0x0020 0x0074 0x006f 0x0020 0x0074 0x0068 0x0065 0x0020 0x006d 0x0065 0x0065 0x0074 0x0069 0x006e 0x0067 0x0020 0x006e 0x0065 0x0078 0x0074 0x0020 0x0053 0x0075 0x006e 0x0064 0x0061 0x0079 0x0020 0x0074 0x006f 0x006f 0x0021 0x0020 0xd83d 0xde00 0x0020 0x0049 0x0020 0x0061 0x006d 0x0020 0x0070 0x0069 0x0063 0x006b 0x0069 0x006e 0x0067 0x0020 0x0068 0x0065 0x0072 0x0020 0x0075 0x0070 0x0020 0x0054 0x0068 0x0075 0x0072 0x0073 0x0064 0x0061 0x0079 0x0020 0x0061 0x0074 0x0020 0x0033 0x0070 0x006d 0x0020 0x0066 0x006f 0x0072 0x0020 0x0073 0x0074 0x0075 0x0064 0x0079 0x002f 0x0064 0x0069 0x006e 0x006e 0x0065 0x0072 0x002f 0x006d 0x0065 0x0065 0x0074 0x0069 0x006e 0x0067 0x0020 in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 308
	at io.realm.internal.UncheckedRow.nativeSetString(Native Method)
	at io.realm.internal.UncheckedRow.setString(UncheckedRow.java:242)
	at io.realm.VisitInfoRealmProxy.realmSet$info(VisitInfoRealmProxy.java:153)
	at io.realm.VisitInfoRealmProxy.copy(VisitInfoRealmProxy.java:750)
	at io.realm.VisitInfoRealmProxy.copyOrUpdate(VisitInfoRealmProxy.java:734)
	at io.realm.DefaultRealmModuleMediator.copyOrUpdate(DefaultRealmModuleMediator.java:456)
	at io.realm.Realm.copyOrUpdate(Realm.java:1599)
	at io.realm.Realm.copyToRealm(Realm.java:1011)`

#### Steps & Code to Reproduce

I don't have the text myself, I just see it in error logs

#### Version of Realm and tooling
Realm version(s): 3.5.0

Realm sync feature enabled: no

Android Studio version: 2.3.3

**Comment by Zhuinden** [comment]
Is your Realm encrypted? Do you have multiple processes? How many threads do you do writes on (shouldn't be a problem)?

**Comment by cmelchior** [comment]
In this case the error happens when inserting data into Realm, so most likely something outside made a wrong string. For example Java's string methods operate on chars instead of code points, so if you use `substring()` or `reverse()` you can risk it throwing errors like this if the string contained emojis.

**Comment by Maxxan** [comment]
Realm not encrypted, not multi processes, I've got a second thread where I read the old data and convert it to new realm database, and it's somewhere there this occurs for some, very few, users. So basically it reads the whole string, no substring or reverse.

**Comment by cmelchior** [comment]
Note that we have also seen this problem with custom keyboards

**Comment by cmelchior** [comment]
But if you say that all you do is reading data out from an old Realm and putting them into another. It  would be very surprising behavior. We have pretty strict safeguards around strings, so if something was wrong with the String when it left Realm we should have caught it there.

**Comment by Maxxan** [comment]
No, not an old realm, from an old file. I'm converting it to start using Realm.
I got hold of the string, and it does include some strange characters. Maybe I can just strip those..
Looks like` Picked up her �� (She gave me gas money �)��) ` So something strange there. Maybe a custom keyboard.

**Comment by cmelchior** [comment]
Perhaps, it can depend on a lot of things. Java is less strict about Strings not being correct UTF8, so it is entirely possible to create code in Java that throw Strings around that are not valid UTF8. 

We have to be really strict about it because the String might be read on multiple platforms that have different rules.

Stripping those chars might not be straight forward, but as a minimum, you probably need to try/catch this part of the code and then decide what to do if faulty strings are encountered.

**Comment by Maxxan** [comment]
I was thinking that I catch the error and use a regex to strip all non good characters and copy that to realm.

**Comment by Maxxan** [comment]
What is the best strategy for the future. Say that they use a keyboard that inserts wrong characters. Should I try to strip the characters from the string each time they save if an error occurs?

**Comment by cmelchior** [comment]
That really depends on your use case and how important it is to preserve the String, so that is up to you. 

Let's say a user inserts two emojis and only one is faulty. Finding the faulty one and removing them is very non-trivial and requires a lot of processing, especially if you allow none-English languages as well.

I see at least 3 ways of handling it.

1) Show an error to the user and say that it contains invalid characters asking them to rewrite it -> Hard to explain to users, but you will never modify the string after they inserted it

2) Strip unwanted chars automatically -> Might alter the meaning of messages.

3) Just abort the screen with "Error happened" and hope they don't enter the same string again.

Do note, that we have seen _very_ few reports of this UTF8 conversion failing, so it might not be worth implementing workarounds that take a long time.

**Comment by Maxxan** [comment]
Ok, thanks for your answer!
