### ISSUE TITLE
Wait until download all data from Realm Object Server.

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5219]
Realm 3.5.0, Android 4.3
My task
1. On the Realm Object Server has my Realm
2. When Android app is start I need to download all data from my Realm
3. Only after all data was success download I can work with my Realm (read/write).

Here my snippet code:

```
public class MyApplication extends Application {
    private static String REALM_URL = "realm://" + BuildConfig.ROS_IP + ":" + BuildConfig.ROS_PORT + "/~/" + BuildConfig.REALM_NAME;
    private static final String AUTH_URL = "http://" + BuildConfig.ROS_IP + ":" + BuildConfig.ROS_PORT + "/auth";
    private static SyncConfiguration syncConfiguration;

    private static final String TAG = MyApplication.class.getName();

    @Override
    public void onCreate() {
        super.onCreate();
        Realm.init(this);
        loginToRealm(BuildConfig.USER_NAME, BuildConfig.PASSWORD);
    }

    private void loginToRealm(final String userName, String password) {
        SyncUser.Callback callback = new SyncUser.Callback() {
            @Override
            public void onSuccess(SyncUser user) {
                syncConfiguration = getSyncConfiguration(user, REALM_URL);
                loadAllData();
            }

            @Override
            public void onError(ObjectServerError error) {

            }
        };
        SyncCredentials syncCredentials = SyncCredentials.usernamePassword(userName, password, false);
        SyncUser.loginAsync(syncCredentials, AUTH_URL, callback);
    }

    private SyncConfiguration getSyncConfiguration(SyncUser syncUser, String realmURL) {
        SyncConfiguration syncConfiguration = new SyncConfiguration.Builder(syncUser, realmURL)
                .waitForInitialRemoteData()
                .build();
        return syncConfiguration;
    }

    private void loadAllData() {
        Realm.getInstanceAsync(syncConfiguration, new Realm.Callback() {
            @Override
            public void onSuccess(Realm realm) {
                // IS HERE ALL DATA SUCCESS DOWNLOADED?
            }

            @Override
            public void onError(Throwable throwable) {
            }
        });
    }
}
```

Statements

1. To wait until all data was download from ROS I **MUST** use `waitForInitialRemoteData()`
2. When I use `waitForInitialRemoteData()` then for success download all data I **MUST** use method `Realm.getInstanceAsync()` (on method `loadAllData()` )
3. After call callback method `onSuccess(Realm realm)` in my custom method `loadAllData()` then ALL data was success downloaded from ROS. And now I can read/write to my Realm.
4. Every time when start my Android app I need call my method `loadAllData() ` to download (sync) all data from ROS

Is I'm right?

**Comment by Zhuinden** [comment]
Maybe https://stackoverflow.com/a/45716058/2413303 can help as well. But yes, what you said sounds correct.

**Comment by beeender** [comment]
> 1. To wait until all data was download from ROS I MUST use waitForInitialRemoteData()

Yes. But please notice the downloading only happens if there is no Realm instance (to the same realm file) opened. Otherwise it will just open the Realm without downloading.

> 2.  When I use waitForInitialRemoteData() then for success download all data I MUST use method Realm.getInstanceAsync() (on method loadAllData() )

Yes. unless you get the **FIRST** Realm instance on a bg thread .

> 3. After call callback method onSuccess(Realm realm) in my custom method loadAllData() then ALL data was success downloaded from ROS. And now I can read/write to my Realm.

Yes.

> 4. Every time when start my Android app I need call my method loadAllData() to download (sync) all data from ROS

Only if you want to fetch all server changes to the client. Otherwise you can just open the client Realm and continue to use the local Realm and let Realm handle the future data merging.

**Comment by lmdic** [comment]
OK. Thanks. 
One more statement:

1.  Login to ROS by user
2.  After success login I get `SyncUser`
3.  Store this `SyncUser `in Android `SharedPreferences `as Json (use method `syncUser.toJson()`)
4. Create `SyncConfiguration `from restored `SyncUser`

As result I'm not need to login every time when start Android application. I only  create `SyncConfiguration  `from `SyncUser`

Is it correct algorithm?

**Comment by beeender** [comment]
You don't have to save it by yourself. We have APIs for that.
See `UserStore` https://realm.io/docs/java/3.7.1/api/
`SyncManager.getUserStore()` https://realm.io/docs/java/3.7.1/api/io/realm/UserStore.html/SyncManager.html#getUserStore--

**Comment by lmdic** [comment]
OK. I will try use `SyncManager.getUserStore()` .
But the my statement is:
I can login ONLY once. Store user. And every time (when start Android application) only get user by `SyncManager.getUserStore()`. No need to login every time.

Is I'm right?

**Comment by beeender** [comment]
Yes!

You can just use `SyncUser.currentUser()` to get a login user when start. It will return null if no user is login. Also please notice it will throw if more than one users are logged in.

**Comment by cmelchior** [comment]
@lmdic I assume the above answered your question. If not, feel free to reopen

**Comment by dbskarl** [comment]
@beeender, a question with the above implementation, I'm also doing the same but it does not work as expected. I want to download all the server changes everytime I open the app. In that case, loadAllData() method will be called every app launch.

But if the app is not running and changes happened on the ROS, after launching the app, it will load the old copy/data and not the changes from the ROS. When it should download the new changes from the ROS since loadAllData() is getting called every app launch.

Did I misunderstand something?

**Comment by dbskarl** [comment]
@beeender a question with the above implementation, I'm also doing the same but it does not work as expected. I want to download all the server changes everytime I open the app. In that case, loadAllData() method will be called every app launch.

But if the app is not running and changes happened on the ROS, after launching the app, it will load the old copy/data and not the changes from the ROS. When it should download the new changes from the ROS since loadAllData() is getting called every app launch.

Did I misunderstand something?

**Comment by Zhuinden** [comment]
@dbskarl do you have `waitForInitialRemoteData()` on the sync configuration?

**Comment by dbskarl** [comment]
@Zhuinden yes it is.

**Comment by dbskarl** [comment]
@Zhuinden yes it is.
