### ISSUE TITLE
Duplicate Objects with same id with @primarykey

### ISSUE THREAD

**Issue by ViperAlpha** [realm/realm-java#5390]
#### Steps & Code to Reproduce

https://stackoverflow.com/questions/46606397/realmlist-addall-duplicating-object-with-same-primary-key

Realm version(s): 3.7.2

Realm sync feature enabled: yno

Android Studio version: 3.0 b7

Which Android version and device: Emulator/any

**Comment by Zhuinden** [comment]
Do you have a sample project that reproduces this?

**Comment by ViperAlpha** [comment]
[test.zip](https://github.com/realm/realm-java/files/1363595/test.zip)

**Comment by Zhuinden** [comment]
I have verified that you insert `1` instance of `Child` and that one managed instance of child appears `50` times in the `RealmList<Child>` because it was inserted into the RealmList 50 times.

![realm-list](https://user-images.githubusercontent.com/11718392/31295493-09264130-aadf-11e7-93d1-d135a958bc07.PNG)

This is because lists are *lists* and not sets, so they can contain the same object multiple times.

I've asked for a `RealmLinkedSet` before, maybe one day it'll happen, see [here](https://github.com/realm/realm-java/issues/759#issuecomment-305466428)

**Comment by ViperAlpha** [comment]
Understood. Thank you. I will try to find a way around that. Thanks for your help. If it isn't too much, could you have a look at [this question of mine?](https://stackoverflow.com/questions/46605834/realm-backlink-like-a-foreign-key)

**Comment by Zhuinden** [comment]
Already did, 5 hours ago. It's just that I have too many names.

**Comment by ViperAlpha** [comment]
oh, hahahah. thanks!
