### ISSUE TITLE
Question about `subscribeToObjects()`

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#5443]
I'm actually just curious, I'm reading the method signature of `subscribeToObjects()`, and it has this thing called a `PartialSyncCallback`. And its return type is `void`.

Internally, it does this

``` java
        SharedRealm.PartialSyncCallback internalCallback = new SharedRealm.PartialSyncCallback(className) {
            @Override
            public void onSuccess(io.realm.internal.Collection osResults) {
                RealmResults<E> results = new RealmResults<>(Realm.this, osResults, clazz);
                callback.onSuccess(results);
            }

            @Override
            public void onError(RealmException error) {
                callback.onError(error);
            }
        };

        sharedRealm.registerPartialSyncQuery(query, internalCallback);
```

But I'm surprised this is how the `RealmResults` are constructed, considering by default, `RealmResults` has an `isLoaded()` properly and are also evaluated asynchronously. 

So my question is, how come this is *not* synchronous method that returns a `RealmResults<T>` where `isLoaded == false`, then listen with RealmChangeListener? The query must be evaluated by OS?

I'm just curious, no rush :smile: 

-----

Also, does this mean you receive the `RealmResults<T>` in the callback, need to save it as a field as usual, and add a `RealmChangeListener` to it to receive updates? Based on the obj-c docs that say "use `addNotificationBlock()`, that is what I assume.

This means that if on ROS the results bound to the query change, the results will receive future updates made to the server?

#### Version of Realm and tooling
Realm version(s): 4.0.0

Realm sync feature enabled: yes

Android Studio version: irrelevant

Which Android version and device: irrelevant

**Comment by beeender** [comment]
`RealmResults.isLoaded()` is mainly to "simulate` the behavior of synced version of query APIs like `findAll()`, especially for the `RealmResults.load()` call. After we support the fine grained notifications, there is actually not too much difference between the `findAllAsync()` and `findAll()`. For both , the query will be evaluated on the caller thread only if it is needed, just like what realm-cocoa does.

hmm, but I think maybe for this case the `isLoaded` should be set to `true` when construct. Otherwise the listener could be triggered when `RealmResutls.load()` called which might not be expected.

> Also, does this mean you receive the RealmResults<T> in the callback, need to save it as a field as usual, and add a RealmChangeListener to it to receive updates? Based on the obj-c docs that say "use addNotificationBlock(), that is what I assume.

Yes, this needs to be documented. From user perspective, it is just like a normal `RealmResults`. A ref has to be maintained if he wants to get continuous notifications.

**Comment by Zhuinden** [comment]
The end of the story is https://github.com/realm/realm-mobile-platform/issues/279

Thanks!
