### ISSUE TITLE
Slowness on single item transaction, but with a huge number of other items

### ISSUE THREAD

**Issue by jpmcosta** [realm/realm-java#5519]
#### Goal

This is not the first time I'm opening issue about speed, but I think this case is probably hopeless. 

My goal would be to get some kind of advice on how should I be using Realm, in order to avoid or circumvent a slowness issue when creating executing single transactions on a single item, but there are a lot of other items.

#### Expected Results

Transactions on single items should be able to be handled in the UI thread.

#### Actual Results

Transactions on single items when there is a huge number of other items are slow and, apparently, shouldn't be handled in the UI thread.

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

I'm developing an Android application where I have a similar schema as the following example (but more complex):
```java
public class Project extends RealmObject {

    @PrimaryKey
    public Long id;

    public RealmList<Item> items;
}
```

```java
public class Item extends RealmObject {

    @PrimaryKey
    public long id;

    public boolean isActive = false;

    public RealmList<Note> notes;
}
```
```java
public class Note extends RealmObject {

    @PrimaryKey
    public long id;

    public String text;
}
```

Summary: `Project` has a list of `Items` who has a list of `Notes`.

I display the project's items in a `RecyclerView`, and I add a `RealmChangeListener` to the items `RealmList`, to listen for changes and call `notifyDataSetChanged()`.

My issue is as follows:

- each project can have a huge number of items, like 20K
- when there is a huge number of items in the project, simple transactions like a single `item.isActive = !item.isActive`, start taking too much time
- I stop being able to run this transactions in the UI thread, because of breaks
- the item won't update immediately if I make the transaction in the background

I made a test project to repeat the following transaction 1000 times and calculate the average time spent in transaction.
```java
realm.executeTransaction(new Realm.Transaction() {
    @Override
    public void execute(@NonNull Realm realm) {
        // item is always the same.
        item.isActive = !item.isActive;
    }
});
```

From my testing, these are the average times:

- first run:
  - 1 project
  - 1 item in project
  - 4 notes per item (4 in total)
  - **average time: 5.415ms**
- second run:
  - 1 project
  - 200 items in project
  - 4 notes per item (800 in total)
  - **average time: 6.219ms**
- third run:
  - 1 project
  - 20000 items in project
  - 4 notes per item (80000 in total)
  - **average time: 76.023ms** -> that's a noticeable break

The tests were run on a Xiaomi Mi A1 device.

This times are already not perfect, but my issues is even worse, since the Schema is naturally more complex. There are times when I'm spending 200ms to update a single item.

Should I just take an optimistic approach on actions (like when activating or deactivating an item), and use `executeTransactionAsync`?

#### Version of Realm and tooling
Realm version: 4.1.0

Which Android version and device: 7.1.2 and Xiaomi Mi A1

#### Follow-up on @cmelchior 
>**@cmelchior:** Do you have any RealmListeners registered when doing those transactions? Because most likely you are running into calculating changesets. This is normally only a problem when you have schemas with circular references, which does not appear to be the case?

Since I opened #4544, I knew about the issues regarding schemas with circular references, and while my Schema does have circular dependencies between 2 classes (`Project` has `Items`, and `Items` may have a `Project`), the first thing I tested for was removing those, but the result was the same (I was not testing with average times, so I can't tell for sure). However, as you can see in the Schema above, there are no circular dependencies and the results are not very good.

I do have 2 or 3 `RealmChangeListeners` in my main application. In the example above I only have one. I tried to remove it and the times are much better, indeed, like with a single item:
- fourth run:
  - 1 project
  - 20000 items in project
  - 4 notes per item (80000 in total)
  - no `RealmChangeListener` attached to `project.items`
  - **average time: 5.126ms**

So, should I remove all listeners before doing any transactions?

*Note: this issue was originally posted in https://forums.realm.io/t/slowness-on-single-item-transaction-but-with-a-huge-number-of-other-items/684*

**Comment by cmelchior** [comment]
I'm not that familiar with our changeset detection algorithm, but I'm guessing it might be traversing the entire item list even if only item was changed. @tgoyne would know the details.

**Comment by Zhuinden** [comment]
What is your query?

**Comment by jpmcosta** [comment]
@Zhuinden it's not a query. It's the items `RealmList` in `Project`.

**Comment by Zhuinden** [comment]
....oh. So no query at all.

This is too much down in core things for me to know what's up with it, sorry.

**Comment by jpmcosta** [comment]
@Zhuinden no problem at all! Much thanks for trying to help! 😄

**Comment by jpmcosta** [comment]
@tgoyne sorry to insist, but do you have any ideas, or is this a limitation that has no current workaround?

**Comment by tgoyne** [comment]
I made a [quick port of your described schema and test case to C++](https://gist.github.com/tgoyne/bf8f7aa95ef029f52fabe2114b746ab1), which as expected did spent almost all of the run time (after the initial setup) in the notifier worker. Profiling this gave the following result:

![image](https://user-images.githubusercontent.com/408944/32854214-bf027c80-c9f2-11e7-9a9b-b2172700a833.png)

For a List, we first check if any of the entries in the List were added, removed, or changed to point to different objects. Because no such changes were made, this doesn't even show up in the profile. We then go on to check if the objects within the list were modified. This check too is quite cheap (~3% of runtime). However, for the objects which weren't modified directly, we then go on to check if the objects they link to were modified (in this case, checking each Item to see if any of the Notes were changed). This part ends up taking a very long time due to that it initializes and then destroys 20k List accessor objects, which is a fairly heavyweight operation.

To work around this, you could potentially contort your schema to invert the direction of the relationship. If Note linked to the containing Item and Item had a `LinkingObjects<Note>` rather than a `RealmList<Note>`, the change checker would not check the Notes for modifications. If that doesn't work for your real schema, I'm not sure there's anything you can do on your end, but I'll take a stab at making this case perform a bit better.

**Comment by jpmcosta** [comment]
If I understood you correctly, a Schema like the following should fix the issue.

```java
public class Item extends RealmObject {

    @PrimaryKey
    public long id;

    public boolean isActive = false;

    @LinkingObjects("items")
    final public RealmResults<Note> notes = null;
}
```
```java
public class Note extends RealmObject {

    @PrimaryKey
    public long id;

    public String text;

    public RealmList<Item> items;
}
```
```java
public class Project extends RealmObject {

    @PrimaryKey
    public Long id;

    public RealmList<Item> items;
}
```
However, while it actually improves performance, it's still far from the 5ms average without listeners. Am I missing something?

- fifth run:
  - 1 project
  - 20000 items in project
  - 4 notes hold 1 item (80000 in total)
  - RealmChangeListener attached to project.items
  - **average time: 50.548ms** -> better than 76.023ms (third run), but still a UI break

Either way, thanks for your feedback!

**Comment by tgoyne** [comment]
Things inherently will be slower with listeners if you perform multiple write transactions in a row simply because there is more work to be done. However, do keep in mind that if each write transaction is performed in response to user input, realistically this won't actually block the UI thread. Most of the notification work is done on a background thread, and the UI thread is only blocked if another write transaction is begun before the background work is done. If the user taps a button in the UI which toggles isActive, then that first write transaction will block the UI thread for 5ms. If the user manages to tap another button within the next 75ms then that second write transaction will be delayed, but if they wait 100ms then the second write will also only take 5ms.

If you're performing multiple write transactions in response to a single user input then you may run into trouble, but there my advice would be to batch all of the modifications into a single write.

**Comment by jpmcosta** [comment]
>If the user taps a button in the UI which toggles isActive, then that first write transaction will block the UI thread for 5ms.
I don't understand how can this be, as my tests show the time it takes to execute the transaction, and that's blocking time. It should stop the UI thread for 50ms or 75ms, depending on the Schema, unless I use `executeTransactionAsync`. 

In my main application, I'm using the exact same transaction as in my example:
```java
realm.executeTransaction(new Realm.Transaction() {
    @Override
    public void execute(@NonNull Realm realm) {
        // item is always the same.
        item.isActive = !item.isActive;
    }
});
```
I'm getting longer a break. I would say it's more than 200ms, but my application schema is more complex. Maybe I'm also running into #4544.

I'm honestly a bit worried about this, since a list of 20K items it's very easy to reach within feasible time with low to medium usage. I predict most users will have 2 or 3 projects with that number of items within 8 to 12 months of usage, and the avid users a lot sooner.

**Comment by beeender** [comment]
@jpmcosta 
calling `realm.executeTransaction()` on UI thread will result the change set to be computed on UI thread immediately when the transaction committed. And this cannot be avoided because of consistency of refreshing the recycle view/ list view .

So unless you are using `executeTransactionAsync()` or committing transactions on a background thread through other ways, the changeset computing work cannot be done in the background thread like what @tgoyne said. 

Is there any reason you cannot use `executeTransactionAsync()`?

**Comment by jpmcosta** [comment]
@beeender no and I plan to use `executeTransactionAsync`. However, I was pushing the discussion a bit, because there are cases where I need to create objects, and on those cases I will still need to wait for them.

In addition to using `executeTransactionAsync` I will try to improve the Schema the best I can and try to manage the listeners better.

Thanks for all your help!

**Comment by beeender** [comment]
realm-cocoa has a method `commitWriteTransactionWithoutNotifying()`

https://realm.io/docs/objc/3.0.2/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(im)commitWriteTransactionWithoutNotifying:error:

> Commits all write operations in the current write transaction, without notifying specific notification blocks of the changes.
After saving the changes, all notification blocks registered on this specific RLMRealm instance are invoked synchronously. Notification blocks registered on other threads or on collections are scheduled to be invoked asynchronously.
You can skip notifiying specific notification blocks about the changes made in this write transaction by passing in their associated notification tokens. This is primarily useful when the write transaction is saving changes already made in the UI and you do not want to have the notification block attempt to re-apply the same changes.
The tokens passed to this method must be for notifications for this specific RLMRealm instance. Notifications for different threads cannot be skipped using this method.
This method can fail if there is insufficient disk space available to save the writes made, or due to unexpected i/o errors.

But it is actually for other purposes which is only useful for cocoa. I would think use async transaction will be a better solution for this case.

The possibility is we might be able to supply a similar API like `Realm.commitTransactionWithoutNotifyingListener(RealmChangeListener listener)` to skip the change set population once. But there are quite a lot of side effect of this API and it is quite confusing for users i think.

 I am closing this issue now. Hope the discussion cleared your doubt about this. Thanks a lot for the feedback!!
