### ISSUE TITLE
Can't use anyOf in Kotlin: Unresolved reference

### ISSUE THREAD

**Issue by Marcel50506** [realm/realm-java#5600]
#### Goal

Use anyOf instead of `in` in my Kotlin Android app

#### Actual Results

I get an IDE/buildtime error: 
Error:(251, 41) Unresolved reference: anyOf

#### Steps & Code to Reproduce

Tried to manually import, but couldn't find anyOf anywhere in the repo

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: no

Android Studio version: 3.0.1

**Comment by beeender** [comment]
See
https://github.com/realm/realm-java/issues/4092#issuecomment-348572935

use `oneOf`

**Comment by Marcel50506** [comment]
Thanks! In that case: update the docs and blogs ;)

**Comment by NeverwinterMoon** [comment]
Only today read https://realm.io/blog/realm-4-3-0-released-w-first-class-support-for-kotlin/ and decided to upgrade and ran into this problem (better late than never).

The aforementioned article is the first Google hit for "realm kotlin" search today, March 26, 2018. So, at least blogs haven't been fixed in over 4 months!

**Comment by MongoCaleb** [comment]
The query predicate in() now has a Kotlin alias named anyOf() as in is a keyword in Kotlin.

**Comment by i-schuetz** [comment]
`anyOf` doesn't work, 7.0.0 beta.

**Comment by Zhuinden** [comment]
Is it imported from `io.realm.kotlin.*`?

**Comment by cmelchior** [comment]
@i-schuetz In my experience, Android Studio isn't the quickest to find extension methods at times. So sometimes you need to add the import yourself.
