### ISSUE TITLE
Can't provide SSL root certificate for PermissionManager

### ISSUE THREAD

**Issue by joluet** [realm/realm-java#5607]
`PermissionManager.getInstance()` internally creates three `SyncConfiguration` instances to access different management and permission realms. However, there is no way to inject a ssl root certificate to be used when creating these `SyncConfigurations`. This can result in a `SSL handshake failed` error when trying to call `PermissionManager.makeOffer`.

I suggest to add the ability to inject a trusted root certificate when obtaining a `PermissionManager` instance. Similar to this: https://github.com/GulajavaMinistudio/realm-java/pull/33

**Comment by Zhuinden** [comment]
I'm mostly surprised these fields aren't inherited from some other configuration

**Comment by joluet** [comment]
True, that would be even better. :)

**Comment by cmelchior** [comment]
Good catch. You are correct this is currently not well supported. It would have been ideal if we could have inherited the SSL settings from the SyncConfiguration, but unfortunately, the `SyncUser` is created independently of the `SyncConfiguration`.

Since the same SSL settings are probably used across a User and his Realms, we should probably look into specifying SSL settings on the `SyncUser` and then let `PermissionManager` and any `SyncConfiguration` who uses that user inherit those settings as the default.

I don't have a good idea in mind at the top of my head though. @nhachicha what do you think?

**Comment by nhachicha** [comment]
Hi,
which Realm version are you using? note that since [4.2.0](https://github.com/realm/realm-java/blob/master/CHANGELOG.md#420-2017-11-17) we support certificate validation using Android keystore, so if your Root certificate is installed or part of the default trust root ca, then you don't need to provide the `trustedRootCA` option.

However, In the case of a Root CA that's not installed, you still need to provide the `trustedRootCA` option.

@cmelchior since the `SyncUser` is using the `Auth` service/endpoint in  ROS it will be weird to provide a configuration (SSL) which will act on the `Sync worker`/service.

An option could be to add the SSL conf as an option when obtaining the `PermissionManager` instance?

**Comment by Zhuinden** [comment]
Isn't SyncUser associated with a Realm that has a RealmConfiguration? Just wondering

**Comment by cmelchior** [comment]
Not really, you create Realms from a User, not the other way around.
