### ISSUE TITLE
Kotlin/Native

### ISSUE THREAD

**Issue by cl3m** [realm/realm-java#5727]
Is realm-kotlin on the roadmap? 

It would be great for (iOS/Android) cross-platform development and code sharing of business logic. Kotlin/Native support is still early but multi-platform is coming https://github.com/JetBrains/kotlin-native/pull/1102 and iOS support exists.

Otherwise, do you plan to do an abstraction over realm-java and realm-cocoa ?

**Comment by cmelchior** [comment]
Currently, there are no plans to develop a Kotlin/Native binding as that would require rewriting/duplicating a large portion of our internal code. 

More likely is that we will ship a full native C++ binding that can be used if you want to share logic between platforms. We already have a C++ API, but it isn't part of the public API and thus subject to change without any notice.

But lets keep this issue open in order to track interest.

**Comment by Zhuinden** [comment]
@cmelchior the Object Store?

**Comment by cmelchior** [comment]
Yes, that isn't a public API as such either. Just a bridge between the underlying Core API and the API exposed in Java/JavaScript/Swift/.NET

**Comment by cmelchior** [comment]
But yes, if you wanted you could write your shared logic in that, but we are not promising API stability there either.

**Comment by ChaitanyaDuse** [comment]
Interested!

**Comment by mhammouri98** [comment]
Interested!
And I may work on it !!

**Comment by kid1412621** [comment]
look forward

**Comment by egrigorieva** [comment]
Interested!

**Comment by achojoao** [comment]
Interested!

**Comment by lipa4** [comment]
Interested!

**Comment by Cassers** [comment]
If this existed, I would already have a fully functional multiplatform project, how not to be interested?

**Comment by MBoberski** [comment]
Sooo this maybe a dumn question but. If I have kotlin multiplatform project and in common module I write Realm logic I wont be able to use it in ios porject the same way as I use for example Retrofit?

**Comment by cmelchior** [comment]
Not right now. The Realm Java SDK would only work in the Android sourceset of the KMP project. 

We have however started on the initial steps for supporting Realm in the common parts of a KMP project, but we are still a bit away from releasing any details and possible release dates.

**Comment by sergiocasero** [comment]
Interested also! :)

**Comment by sdeff** [comment]
> Not right now. The Realm Java SDK would only work in the Android sourceset of the KMP project. 
> 
> 
> 
> We have however started on the initial steps for supporting Realm in the common parts of a KMP project, but we are still a bit away from releasing any details and possible release dates.

This sounds great, I’m looking forward to any news regarding Realm and Kotlin Multiplatform!

**Comment by cmelchior** [comment]
> Is realm-kotlin on the roadmap?

Realm Kotlin is indeed on our roadmap and we have been working on it for a while. It is going to be a Kotlin SDK targeting Kotlin Multiplatform and Android. It can be found in the new Realm Kotlin repo we just open-sourced: https://github.com/realm/realm-kotlin

The project is still in very early stages, so nothing has been finalized yet. But we encourage any feedback you might have regarding the API or use cases in the new repo.

I'll close the issue here and redirect to https://github.com/realm/realm-kotlin for more information.
