### ISSUE TITLE
Batch delete

### ISSUE THREAD

**Issue by eygraber** [realm/realm-java#5769]
#### Goal

If I have an unmanaged `List<RealmModel>`, I would like to delete them all in one shot

#### Expected Results

`RealmObject.deleteFromRealm(realm.copyFromRealm(list))`

#### Actual Results

`realm.copyFromRealm(list).forEach { RealmObject.deleteFromRealm(it) }`

**Comment by Zhuinden** [comment]
Hmm I'd figure you can only batch deleted managed RealmResults and managed RealmLists, sooo... I'd think you might even need to look up the managed RealmObject by primary key, first, for `realmObject.deleteFromRealm()` to work.

**Comment by cmelchior** [comment]
`copyFromRealm` return unmanaged copies of objects, which cannot be deleted from the Realm since they are not in it.

Like @Zhuinden says. If you have a list of unmanaged objects, the only way to delete the equivalent managed objects in Realm is if these objects have a primary key you can search for.

Something like:

```
val list: List = getList()
realm.executeTransaction(r -> {
  list.forEach {
    realm.where<Foo>().equalTo("id", it.id).findFirst()?.deleteFromRealm()
  }
}
```

**Comment by eygraber** [comment]
Ah my bad. Completely spazzed on `copyFromRealm`.
