### ISSUE TITLE
"The Realm is already in a write transaction" with unrelated `executeTransaction` calls

### ISSUE THREAD

**Issue by jpmcosta** [realm/realm-java#5785]
#### Goal

To report a potential issue between transactions and listener notifications.

#### Expected Results

To have multiple, unrelated, `executeTransaction` calls in one thread (like the UI thread), without the risk of crashing due to Realm already being writing a transaction.

#### Actual Results

I have 2 unrelated `executeTransaction` calls in the same thread and, due to a third transaction running in the background, they crash.

#### Steps & Code to Reproduce

I created a simplified Android project to reproduce the issue (please disregard the concepts behind the objects in the project):
https://github.com/jpmcosta/RealmTestProject/tree/e14ba555a6fe4c7a520833a0a42b1fe357647275

The idea of the test project:
- the objects: 1x`App`, 1x`Session`, and 10x`Item`
- `App` and `Session` are related to one another, but unrelated to `Item`
- when `App` is updated, it updates `Session`
- `App` is being updated in the background, every 100ms, which triggers a listener to update `Session`
- you can click on items in a list, to toggle their `isBookmarked` property
- if you click a few times, eventually the application will crash, because it will try to update `Session` after starting a transaction to update an item. It will call `notifyChangeListeners` after `beginTransaction` -> this is the issue

#### Version of Realm
Realm version(s): 4.3.4

**Comment by Zhuinden** [comment]
Hmm.. I wonder if this is a bug in [object store](https://github.com/realm/realm-object-store/blob/bb559df9237ece49f9c889993f7c1aff619b48f9/src/impl/realm_coordinator.cpp#L426-L432).

Nice repro-case!

**Comment by cmelchior** [comment]
Thanks a lot @jpmcosta. I managed to reproduce the crash using your app and I'm looking into it now.

**Comment by cmelchior** [comment]
After looking at the code, it looks like it is working as intended, but the error is only triggered when you call `beginTransaction()` on the main thread and there is a pending update from the IntentService.

In that case, the call to `beginTransaction()` will notice the Realm has changed, and notify all listeners, which, in turn, attempts to start a transaction, which crashes with the error you are seeing.

There are two workarounds currently:

1) Either do all writes on the main thread as `executeTransactionAsync`
2) Add a `realm.isInTransaction()` check inside your listeners.

A little more background:

Due to Realms MVCC architecture, we can have multiple versions of your data live at the same time. This is what allows you work on both the UI thread and the IntentService thread at the same time, but on the other hand, we also have ACID guarantees. This is especially important in the context of writes, because in order to be consistent we are forced to only perform writes on the _latest_ version. You cannot write to older versions of Realm (actually you can using our merge algorithm, but longer story :) )

Specifically, this means that while a thread is allowed to _see_ old data, as soon as a write transaction is started, we must fast-forward the version on the thread to the latest, but doing that also requires notifying all listeners as otherwise, any UI component that uses Realm data might try to access, now, invalid data. We have e.g. seen a number of crashes in RecyclerView if listeners were not notified immediately after the version changed. 

It is for this reason that we trigger listeners on the current thread in all the following cases:
- Looper event sent from a Realm instance on another thread (this is e.g. what all our `*Async` methods does)
- If you call `Realm.refresh()`
- If you call `Realm.beginTransaction()`
- If you call `Realm.commitTransaction()`

**Comment by jpmcosta** [comment]
I was afraid that was the case and I understand.
It's just not ideal, since I will now have to make sure no `RealmChangeListener` ever triggers a transaction, even if it doesn't directly call it.
Well, I thought it was worth the shot posting it here, as it could be a bug.
Thanks. :)

**Comment by Zhuinden** [comment]
> If you call Realm.beginTransaction()

Yep, this is tricky because it happens if the current thread Realm is outdated, which is *not always*.

**Comment by nolanamy** [comment]
Why doesn't Realm notify listeners _before_ starting the transaction, in the case of `beginTransaction()`? And in the case of `commitTransaction()`, after closing it?

**Comment by cmelchior** [comment]
Because then you have a race condition. If you don't trigger notifications inside the transaction, another transaction might trigger first creating even more changes that needs to trigger notifications.

**Comment by Zhuinden** [comment]
@nolanamy because the Realm is updated *by opening the write transaction*. So it gets refreshed. Refreshing updates version, so it calls change listeners.

**Comment by nolanamy** [comment]
What if I called `Realm.refresh()` before calling `Realm.beginTransaction()`? Would that not cause the refresh, triggering a version update, and in turn listener notifications? And then those listeners could freely start their own transactions, no?

**Comment by nolanamy** [comment]
I suppose until I open the original transaction, there's always an opportunity for another thread to make a change... this is the race condition @cmelchior is talking about?

**Comment by nolanamy** [comment]
Really bad because there could be a long-running write transaction on another thread that this transaction would have to wait for? So you'd recommend @cmelchior's workaround number 1?

> do all writes on the main thread as executeTransactionAsync

In practice, doing synchronous write transactions from the UI thread doesn't seem to have been an issue, but I'm not sure I'd know if it were...

**Comment by Zhuinden** [comment]
Long-running background transactions will cause ANR.

Ran into it. The mistake was on our part, of course.

**Comment by Zhuinden** [comment]
When I was inserting ~4000 items per transaction, that could count as a "slow transaction". :smile:
