### ISSUE TITLE
Android ToDo App usability is bad

### ISSUE THREAD

**Issue by jedelbo** [realm/realm-java#5804]
This issue relates to `https://docs.realm.io/cloud/android-demo-app`.

The prerequisites paragraph should come first. You should install Android Studio also when you select the quick start.

## Quick Start:
Downloading and building the app goes relatively easy.
The problems start when you run the app and is presented with the nickname prompt. What to do? I tried to enter a name and an error occurred. It turned out that the problem was that I included "https://" in the URL of the cloud instance. Separate issue created.

## The not so quick start

I find that this approach to construct the application is way too complicated. I gave up half way through. I felt I had lost the overview of where I was in the process, I was not sure if I had done it correctly and I did not know how long time it would take me to complete the task.

A specific problem is that when it in step 5 says "Now compile and run the application ", the application cannot run. 

Another problem is that if you copy the code from the web page, you will get some illegal characters into the source code. They appear when you have a blank line.

## Conclusion
Overall result: no success experience after 2 hours work. 
If you want to have a step-by-step instruction, then you should develop the application in a way that you have a running example after each step. And you should learn something about how to use Realm is each step.

**Comment by Zhuinden** [comment]
> I find that this approach to construct the application is way too complicated. 

That's just how Android apps are built. From Android Studio projects that you import, and then Gradle figures out what to do. When you connect an Android device, then ADB runs, and AS lets you install things on the device; otherwise you have to setup an emulator.

I guess the tricky part might be that you have to clone the Github repo, and open only 1 project at a time, or so I'd think.

----

But I do admit, when I was using `Realm-Tasks` it was ***super weird*** to use! Mostly because it was a direct port from iOS and I guess the app `Clear` (the todo app it was based on) only makes sense to iPhone users.

**Comment by jedelbo** [comment]
I think you should start off by cloning a super simple application without any realm related code in it and then gradually add functionality - like done in the Cocoa example.

**Comment by nhachicha** [comment]
Fixed. added step by step tags as checkpoints for the first sync tutorial
