### ISSUE TITLE
SIGSEGV error - RealmFinalizer thread

### ISSUE THREAD

**Issue by jainpiyush19** [realm/realm-java#5825]
Hi
Got this error log.
A/libc: Fatal signal 11 (SIGSEGV) at 0x301a316c (code=1), thread 24349 (RealmFinalizing)

**Comment by cmelchior** [comment]
Hi @piyushzomato 
Thank you for reporting this, but please fill out the template as otherwise we don't have enough information to work with.

**Comment by piyushzomato** [comment]
<!---
#### Steps & Code to Reproduce
I don't have any steps to reproduce since it happened randomly.

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: No

Android Studio version: 3.0.1

Which Android version : Android 4.4.4
Which Android device : Posiflex POS machine.

**Comment by piyushzomato** [comment]
#### Steps & Code to Reproduce
I don't have any steps to reproduce since it happened randomly.

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: No

Android Studio version: 3.0.1

Which Android version : Android 4.4.4
Which Android device : Posiflex POS machine.

**Comment by cmelchior** [comment]
Thanks. Unfortunately, there isn't much to go from.
It looks like you are running Android on some custom hardware and, I assume, a customized operating system as well, so without some more detailed logs about what is wrong it is a wild guess.

How often does it crash?

**Comment by rorbech** [comment]
Closing as duplicate #5578, which has been fixed a while ago (https://github.com/realm/realm-java/issues/5578#issuecomment-552416649). 

Please update if you have newer observations of this.
