### ISSUE TITLE
findFirstAsync doesn't create a subscription

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5938]
From https://realmio.slack.com/files/U03426T1Y/FAMG06LNT/Findings_from_implementing_Partial_Sync_in_an_app

> FindFirstAsync() doesn't  create a subscription. 

I haven't checked but I assume the same is the case for `findFirst()`

**Comment by nhachicha** [comment]
I can confirm the behaviour for `findFirstAsync` however `findFirst` should behave like `findAll` where we don't create a subscription.

**Comment by nhachicha** [comment]
We can make `findFirstAsync` add a subscription by modifying the `PendingRow` as follow  
```Java
    public PendingRow(OsSharedRealm sharedRealm, TableQuery query, @Nullable SortDescriptor sortDescriptor,
                      final boolean returnCheckedRow) {
        this.sharedRealm = sharedRealm;
        if (sharedRealm.isPartial()) {
            pendingOsResults = SubscriptionAwareOsResults.createFromQuery(sharedRealm, query, sortDescriptor, null, SubscriptionAction.ANONYMOUS_SUBSCRIPTION.getName());    
        } else {
            pendingOsResults = OsResults.createFromQuery(sharedRealm, query, sortDescriptor, null);  
        }
// ...
```

However, this will have a surprising behaviour for the user, since the listener you'll attach to the pending row will not be triggered once the data is downloaded. This is the same behaviour we have with non Sync `findFirstAsync`, e.g:
```Java
Realm realm = looperThread.getRealm();

        Dog dog = realm.where(Dog.class).equalTo("name", "Fido").findFirstAsync();
        dog.addChangeListener((Dog d) -> {
            // this will not be triggered with a valid Dog
        });

        looperThread.postRunnableDelayed(new Runnable() {
            @Override
            public void run() {
                realm.beginTransaction();
                realm.insert(new Dog("Fido"));
                realm.commitTransaction();        
            }
        }, 1000);        

```
This happens because the listener was registered on an invalid row, since the completed async query didn't return any results. (Note same use case works with `RealmResutls` since the listener is attached to a query/_tableview_ not a row/pointer).

Further more, when attaching a listerner in the context of query based sync, the listener will not be triggered because:
- The reference Realm doesn't fulfill the query 
- Even if it fulfills the query & download the date, the listener will not be triggered (since it's attached to an invalid row, this is the same use case expalined above with non sync Realm).

Another argument for not allwoing `findFirstAsync` to register a subscription is the subscirption behaviour, ROS will run the query & sync back all data that fulfills the query locally (which has the same effect as using `findAll`).

I sugegsted we document this, & advise the use of `findAllAsync` which will create the same subscription as `findFirstAsync`, but gives you working callbacks to check the subscription status, nothing prevents you from using `findFirstAsyc` locally (on offline data) once you're sure the data is there

**Comment by Zhuinden** [comment]
You have so much technical debt from not using a `RealmOptional<T>` of sorts for `findFirst` and `findFirstAsync`, and this is kinda one of them. 😕
