### ISSUE TITLE
realm.copyToRealm() - how set null value?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#6260]
in my Android project I use:

`currentLocalMerchant.setName(realm.copyToRealm(findIncomingMerchantName));`

And this code success copy `findIncomingMerchantName` to Realm. Nice.
`currentLocalMerchant` , `findIncomingMerchantName ` are  a `RealmObject`

Except one case. When `findIncomingMerchantName` is null I get the next error:

```
FATAL EXCEPTION: main
Process: com.loyalix.android.customer.debug, PID: 22548
java.lang.IllegalArgumentException: Null objects cannot be copied into Realm.
	at io.realm.Realm.checkNotNullObject(Realm.java:1603)
	at io.realm.Realm.copyToRealm(Realm.java:992)
	at com.loyalix.android.customer.service.MerchantService$1.execute(MerchantService.java:102)
	at io.realm.Realm.executeTransaction(Realm.java:1393)
	at myproject.MerchantService.updateMerchantList(MerchantService.java:68)
	at myprojectSyncService$1.onSuccess(SyncService.java:49)

```

How I can fix this?

**Comment by Zhuinden** [comment]
`currentLocalMerchant.setName(findIncomingMerchantName == null ? null : realm.copyToRealm(findIncomingMerchantName));`

**Comment by bmunkholm** [comment]
@lmdic 
As mentioned in the issue template, we use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Swift Forum](https://forums.realm.io/c/swift) or [Obj-C Forum](https://forums.realm.io/c/objc).

If you have a feature request or you think you have a bug, please fill out the template available when you choose your issue here: https://github.com/realm/realm-java/issues/new/choose

Thanks for your help!
