### ISSUE TITLE
faster indexOf and better support for random accessing realm list

### ISSUE THREAD

**Issue by MkazemAkhgary** [realm/realm-java#6360]
It would be nice if we could simply do something like this

```java
int index = realmList.where().equalTo(Model.ID, id).findIndex(); // O(log N) ???
Model model = realmList.get(index); // O(1)
if(shouldDelete) realmList.deleteFromRealm(index); // O(???)
```

Instead of

```java
Model model = realmList.where().equalTo(Model.ID, id).findFirst();
if(shouldDelete) {
    int index = realmList.indexOf(model); // O(N)
    realmList.deleteFromRealm(index);
}
```
  
I think this can be supported relatively easy. since indexOf is supported anyway.

---

Also one question. will calling `deleteFromRealm` on `RealmResults` also delete the entry from its source i.e `RealmList`? or will the entry in `RealmList` just become invalid?

**Comment by cmelchior** [comment]
@MkazemAkhgary `realmList.where().equalTo(Model.ID, id).findIndex()` would still be `O(n)` but we could move the entire searching part to C++ which would provide a speedup. However, it wouldn't be something that has a high priority.

In your case, if it is just because you want to delete an element from a list, then you can just delete the element and it will remove itself from the list automatically. This is because `RealmList<Model>`is not allowed to contain `null` values, so it will automatically resize.

In your case, this should work as well:
```
Model model = realmList.where().equalTo(Model.ID, id).findFirst();
if (shouldDelete && model != null) {
  model.deleteFromRealm();
}
```

**Comment by MkazemAkhgary** [comment]
@cmelchior wow, that simple? How is that possible? does RealmObject have reference to all realm list its being stored? or does realm list automatically handle null values and remove null values when null values are later encountered?

I'm starting to like realm pretty much! :)

**Comment by cmelchior** [comment]
References in Realm are, unlike SQLite, an integral part of how the database work and they work both ways. So it is very fast and efficient to remove it from all places it is being referenced when it is deleted.

**Comment by MkazemAkhgary** [comment]
that's good to know, thank you.
