### ISSUE TITLE
RealmProcessor should ignore methods that have the @Ignore annotation

### ISSUE THREAD

**Issue by demonar** [realm/realm-java#637]
hey guys, i'm trying to add some methods that allow to populate data from a class that comes from a service. Both, the realm and the service class have the same parameters, when i create the method on the realm class adding the @Ignore annotation i still get error: Only getters and setters should be defined in model classes.
The method looks like this:

@Ignore
    public void addDataFromServiceData(ServiceData data) {
        setStringVariable(data.stringVariable);
        setDateVariable(parseDate(data.dateVariable));
    }

I'm still using the setters to populate the data to avoid any issues with the changes made in the class.

**Comment by mpost** [comment]
I also see the danger of forgetting to use the accessor. None the less, the current programming model is quite clumsy.

I was trying to add a field with an enum which is not supported. Next i modeled the enum entries with ints, which works, but i wasn't able to add a simple .isFlagSet(flagToCheck) method on the class since it can not be ignored. Having an external helper class just to do the bit check feels rather redundant.

**Comment by SrMouraSilva** [comment]
Methods like toString and Equals cannot be ignored :/]

Utility classes too is the better solution for this cases?

**Comment by sadlerjw** [comment]
Hi folks, I'd just like to +1 this feature request. Being able to implement `toString` and `equals`, as well as implementing compound properties (think `public String getDisplayName() { return getFirstName() + " " + getLastName();}`) is really important, at least for me.

**Comment by tomekpiotrowski** [comment]
+1

**Comment by JulienDev** [comment]
+1 too

**Comment by caroth92** [comment]
+1

**Comment by deepu** [comment]
+1

**Comment by cmelchior** [comment]
This is just one solution for the overall problem, which is allowing custom methods which is covered by this issue #909, so closing this a duplicate.
