### ISSUE TITLE
Feature: Removing listener automatically once objects become invalid after deletion

### ISSUE THREAD

**Issue by anggrayudi** [realm/realm-java#6479]
#### Describe your problem or use case
Calling change listener when objects become invalid after deletion is redundant. It makes me to add this logic on every listener I implement in `Activity` or `Fragment`:

    override fun onChange(task: Task) {
        if (!task.isValid || !task.isManaged) return // <== I hate this line

        // some code to display data to UI
    }

#### Describe the solution you'd like
If I remove `if (!task.isValid || !task.isManaged) return` from the logic, I will get `IllegalStateException` because the listener passes invalid Realm objects, and we are trying to access them. Well, we need to remove the listener automatically when they become invalid. Realm listener should not be called once database object is deleted.

**Comment by Zhuinden** [comment]
If you use `RealmObjectChangeListener` then you get the RealmObjet change set which contains if the object was invalidated, this is so that if you store a reference to this object and manipulate it from other areas of your code then you can be aware that those should no longer be run.

I think it was specifically a request that the RealmObjectChangeListener is invoked one last time then never again, so that this could be handled and you don't need to *also* register a RealmResults listener for it.

**Comment by cmelchior** [comment]
Yes, being able to be notified about an object being deleted has a lot of use cases, so this isn't something we really want to change. If you want to change the behaviour globally you can create your own abstract class and use that, something like:

```
abstract class RealmChangeListenerAdapter<T extends RealmModel> implements RealmChangeListener<T> {

        @Override
        public void onChange(T obj) {
            if (RealmObject.isValid(obj)) {
                onObjectChange(obj);
            }
        }

        abstract public void onObjectChange(T obj);
    }
```

It isn't 100% ideal but will reduce the boilerplate.

**Comment by anggrayudi** [comment]
Thanks for the idea @cmelchior. I'll try this.
