### ISSUE TITLE
There are security issues. How do I fix it?

### ISSUE THREAD

**Issue by SeongTaekPark** [realm/realm-java#6535]
I received reports from security team on the following security issues:

1. **Using Format String vulnerable functions**
1) librealm-jni.so
fsb warning funcs
--
fprintf:0009ff88
sprintf:0017ec84
vsprintf:0015259c
--

2. **Race Condition vulnerability exists.**
1) librealm-jni.so
race condition warning funcs
--
access:0013ecb2
--

How should I solve it?

**Comment by bmunkholm** [comment]
@SeongTaekPark You can't and shouldn't. From time to time we receive these warnings that are false warnings from these tools and not a real problem. Similar to some compiler warnings that are what they are - only warnings not errors. 
If you really want to do something, you can get more detailed information about where exactly the problem is and investigate the code which is freely available and assess if you think there is a real security risk and we will be happy to check it out.
