### ISSUE TITLE
Trying to build 0.76.0 version with encryption fails

### ISSUE THREAD

**Issue by demonar** [realm/realm-java#687]
When trying to build the version 0.76.0 of the library i get an error trying to download the core library:

http://static.realm.io/downloads/core/realm-core-android-0.86.0-encryption.tar.gz

The standard version is available, but the encrypted one isn't there.

**Comment by eddieringle** [comment]
@bmunkholm @kneth 

I'm also working on the same project as @demonar and @Pobomo. We're actually now in the painful process of swapping out Realm for a SQLite-based ORM since we needed this application ready for production weeks ago.

However, in a last ditch effort to see if we could get Realm working with encryption, I tried again today. I built 0.76.0 from source using the latest 0.87.4 core libraries, but I'm still seeing the same exception @demonar posted earlier in this thread (I'm running 5.0.1 on a Nexus 5).

While we probably won't be shipping with Realm due to this, I'd really like to see this issue resolved. Thanks.

**Comment by emanuelez** [comment]
I can reproduce the problem. I'm investigating on it right now

**Comment by bmunkholm** [comment]
As I understand it, we havn't seen the GC issue yet, right @emanuelez ?
But that sounds like it's related to things just being cleaned up after you have done more work. Can you share some more info as to how you use Realm. No of objects, queries, iterations?

**Comment by demonar** [comment]
Awesome news, let us know if we can contribute with something

**Comment by eddieringle** [comment]
@bmunkholm Yeah, I can confirm building from master seems to fix our issues. Thanks for working on this.

**Comment by demonar** [comment]
We really need to thank you for the effort and help during these days, sorry for bothering during holidays.
We should run a couple of tests but the issues seem to be gone.

**Comment by benjaminburzan** [comment]
The latest version of encryption cannot be downloaded, I get a 404 when I call
http://static.realm.io/downloads/core/realm-core-android-0.87.5-encryption.tar.gz
Has this package been pulled off the server?
Thanks for your help!

**Comment by bmunkholm** [comment]
The old experimental version has been removed from the server - it's really not recommended to use that by now. A new version will be released tomorrow.

**Comment by benjaminburzan** [comment]
Thanks @bmunkholm for your quick reply! 
I tried to build realm with 
```
"encryption=true"
```
 in local.properties and then
```
 /gradlew androidJar
```
again. I am getting the following error:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/benjamin/Downloads/realm-java/realm-jni/build.gradle' line: 38

* What went wrong:
Execution failed for task ':downloadCore'.
> Could not download file
```
Line 38 wants to download:
```
http://static.realm.io/downloads/core/realm-core-android-0.88.0-encryption.tar.gz  
```
Is there a newer version of this file available on the server but the script has not been modified to use the new file?
Thank you again!

**Comment by emanuelez** [comment]
Hello Benjamin,
since release 0.78.0 encryption is fully supported and there is no need to build your custom version of Realm anymore. Happy times! :) http://realm.io/news/realm-java-0.78/

**Comment by benjaminburzan** [comment]
Thank you @emanuelez for your quick response!

**Comment by eugeneek** [comment]
Issue, which described @demonar early are still there on new jar 0.78
Caused by: java.lang.RuntimeException: Unspecified exception. Invalid database in io_realm_internal_SharedGroup.cpp line 101

Because of this I can not use encryption on my realm db.

**Comment by emanuelez** [comment]
@eugeneek Could you please open a new issue describing your problem? This issue was about the compilation of Realm with support for encryption, which is something that is not needed now. It would also help other users potentially having your same issue.

**Comment by komalnikhare** [comment]
hello @bmunkholm 

I'm attempting to integrate the Realm.io database into a fresh project on Eclipse however upon compilation the following error is thrown:

[2015-10-22 19:41:44 - RealmIntroExample] The library 'realm-0.84.0.jar' contains native libraries that will not run on the device.
[2015-10-22 19:41:44 - RealmIntroExample] Additionally some of those libraries will interfer with the installation of the application because of their location in lib/
[2015-10-22 19:41:44 - RealmIntroExample] lib/ is reserved for NDK libraries.
[2015-10-22 19:41:44 - RealmIntroExample] The following libraries were found:
[2015-10-22 19:41:44 - RealmIntroExample]  - lib/arm64-v8a/librealm-jni.so
[2015-10-22 19:41:44 - RealmIntroExample]  - lib/armeabi/librealm-jni.so
[2015-10-22 19:41:44 - RealmIntroExample]  - lib/armeabi-v7a/librealm-jni.so
[2015-10-22 19:41:44 - RealmIntroExample]  - lib/mips/librealm-jni.so
[2015-10-22 19:41:44 - RealmIntroExample]  - lib/x86/librealm-jni.so
[2015-10-22 19:41:44 - RealmIntroExample]  - lib/x86_64/librealm-jni.so

**Comment by bmunkholm** [comment]
Hi @komalnikhare 
Please create a new issue as this one is already closed and it doesn't seem related. Adding more details would also be helpful. Can you post some of your project setup files?
