### ISSUE TITLE
file exception error

### ISSUE THREAD

**Issue by NamGungWon** [realm/realm-java#6991]
#### Goal
bug fix and Cause Analysis

#### Actual Results
Caused by io.realm.exceptions.RealmFileException
Unable to open a realm at path '/data/data/com.example.myapp/files/myapp.realm': Incompatible histories. Unexpected future history schema version. (Incompatible histories. Unexpected future history schema version) (/data/data/com.example.myapp/files/myapp.realm) in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

#### Steps & Code to Reproduce
crashed by init in applcation, this code 
cash line 'realm = Realm.getDefaultInstance();'

```
Realm.init(this);
RealmConfiguration config = new RealmConfiguration.Builder()
                .name("myapp.realm")
                .schemaVersion(29)
                .migration(new RealmMigrations(getApplicationContext()))
                .build();
        Realm.setDefaultConfiguration(config);

        realm = Realm.getDefaultInstance();
```

#### Version of Realm and tooling

Realm version(s): 4.4.0

Realm Sync feature enabled: No

Android Studio version:  3.5

Android Build Tools version: 28.0.3

Gradle version: 5.1.1

Which Android version and device(s): 8.0,7.0 and galaxy

**Comment by NamGungWon** [comment]
Is it a problem not to call? 'realm.close()'

**Comment by edualonso** [comment]
Hi @NamGungWon. 

> Unable to open a realm at path '/data/data/com.example.myapp/files/myapp.realm': Incompatible histories. Unexpected future history schema version. (Incompatible histories. Unexpected future history schema version)

The reason behind this crash is likely to be that you are providing an "older" schema version when calling `schemaVersion(29)` on your configuration builder. Are you sure `29` is the latest schema version?

> Is it a problem not to call? 'realm.close()'

In order to do housekeeping and deallocate resources properly, all Realm instances should be closed when not in use anymore - see https://realm.io/docs/java/latest/#closing-realms. The only case where it's OK not to call `realm.close()` explicitly is if you are using try-with-resources to get your Realm instance.

**Comment by NamGungWon** [comment]
hi @edualonso

**Comment by cmelchior** [comment]
@NamGungWon I assume you fixed the issue. If not feel free to reopen the issue, but we probably need a small sample project that reproduces the issue in order to help. It does look like wrong usage of Realm somehow.
