### ISSUE TITLE
Realm access from incorrect thread.

### ISSUE THREAD

**Issue by rohit85111** [realm/realm-java#7074]
Getting this below error in some of the devices and in some devices it's working fine.

Error:  Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.

getSuccessDataFromDb() calling from background thread, not main thread.

```
 private void getRealmInstance(){
        if(realm!=null)
            realm = null;
      realm =  Realm.getDefaultInstance();
}
 public List<Realm_ImageUploaded> getSuccessDataFromDb() {
         getRealmInstance();
        final RealmResults<Realm_ImageUploaded>[] realm_imageUploaded = new RealmResults[]{null};
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(@NotNull Realm realm) {
                realm_imageUploaded[0] = realm.where(Realm_ImageUploaded.class).findAll();
            }
        });

        return realm.copyFromRealm( realm_imageUploaded[0]);
    }
```

**Comment by edualonso** [comment]
Hello @rohit85111. That error message indicates you are using the `realm` class field from a thread other than the one that set its value in `getRealmInstance`. It is difficult to draw a different conclusion based on the code snippet you provide. Are you certain there are no other scenarios in which your code calls `getRealmInstance` from a different thread than the one that calls `getSuccessDataFromDb()`?

**Comment by rohit85111** [comment]
@edualonso but this issue happening in some of the devices.

Below are the classes that are using in call to  getSuccessDataFromDb();

**BackgroundTask.java**

public class BackgroundTask extends Worker {

    private Context mCtx;

    public BackgroundTask(@NonNull Context context, @NonNull WorkerParameters workerParams) {
        super(context, workerParams);
        mCtx = context;
    }

    @NonNull
    @Override
    public Result doWork() {
       
        Observable.zip(requests,
                new Function<Object[], List<ResponseData>>() {
                    @Override
                    public List<ResponseData> apply(Object[] objects) {
                        List<ResponseData> list = new ArrayList<>();
                        for(Object obj:objects)
                            list.add((ResponseData) obj);
                        return list;
                    }
                }
        )
                // Run on a background thread
                .subscribeOn(Schedulers.io())
                // Be notified on the main thread
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<List<ResponseData>>() {
                               @Override
                               public void accept(List<ResponseData> data) {
                                   saveSuccessDataInDb(data);    
                               }
                           }, new Consumer<Throwable>() {
                               @Override
                               public void accept(Throwable throwable) throws Exception {
                                  UtilView.showLogError("@Flow","errorMessage "+throwable.getMessage());
                               }
                           }
                );
       
        return result[0];
    }


  
    private void saveSuccessDataInDb(List<ResponseData> data){
        UtilView.checkUuidAndSaveSuccessData(data);
    }
    
}


 **UtilView.java**

 public static void checkUuidAndSaveSuccessData(List<ResponseData> successData){
        new Thread(new Runnable() {
            @Override
            public void run() {
                List<Realm_ImageUploaded> result = RealmService.with(KlickCheckApplication.getInstance()).getSuccessDataFromDb();
                // other operations  
            }
        }).start();

    }


**RealmService.java**
private void getRealmInstance(){
        if(realm!=null)
            realm = null;
      realm =  Realm.getDefaultInstance();
}
 public List<Realm_ImageUploaded> getSuccessDataFromDb() {
         getRealmInstance();
        final RealmResults<Realm_ImageUploaded>[] realm_imageUploaded = new RealmResults[]{null};
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(@NotNull Realm realm) {
                realm_imageUploaded[0] = realm.where(Realm_ImageUploaded.class).findAll();
            }
        });

        return realm.copyFromRealm( realm_imageUploaded[0]);
    }

**Comment by edualonso** [comment]
You have a race condition.

Calling `UtilView .checkUuidAndSaveSuccessData` spawns a new thread, say `Thread A`, which in turn calls `RealmService.getSuccessDataFromDb`, which in turns sets `RealmService .realm` with a Realm instance after calling `RealmService .getRealmInstance`.

Now imagine that `Thread A` goes to sleep before it has reached the `realm.executeTransaction(...)` instruction inside the `RealmService.getSuccessDataFromDb` method. Meanwhile, somewhere else in the code, you call `UtilView.checkUuidAndSaveSuccessData` again. A new thread, say `Thread B` will be spawned as expected and, while `Thread A` is still sleeping, `Thread B` reaches the call to `RealmService.getRealmInstance()` inside `getSuccessDataFromDb()`. Now your logic has effectively changed the value of the `RealmService .realm` field to point at a default Realm instance obtained from `Thread B`, which continues its execution and finishes its logic correctly.

However, `Thread A` is now resumed and reaches `realm.executeTransaction(...)`. It will crash with the message you mentioned above, as the Realm instance you are trying to access was not obtained from `Thread A`, but from `Thread B`.

The reason why this logic crashes only in some devices is because the thread behaviour is not deterministic and varies from execution to execution. To solve this you need to synchronise how you access your Realm instances to avoid such race conditions.
