### ISSUE TITLE
Realm.deleteRealmFile() doesn't return the correct result

### ISSUE THREAD

**Issue by ImGauravC** [realm/realm-java#711]
I have a user session based app. On logout I call Realm.deleteRealmFile(context) and it returns true. 
But when I log in as another user, the data of the previous Realm still exists. How to remove all data ? 

I'm on Android and using Realm 0.76 for Android.

**Comment by cmelchior** [comment]
Hi @ImGauravC 
If you call deleteRealmFile() while the Realm is still open the file will not be deleted, ie. you need to call Realm.close() on all your open instances.

Alternatively instead of deleting the Realm file you can call  ```Realm.clear(Session.class)``` which will delete all objects of type Session while keeping the Realm file.

Does that answer your question?

**Comment by ImGauravC** [comment]
Thanks. That worked.

**Comment by cmelchior** [comment]
Hi @ImGauravC 

We rely on the return value of Java's File.delete() which returns true and it reports the wrong result due to how the file system works.  

It is documented in the JavaDoc for this reason as well, but we could probably add some additional checks that could catch some more edge cases. However for some use cases it will probably never be possible, like eg. two processes having the file open.

**Comment by ImGauravC** [comment]
I see. Thanks for the response @cmelchior :)

**Comment by cmelchior** [comment]
We have added a check to ```Realm.deleteRealmFile()``` that will throw an error if called incorrectly. https://github.com/realm/realm-java/pull/787

It will be released as part of 0.79.0.
