### ISSUE TITLE
Unable to resolve dependencies not related to Realm when updating from 5.14.0 to any version higher

### ISSUE THREAD

**Issue by KennyGoers** [realm/realm-java#7204]
#### Goal
To build Android project

#### Actual Results
Build Issue resolving third party libraries when using Realm version 5.15.0 or higher

#### Steps & Code to Reproduce
When removing or changing the realm version number for the plug-in (and thus the realm version itself) from any version below 5.15.0 to 5.15.0 or higher, including 10.0.1 I can no longer resolve a number of dependancies that resolve perfectly fine when using a lower version. 

#### Version of Realm and tooling

Realm version(s): 5.14.0, 5.15.0, +

Realm Sync feature enabled: No

Android Studio version: 4.1.0/4.1.1

Android Build Tools version: Unsure

Gradle version: 6.5

Which Android version and device(s): N/A

**Comment by clementetb** [comment]
Hi Kenny, what are the dependencies that cannot be resolved? Could you please share some details of your Gradle config?

**Comment by rorbech** [comment]
Closing due to lack of feedback. Maybe try to track the dependencies with `./gradlew dependencies` to see if any transitive dependencies triggers unforeseen constraints in the version of the unresolvable dependencies. 

Feel free to reopen with the appropriate information, ex. the above trace, if the issue persists.
