### ISSUE TITLE
Realm is not storing sequence properly. 

### ISSUE THREAD

**Issue by DAKSHSEMWAL** [realm/realm-java#7291]
#### Actual Results
I am storing data from my API to the database 
Realm is Converting my JSON  which is `"ahi": [
                {
                    "image": "thumbsupgreen",
                    "addedAt": 1612317276,
                    "color": "green",
                    "addedBy": "worker",
                    "mainText": "Your vitals give you full permission!",
                    "nextActions": [
                        {
                            "action": "update",
                            "text": "I feel great"
                        },
                        {
                            "action": "update",
                            "text": "I feel dull"
                        }
                    ],
                    "alertList": [],
                    "subText": "You’re doing well, time for pushing yourself today just a tad more"
                }
            ]`

to 
`{"ahi":[{"image":"thumbsupgreen","addedAt":1612317276,"color":"green","addedBy":"worker","mainText":"Your vitals give you full permission!","nextActions":[{"action":"update","text":"I feel great"},{"action":"update","text":"I feel dull"}],"alertList":[],"subText":"Youâre doing well, time for pushing yourself today just a tad more"}]}`

#### Version of Realm and tooling
io.realm:realm-gradle-plugin:4.2.0
Realm version(s): 4.2.0

Realm Sync feature enabled: Yes/No

Android Studio version: 4.1.2

Android Build Tools version: 30.0.2

Gradle version: 4.1.2

Which Android version and device(s): 10, Honor 20

**Comment by edualonso** [comment]
Hi @DAKSHSEMWAL
We've had some issues with escaping strings in the past. I would recommend you upgrade your Realm dependency to use the latest version, if possible, as it should work just fine.

**Comment by akshay-kapase** [comment]
Tried using the latest plugin but still facing this issue

**Comment by edualonso** [comment]
I've tried creating a Realm object with just one string field using this payload:
```
{ "subText": "You’re doing well, time for pushing yourself today just a tad more" }
```
And the `´` character is parsed correctly. I don't see how else this could fail.

Could it be you're unknowingly doing something between the reception of the response and creating the object with `createObjectFromJson`?

**Comment by akshay-kapase** [comment]
yes we are doing createObjectFromJson but we are not parsing that part of json

**Comment by akshay-kapase** [comment]
@edualonso ok I think this might be the issue that we are storing

**Comment by edualonso** [comment]
> @edualonso yes we are doing createObjectFromJson but we are not parsing that part of json

@akshay-kapase If by that you mean you are not post-processing the response you are getting from the API in any way, then I am at a loss. I have run a test myself against the latest 10.3.0 release (on top of all the other JSON-related tests we have) and the string you provided us with doesn't become what it is being shown in the first comment.

Would it be possible for you to debug the code that causes this behaviour and set a breakpoint on the line where you call `createObjectFromJson` and evaluate the string you are feeding into the method? You could take a screenshot at that very moment where the string representing the JSON payload is clearly visible and take another screenshot just after the object has been created showing the string value that is stored in it so that I can compare them and have a better understanding of what it is that you are doing.
