### ISSUE TITLE
Find flaky tests that complain about "Remember to close()..." and use local BlockingLooperThread instead

### ISSUE THREAD

**Issue by edualonso** [realm/realm-java#7333]
It seems using `BlockingLooperThread` as a class property can lead to the instance being caught up a weird state after running several tests. There has been a number of flaky tests which complained precisely about this.

Find them and use local instances of `BlockingLooperThread` as it seems to avoid race conditions.

**Comment by cmelchior** [comment]
We found the root cause, which is that Parameterized tests cache values created inside the method annotated with `@Parameterized.Parameters`. In this case, the BlockingLooperThread was created here and it contained a state that wasn't reset between tests.

So it seems that any parameters created by a parameterized test must be stateless.

**Comment by edualonso** [comment]
I've checked all other places where we use this and none of the tests are paremeterised. Additionally, I've run all tests using it in isolation and could determine the class field containing the `BlockingLooperThread ` is re-instantiated after every test which makes it stateless. I will still update the documentation to make it clear(er) we shouldn't be reusing instances in a funny way.
