### ISSUE TITLE
Realm getinstance() method very slow on android api 28

### ISSUE THREAD

**Issue by kaswan24** [realm/realm-java#7371]
I am developing an android application which uses Realm as an offline database, opening the app for the first time takes a lot of time, almost **3-4 seconds** and inspecting the things under the hood through android **strict mode** I came out to know that **Realm getinstance()** method itself is taking **1-2 seconds.**

Is there any workaround this problem? It's extremely slow..

**Comment by cmelchior** [comment]
Hi @kaswan24, sorry for the late reply.

Without more details it is unclear exactly what is causing this. It could either be because you are doing a lot in an initial data block or are using `compactOnLaunch`, in both of these cases you can use `Realm.getInstanceAsync()` to make the Realm load on a background thread which will not block the UI thread.

To get it any closer, we would need more details.
