### ISSUE TITLE
After addChangeListener on RealmResult onChange Take time to call (Approx 3-5 seconds)

### ISSUE THREAD

**Issue by mkansara** [realm/realm-java#7451]
Take time to call onChange Method for RealmResult  with Records above 4k+

Realm version(s): 10.3.1

Realm Sync feature enabled: No

Android Studio version: 4.3.1

Android Build Tools version: 30.0.2

Gradle version: 4.1.2

Which Android version and device(s):

Oneplus 6T devices => Android 10

**Comment by cmelchior** [comment]
Hi @mkansara In some cases, changelisteners can take a while to trigger as we are running diffs in the background. If that diff is hard to calculate, the notifications can be delayed. This normally happens if there are cycles in your schema like `A -> B -> A` where the cycle is created using Object references or Lists....you can break these cycles by using `@LinkingObjects` instead (if possible). 

I hope that answers your question.

If you have specific performance concerns, we would need to see a fully working sample in order to provide better guidance.
