### ISSUE TITLE
findAllAsync freezes UI thread

### ISSUE THREAD

**Issue by prasad-dot-ws** [realm/realm-java#7495]
Hello, In my application I have 800k+ member records. And I attempt to fetch all with `findAllAsync`. However, It seems like `findAllAsync` **runs** on the main thread instead of the **background**. Below is my query,

`var res = realm.where(Member::class.java).notEqualTo("deleted", 1).sort("name").findAllAsync()`

The above query freezes my fragment for about 3-4 seconds. However, query time improves if I lose the sorting.

Currently, the UI is frozen until `onChange` calls.

One another interesting finding is that if I remove `res?.addChangeListener(this)`  `findAllAsync` behaves like an async process and the fragment instantly loads without any freezing. But of course, I don't get the results :)

![image](https://user-images.githubusercontent.com/8954510/120919324-97fa5b00-c6d6-11eb-9da3-cf05f2316fd9.png)

Am I doing something wrong here?

I can understand the query loading time. My expected result is to execute `findAllAsync` asynchronously without blocking the UI thread.

Platform: Android
Language: Kotlin
Realm Version: 6.0.2

**Comment by cmelchior** [comment]
Hmm, the above should correctly run in the background, but there is a few cases where an async query is being forced to run on the UI thread:

1) If you call `Realm.refresh()` on the thread, it will force all change listeners to evaluate synchronously
2) If you make a synchronous transaction, i.e. `Realm.beginTransaction()` or `Realm.executeTransaction()` instead of `Realm.executeTransactionAsync()`. Similar to `refresh()`, that will also force all change listeners to evaluate on the UI thread.

I don't know if either of those cases apply to you?

**Comment by prasad-dot-ws** [comment]
That was it! I was calling `Realm.refresh()` in my main thread. It worked perfectly fine as soon as I remove `Realm.refresh()`. 

Thanks a lot @cmelchior !
