### ISSUE TITLE
NativeObjectReference takes all heap 

### ISSUE THREAD

**Issue by ganfra** [realm/realm-java#7564]
### How frequently does the bug occur?

All the time

### Description

Any ideas why NativeObjectReference would take as much space as it is actually? (see screen capture)
We have 2 realm always open in the background listening to events in the db. 
Realm.getGlobalInstanceCount stays at 3-4 instances, so don't think there is a leak on there.

This is happening just at the start-up of the application, so not a long term state.

### Can you reproduce the bug?

Yes, always

### Version

10.8.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

Android 11

### Build environment

![Capture d’écran 2021-09-13 à 16 05 15](https://user-images.githubusercontent.com/8754928/133098722-804935b8-7808-4634-91e1-8881d4da9cbd.png)

**Comment by bmunkholm** [comment]
@ganfra It's hard to guess without more information :-) But I assume this is just capturing the size of your database. How big is your database? Is this a problem or just curiosity for now :-)?

**Comment by ganfra** [comment]
We have some performance issues, so trying to figure if it can be related! The db was 100Mo large at this moment

**Comment by bmunkholm** [comment]
It can take up more memory if you have the same realm open in multiple threads concurrently. So that's at least a thing to consider. But it's not so likely to be performance related.

We do try to keep the github issues to just track bugs, but encourage to use our [Forums](https://www.mongodb.com/community/forums/c/realm-sdks/58) for "how-do-I" kind of things or for getting advice.  
So if you have no specific suspicion of a bug, I will close this one for now.
Thanks!
