### ISSUE TITLE
Duplicate embedded objects in list after insertOrUpdate

### ISSUE THREAD

**Issue by PAlAl** [realm/realm-java#7565]
### How frequently does the bug occur?

All the time

### Description

Hi everyone, we have problem when use embedded objects in a list. After updating the data, some embedded objects are duplicated.

See details and reproducing in test:
https://github.com/PAlAl/RealmEmbeddedTest

Short description:
We have list of parent objects with children embedded objects, e.g.
`
[
   {
      "children": [
         {
            "code": "1"
         },
         {
            "code": "11"
         }
      ],
      "id": 1
   },
   {
      "children": [],
      "id": 2
   },
   {
      "children": [
         {
            "code": "3"
         }
      ],
      "id": 3
   }
]
`

Then try:
-write it to realm
-read with copy from realm
-update child in parent with id = 1
-writing it to realm
-read with copy from realm and check child in parent with id = 3 is duplicated

![scr](https://user-images.githubusercontent.com/17061769/133232572-47d74835-8ab8-4cbf-a8d4-1c05106d96e7.png)

### Can you reproduce the bug?

Yes, always

### Version

10.5.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

android - any

### Build environment

Android Studio version: 4.2
Android Build Tools version: 30.0.3
Gradle version: 4.2.0

**Comment by rorbech** [comment]
Hi @PAlAl Thanks for the precise reproduction project ... and sorry for the late reply. I was able to reproduce the issue and it was caused by our implementation being a bit different for the `insertOrUpdate` variant that takes an iterator. The proper import (clearing the existing list before appending the updated objects) was already implemented in https://github.com/realm/realm-java/commit/ef558b23d6767c87e5931a34f0a238e895463f6c#diff-314913e78729941373d8ebb61f525077f7f5cc070da10ea6776bf4dc30c297e9R1316, but the code paths aligning the iterator and non-iterator cases was done as part of 10.6.0 which contained heavy updates of the infrastructure due to multiple new datatypes. So, was already fixed from 10.6.0.
