### ISSUE TITLE
The size of the database grows after repeated insertion and deletion of data from it

### ISSUE THREAD

**Issue by Kolyall** [realm/realm-java#7785]
### How frequently does the bug occur?

Always

### Description

The size of the database grows after repeated insertion and deletion of data from it, when the Flow listener is open

Here is example project:
https://github.com/Kolyall/RealmIssues
Just run it 
Click on "Start Inserting Into Db"
Wait 30 min
[result]

Database size is over 5MB
p.s.: Realm Open Key(128Hex) for RealmStudio: `31323334353637383930313233343536373839303132333435363738393031323334353637383930313233343536373839303132333435363738393031323334`

![2023-03-14_10-13](https://user-images.githubusercontent.com/3495165/224923575-0d6ab9e9-ba4b-48c2-b43e-3a94d74994ea.png)

But it has only 6 objects:
![2023-03-14_10-19](https://user-images.githubusercontent.com/3495165/224924630-a25c1e9c-0e6a-421a-bac6-cd880f0735a4.png)

### Can you reproduce the bug?

Always

### Reproduction Steps

Example project:
https://github.com/Kolyall/RealmIssues
Just run it
Click on "Start Inserting Into Db"
Wait 30 min
[result]
Database size is over 5MB

### Version

10.13.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

Android

### Build environment

Android Studio version: 
Android Studio Electric Eel | 2022.1.1 Patch 2
Build #AI-221.6008.13.2211.9619390, built on February 17, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-144-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false

Non-Bundled Plugins:
    idea.plugin.protoeditor (221.6095)
    com.intellij.marketplace (221.6008.18)
    com.intellij.javafx (1.0.4)
    co.anbora.labs.kse (1.2.2)
    JUnit4-Parallel-Runner (1.5)
    com.atlassian.bitbucket.references (2022.1.223)
    com.thoughtworks.gauge (221.6008.13)
    com.developerphil.adbidea (1.6.8)

Current Desktop: ubuntu:GNOME

Android Build Tools version: 7.4.2
Gradle version: https\://services.gradle.org/distributions/gradle-7.5-bin.zip

**Comment by cmelchior** [comment]
Hi @Kolyall. This is most likely a result of version pinning. You can read more about it here: https://www.mongodb.com/docs/realm/sdk/swift/realm-files/compacting/  (even though the documentation is for Swift, the same applies to Java). 

This means that when using flows, the size of the Realm file will somewhat depend on how often the GC runs.

You should hopefully see the file size stabilize and not continue to grow?

If that is not good enough, there are a few options for fixing it.

- You can periodically use compaction to reduce the size of the Realm.
- You can provide your own implementation of a `FlowFactory` that doesn't freeze objects. Our implementation is "freezing" objects here https://github.com/realm/realm-java/blob/73c95a43a50186ba4744d19d7cb41d315445ddc2/realm/realm-library/src/main/java/io/realm/internal/coroutines/InternalFlowFactory.kt#L126 which is what is causing the issue since the Realm file then has to track multiple versions. We do this, to allow these objects to pass between threads (which is very common in Flows), but alternatively, you can either pass them on directly (but then they are thread-confined), or you can use `copyFromRealm` (but then your app will use more JVM memory).

So the solution depends a bit on exactly what tradeoffs you want to take.

**Comment by Kolyall** [comment]
1. _You can periodically use compaction to reduce the size of the Realm._
When I use compaction the error occurs:
https://github.com/realm/realm-java/issues/7788
2. I already use `copyFromRealm`, so why the size of the database grows in this case?
https://github.com/Kolyall/RealmIssues/blob/fad0f9d54e31e61e1b7b3d92029332da2fbb9266/app/src/main/java/com/realmissues/db/RParentRealm.kt#L52

**Comment by cmelchior** [comment]
Because you are using `copyFromRealm` on an already frozen instance. It is up to the mercy of the GC then when it is released.

Another solution could also be to use a callbackFlow around our change listeners, and then manually use `copyFromRealm` inside those. Objects in the callback are "live" and thus don't pin memory the same way.

I.e.

If you use copyOnRealm on a "live" object, you shouldn't see the file increase.
If you use copyOnRealm on a "frozen" object, you might still see a file increase, but it will depending on the GC.

**Comment by Kolyall** [comment]
Ok, I'll try to make my own implementation of a FlowFactory that doesn't freeze objects and use `copyFromRealm`
