### ISSUE TITLE
Wrong result when using x == NONE {y}

### ISSUE THREAD

**Issue by jd565** [realm/realm-java#7862]
### How frequently does the bug occur?

Always

### Description

Am writing queries using the RQL syntax, and a couple of our queries are filtering out items that don't exist in a list. However, if we put in a list of a single item then the wrong item is selected.

```
fun cleanup(ids: List<Int>) {
    val queryIds = ids.joinToString(prefix = "{", postfix = "}", separator = ",")
    realm.where<RealmItem>()
        .rawPredicate("memberId == NONE $queryIds")
        .findAll()
        .deleteAllFromRealm()
}
```

If I have ids 100, 101 and 102 in realm, and run this passing in `listOf(100, 101)`, then it correctly deletes 100 and 101 leaving 102, but if I pass in `listOf(100)`, then it does not delete the item with id 100. Have also tried hardcoding the ids in my test `"memberId == NONE {100}"` and see the same behaviour.

I am new to RQL so could be doing something wrong but this seems like incorrect behaviour to me.

### Can you reproduce the bug?

Always

### Version

10.17.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android all versions

### Build environment

Android Studio version: Iguana Canary 18
Android Build Tools version: 8.1.2
Gradle version: 8.4

**Comment by kneth** [comment]
@jd565 Thank you for taking the time to report. 

@ironage Do you have any ideas?

**Comment by ironage** [comment]
Hi @jd565 
Assuming 3 objects with member_ids of 100, 101, 102 then we'd expect the following matches for these queries:

|  query    | result objects by member_id  |
|---|---|
| `member_id == NONE {100, 101, 102}`   |  no results |
| `member_id == NONE {100, 101}`   |  102 |
|  `member_id == NONE {100}`  | 101, 102  |
|  `member_id == ANY {100, 101, 102}`  | 100, 101, 102 |
|  `member_id == ANY {100, 101}`  | 100, 101 |
|  `member_id == ANY {100}`  | 100 |

We can read `member_id == NONE {100, 101, 102}` as "match all members who have a member_id that equals none of {100, 101, 102}".
From your expectations, I think you are looking to use the ANY query instead of NONE. Let me know if that works for you.

**Comment by ironage** [comment]
@jd565 thanks for the clarification. I wasn't able to reproduce, until I add an index to test property (this applies to you if member_id is a primary key or if you have added an index manually). I submitted a fix in https://github.com/realm/realm-core/pull/7333, but until that lands, I'd suggest that you change your query to be `member_id != ALL {...}` which should produce equivalent results for the time being. Thanks for reporting this bug to us!
