### ISSUE TITLE
Saves only every other row

### ISSUE THREAD

**Issue by samyboy89** [realm/realm-java#789]
Whenever I save and object like this:

    mRealm.beginTransaction();
    for (int i = 0; i < items.size(); i++) {
        items.get(i).setSection(allAppsSection);
        Log.wtf("ITEM", item.packageName);
    }
    mRealm.commitTransaction();

it only saves every other row into the database. The actual RealmResults list contains all the objects, but when I do a log in the code above it only shows every other object. So it seems like it's only handling every other object. I made a wrapper class like the one below, and that works. But I think that is a stupid workaround. Any thoughts/suggestions on the issue.

    mRealm.beginTransaction();
    for (ItemWrapper item : wrappedList) {
        mRealm.where(Item.class)
                    .equalTo("packageName", item.packageName)
                    .equalTo("className", item.className)
                    .findFirst().setSection(allAppsSection);
    }
    mRealm.commitTransaction();

**Comment by emanuelez** [comment]
Hello!
RealmResults are **live** views of your data, meaning that when you modify one of its items in a way that excludes it from the query associated to the RealmResults instance, you also change the RealmResults itself instantly. This is very handy in many occasions but it bites back when you want to iterate and modify some items. We are working on making this use-case more predictable.

Would it help in your case if you iterated backwards?

**Comment by samyboy89** [comment]
Hi. I iterated backwards, and it worked. Why is that?
I still feel like this is something that should work without such a change.
Thanks for the help! :+1:

**Comment by emanuelez** [comment]
I will try to explain with an example.

Let's say you want to query for all dogs with age 3 and change their age to 4:

```java
// This returns 3 dogs
RealmResults<Dog> dogs = realm.where(Dog.class).equalTo("age", 3).findAll();

realm.beginTransaction();
for (Dog dog : dogs) {
   dog.setAge(4);
}
realm.commitTransaction();
```

What happens when you do `dog.setAge(4)` for the first time? As you know RealmResults are not a copy of your data, but your **actual** data, meaning that in the local thread as soon as the command is executed the age of that specific dog is now 4 (the change will be visible to all the other threads after `commitTransation()`). This change to the dog gets immediately affects the RealmResults instance, which now contains only 2 dogs, since the first has now age 4. That's why when the iterator goes to the next item (number 2), it actually goes to what used to be number 3, and that's why it applies the change only to half of the items. Iterating backwards within a transaction makes sure the modified items don't affect the cardinality of the remaining ones.

I know it's a bit convoluted, but it makes sense when you consider the **live** nature of RealmResults.
I hope this explanation helps you! Please leave some feedback to it so if it's good enough we will include it in the official documentation :smiley:

**Comment by jenzz** [comment]
@emanuelez Yes, it does make sense. Thanks for the clarification. Nonetheless, I think what @samyboy89 was doing is quite intuitive and / or almost general practice so this might become a common pitfall for Realm users in the future?

I don't know about the internals of Realm, but isn't it possible to also delay updating the current Realm object instance until `commitTransaction()` was called?
