### ISSUE TITLE
Any way to schedule Realm transaction?

### ISSUE THREAD

**Issue by ousenko** [realm/realm-java#797]
I got a background service (separate thread) updating Realm. It opens transaction, performs long-running task, and finally commits or cancels transaction.

At the same time, my app's user needs to perform updates on Realm entity. For simplicity sake', let it be "update favorite status" of item.

If I try to: realm.beginTransaction(), - > mark item favorite -> commit transaction --- from UI thread it will cause UI to block, [as per API docs](http://realm.io/docs/java/0.78.0), if my background service has not committed transaction yet.

So I need a way to schedule a transaction. What are the possible ways to do that?
I can only think of IntentService or command service pattern, but is not it way too complicated for such an easy task?

**Comment by cmelchior** [comment]
Hi @ousenko 
It is usually considered bad practice to have long-running transactions in any database, for the exact reasons you are experiencing here. We are probably a bit to blame since we exposed a method for adding objects to Realm just using a InputStream. Depending on your use case, you might have a few options though:

1) If you are not reading large amounts of data from the network. I would convert them to standalone objects first before adding them in a transaction.

2) If in a very long loop, commit at intervals instead of at the end.

3) Move all writes to background threads: Like you mentioned, using a IntentService is an option. You can also use the standalone objects introduced in 0.78 to more easily send data to some other thread, or use a ExecutorService instead like below:

```
ExecutorService executor = Executors.newSingleThreadExecutor();
final int id = tweet.getId();
final boolean flag = tweet.getFlag();
executor.execute(new Runnable() {
    @Override
    public void run() {
        Realm realm = Realm.getInstance(getContext());
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                Tweet tweet = realm.where(Tweet.class).equalTo("id",id).findFirst();
                tweet.setFavorite(flag);
            }
        });
        realm.close();
    }
});
```

**Comment by ousenko** [comment]
Thanks for support!
I ended up doing it all the 3rd way.
