### ISSUE TITLE
Date precisision not precise enough (dropps all milliseconds)

### ISSUE THREAD

**Issue by falkorichter** [realm/realm-java#833]
Java Dates have a millisecond presicsion. Realm queries on dates should respect this precision.

See the example project:
https://github.com/falkorichter/realm-date-fail

The test class in question:
https://github.com/falkorichter/realm-date-fail/blob/master/app/src/androidTest/java/com/sensorberg/android/realmdatecomparison/ApplicationTest.java

The tests shows that with 999 milliseconds difference, realm fails to query correctly.

See the status of this test at: https://travis-ci.org/falkorichter/realm-date-fail.svg?branch=master

**Comment by cmelchior** [comment]
Hi @falkorichter 
Thank you for the testcase. It is a known issue however, that is also documented in our current limitations: http://realm.io/docs/java/0.78.0/#general

The reason is that we want Realms to function cross-platform eg. NSDate uses floating points internally. This is why we currently only support second-precision (it is the same on iOS), but we definitely want to fix it going forward, it is just not a trivial thing to do.

For now, a workaround would be to store your dates as long and convert them back to Date when needed.

**Comment by falkorichter** [comment]
@cmelchior why not drop the Date support completely on Android as it is crippled? Bring it back, when it is working.

**Comment by virl** [comment]
Please fix this. Really annoying to write all the code to use Dates only to discover that precision is not enough and rewrite everything to use long.

**Comment by esco** [comment]
:+1:

**Comment by senorcris** [comment]
:+1:
