### ISSUE TITLE
Realm Instances guidelines (incl. close() )

### ISSUE THREAD

**Issue by kenticus** [realm/realm-java#874]
What is the recommended style for creating Realm Instances? 
Right now I'm leaning towards having a single instance in my ApplicationContext. Is there any reason I shouldn't be doing that?

**Comment by ousenko** [comment]
My two cents:

1. If you've obtained instance in main (UI) thread, then you can only use it in this thread. You are not allowed to use this instance in background service operating in a separate thread (e.g. IntentService)
2. Once you've obtained an instance, you should be able to close instance when component is destructed by framework (e.g. close it in Activity/Fragment onDestroy()). If you can not (or do not) close it, you're leaking resources
3. If you want to reuse the same instance in many components (e.g., open and close it in "root" activity), I guess you'll have settle it down in some sort of **retained  instance** fragment and do some reference counting. I managed to do it, but I strongly advise against it

**Comment by cmelchior** [comment]
You can also read some more hints to what to do in this issue: https://github.com/realm/realm-java/issues/774

But you are right, our documentation is lacking  some information about this topic which we need to add.

**Comment by vickychijwani** [comment]
Hi @cmelchior, I too am calling `Realm.getInstance()` in my Application's `onCreate`. Naturally, I can't `close()` it because I don't have a destroy callback to hook into. I was assuming that the Realm will get closed automatically when the app is killed, but I wanted to know if you have an official stance on this. Will this cause any problems, you think?

**Comment by akhyrul** [comment]
I  have a helper class for abstracting data access (let's say it's named `DataSource`). It's a class with `Context` on the constructor. 

Should I `close()` it on `finalize()`? Any suggested best practice?

**Comment by ousenko** [comment]
@akhyrul Relying on `finalize()` to do anything is not a good idea. 

Your implementation already has problems - Realm file size is gonna grow if you don't close it manually, and it's possible to get some native crash due to some memory usage stuff, as long as I recall my past experience.

If you're avoiding doing too much `.getInstance()` / `close()` calls, I suggest you use some static helper which implements reference counting.

Any activity calls `DataSource.getInstance()` in `onCreate()` and the counter increases, however, only 1 instance remains open. Then, at `onDestroy()` the counter is decreased, and if it reaches 0, then Realm instance is closed. 

However, in this case avoid calling `DataSource.getInstance()` off main thread, it will crash you.
