### ISSUE TITLE
Duplicate entries using copyToRealmOrUpdate() despite @PrimaryKey

### ISSUE THREAD

**Issue by jenzz** [realm/realm-java#882]
Hi there!

I'm using the latest version of Realm: **0.79.1**
I noticed a weird behaviour when using `copyToRealmOrUpdate()` resulting in duplicate entries.
Maybe this is the expected behaviour. I'm not sure.

I've created a sample project: https://bitbucket.org/jenzz/realm-primarykey-bug/src

So what's the problem? The following code...

```
Realm realm = Realm.getInstance(this);
realm.beginTransaction();

Address address = new Address("123 456", "High street");

User user1 = new User(1, address);
realm.copyToRealmOrUpdate(user1);

// Note: Same id and same address!
User user2 = new User(1, address);
realm.copyToRealmOrUpdate(user2);

realm.commitTransaction();
realm.close();
```

...generates the following DB:

![screen shot 2015-02-21 at 14 09 39](https://cloud.githubusercontent.com/assets/1798455/6314381/28f4b8b0-b9d4-11e4-9a45-b0db059a4f9e.png)

Given that `user2` has the **same id and address** as `user1`,
I would expect the `Address` table to just update the currently mapped entry instead of inserting a duplicate.

**Comment by bmunkholm** [comment]
That looks like a bug - we will check up on that. Thanks for the clear repro!
Could you open up access to the bitbucket - I'm denied access :-(

**Comment by jenzz** [comment]
Oops, I thought it was public by default.
You should have access now.

Thanks for the prompt reply.

**Comment by cmelchior** [comment]
Hi @jenzz 
It is actually the currently expected behaviour as your Address doesn't have any primary key.
Currently we only update objects we know for sure can be updated, ie. those with primary keys. Other objects are copied, but the old ones aren't deleted (other objects might reference them).

In your case it means that our User is correctly updated, but any reference objects are copied, hence you get two Address objects. 

For now the solution would be a manual cleanup or simply let the objects stay in the database. Neither is optimal.

We are however aware of the problem, and we do plan to make use cases like yours easier going forward. Your use case could would most likely be solved through the use of adding primary keys to backlinks, which are are automatically created references to other objects referencing that object.

**Comment by cmelchior** [comment]
Hi @jenzz 
I assume the above answered your question. Feel free to add additional info if that is not the case.

**Comment by jenzz** [comment]
Hi @cmelchior 

Not the answer I was hoping, but yes, it answered my question.
I like the idea of adding primary keys to backlinks! :+1:

**Comment by spee** [comment]
How would you return the backlink as the primary key, as a LinkingObjects can't be a dynamic var and therefore not visible to objc?

**Comment by usainat** [comment]
Adding primary key o the database of realm object gives me exception of duplicate values during migration . how  can u do it?

**Comment by Zhuinden** [comment]
well, you can add a primary key to a field that doesn't have duplicate elements in db.
