### ISSUE TITLE
Failed to resolve: io.realm:realm-android:0.73.1 

### ISSUE THREAD

**Issue by sphairo** [realm/realm-java#944]
I'm using Android Studio

**Comment by emanuelez** [comment]
Hello,

please add more details in order for us to be able to help you.
You can see some guidelines on how to file issues here: https://github.com/realm/realm-java/blob/master/README.md#filing-issues

**Comment by cmelchior** [comment]
Hi @sphairo 
Are you using mavenCentral()  or jcenter() as your dependency repository? You should be using jcenter(), also 0.73.1 is a really old release. The newest is 0.79.1

You can find more info on how to setup a project with the latest release here: http://realm.io/docs/java/0.79.0/#installation

Please feel free to reopen if that doesn't work for you.

**Comment by mevdev** [comment]
I needed to run this command in my project from the command line.

```
./gradlew clean assemble --refresh-dependencies
```

**Comment by n0mer** [comment]
still there is a problem:

```groovy
    repositories {
        jcenter()
        mavenCentral()
    }
```

./gradlew clean assemble --refresh-dependencies

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':Application'.
> Could not resolve all dependencies for configuration ':Application:_prodDebugCompile'.
   > Could not find io.realm:realm-android:0.88.2.
     Required by:
         tracker:Application:unspecified

**Comment by beeender** [comment]
@n0mer From 0.88.0, the installation process changes, pleas check https://realm.io/docs/java/latest/#installation

Also, commenting on a very old closed issue might be easily missed by us. So next time try to search for recent issues or create a new one if there isn't.

**Comment by n0mer** [comment]
@beeender thank helped, thanks.

Just as a suggestion - currently gradle reports outdated version as following: "Note: Version 0.88.2 of Realm is now available: http://static.realm.io/downloads/java/latest"

This link is direct download link.

Maybe (as a suggestion) library might provide link to page that explains what's changed, because changing the way how library should be included is sort of breaking change :)

Anyway, problem is sorted - thanks. And sorry for commending in outdated and closed issue - i thought this is regression and this bug can be re-opened.

have a nice day

**Comment by beeender** [comment]
@n0mer 
Glad to hear the problem is solved!
And I think your suggestion makes a lot of send, I just add them to this issue https://github.com/realm/realm-java/issues/2472 
Thanks for the feedback, have a nice day too!
