### ISSUE TITLE
Could not find io.realm.RealmJsonImpl problem

### ISSUE THREAD

**Issue by lirik16** [realm/realm-java#973]
Hello, guys.
I had a problem with the Realm. When i tried  to execute 
Realm mRealm = Realm.getInstance(this);
Realm threw java.lang.ClassNotFoundException: io.realm.RealmJsonImpl. So I wasted a lot of time to solve the problem. I read topics with simular problem but none of the described solutions didn't help me. I started reading the Realm code and thought that RealmProcessor and RealmJSonImplGenerator just didn't start. I read topics about it and it also didn't help me. Finally I solved the problem. I defined my model class like this

public class Contact extends RealmObject {

    @PrimaryKey
    private String mNumber;

    public String getNumber() {
        return mNumber;
    }
    public void setNumber(String number) {
        this.mNumber = number;
    }
}

And looks like Realm generates for mNumber method getMNumber() and doesn't find my getter and setter. And the exception says nothing about it. Just throws java.lang.ClassNotFoundException: io.realm.RealmJsonImpl. It says nothing about that Realm can't find getter and setter for the field.

Please, make errors more human readable and add annotation for defining fields name (like Gson's SerializedName).

**Comment by cmelchior** [comment]
The reason is that those capitalised getter and setter names are not supported. You can see the supported cases here:  https://github.com/realm/realm-java/blob/master/realm-annotations-processor/src/test/resources/some/test/Booleans.java

That said, the support for custom getters and setters could be better and is definitely something we want to add going forward and is already tracked here: https://github.com/realm/realm-java/issues/633

So I am closing this as a duplicate.
